//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
// 
namespace QuanLyKhachSan.QuocTichSVC {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuocTichInfo", Namespace="http://schemas.datacontract.org/2004/07/QuanLyKhachSan")]
    public partial class QuocTichInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int QuocTichIDField;
        
        private string TenQuocTichField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QuocTichID {
            get {
                return this.QuocTichIDField;
            }
            set {
                if ((this.QuocTichIDField.Equals(value) != true)) {
                    this.QuocTichIDField = value;
                    this.RaisePropertyChanged("QuocTichID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenQuocTich {
            get {
                return this.TenQuocTichField;
            }
            set {
                if ((object.ReferenceEquals(this.TenQuocTichField, value) != true)) {
                    this.TenQuocTichField = value;
                    this.RaisePropertyChanged("TenQuocTich");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="QuocTichSVC.QuocTichSVC")]
    public interface QuocTichSVC {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:QuocTichSVC/QuocTich_Add", ReplyAction="urn:QuocTichSVC/QuocTich_AddResponse")]
        System.IAsyncResult BeginQuocTich_Add(string TenQuocTich, System.AsyncCallback callback, object asyncState);
        
        void EndQuocTich_Add(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:QuocTichSVC/QuocTich_Edit", ReplyAction="urn:QuocTichSVC/QuocTich_EditResponse")]
        System.IAsyncResult BeginQuocTich_Edit(int QuocTichID, string TenQuocTich, System.AsyncCallback callback, object asyncState);
        
        void EndQuocTich_Edit(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:QuocTichSVC/QuocTich_Delete", ReplyAction="urn:QuocTichSVC/QuocTich_DeleteResponse")]
        System.IAsyncResult BeginQuocTich_Delete(int QuocTichID, System.AsyncCallback callback, object asyncState);
        
        void EndQuocTich_Delete(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:QuocTichSVC/QuocTich_GetItem", ReplyAction="urn:QuocTichSVC/QuocTich_GetItemResponse")]
        System.IAsyncResult BeginQuocTich_GetItem(int QuocTichID, System.AsyncCallback callback, object asyncState);
        
        QuanLyKhachSan.QuocTichSVC.QuocTichInfo EndQuocTich_GetItem(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:QuocTichSVC/QuocTich_GetItems", ReplyAction="urn:QuocTichSVC/QuocTich_GetItemsResponse")]
        System.IAsyncResult BeginQuocTich_GetItems(System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<QuanLyKhachSan.QuocTichSVC.QuocTichInfo> EndQuocTich_GetItems(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QuocTichSVCChannel : QuanLyKhachSan.QuocTichSVC.QuocTichSVC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QuocTich_GetItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public QuocTich_GetItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public QuanLyKhachSan.QuocTichSVC.QuocTichInfo Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((QuanLyKhachSan.QuocTichSVC.QuocTichInfo)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QuocTich_GetItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public QuocTich_GetItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<QuanLyKhachSan.QuocTichSVC.QuocTichInfo> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<QuanLyKhachSan.QuocTichSVC.QuocTichInfo>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QuocTichSVCClient : System.ServiceModel.ClientBase<QuanLyKhachSan.QuocTichSVC.QuocTichSVC>, QuanLyKhachSan.QuocTichSVC.QuocTichSVC {
        
        private BeginOperationDelegate onBeginQuocTich_AddDelegate;
        
        private EndOperationDelegate onEndQuocTich_AddDelegate;
        
        private System.Threading.SendOrPostCallback onQuocTich_AddCompletedDelegate;
        
        private BeginOperationDelegate onBeginQuocTich_EditDelegate;
        
        private EndOperationDelegate onEndQuocTich_EditDelegate;
        
        private System.Threading.SendOrPostCallback onQuocTich_EditCompletedDelegate;
        
        private BeginOperationDelegate onBeginQuocTich_DeleteDelegate;
        
        private EndOperationDelegate onEndQuocTich_DeleteDelegate;
        
        private System.Threading.SendOrPostCallback onQuocTich_DeleteCompletedDelegate;
        
        private BeginOperationDelegate onBeginQuocTich_GetItemDelegate;
        
        private EndOperationDelegate onEndQuocTich_GetItemDelegate;
        
        private System.Threading.SendOrPostCallback onQuocTich_GetItemCompletedDelegate;
        
        private BeginOperationDelegate onBeginQuocTich_GetItemsDelegate;
        
        private EndOperationDelegate onEndQuocTich_GetItemsDelegate;
        
        private System.Threading.SendOrPostCallback onQuocTich_GetItemsCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public QuocTichSVCClient() {
        }
        
        public QuocTichSVCClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QuocTichSVCClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuocTichSVCClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuocTichSVCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> QuocTich_AddCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> QuocTich_EditCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> QuocTich_DeleteCompleted;
        
        public event System.EventHandler<QuocTich_GetItemCompletedEventArgs> QuocTich_GetItemCompleted;
        
        public event System.EventHandler<QuocTich_GetItemsCompletedEventArgs> QuocTich_GetItemsCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QuanLyKhachSan.QuocTichSVC.QuocTichSVC.BeginQuocTich_Add(string TenQuocTich, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginQuocTich_Add(TenQuocTich, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void QuanLyKhachSan.QuocTichSVC.QuocTichSVC.EndQuocTich_Add(System.IAsyncResult result) {
            base.Channel.EndQuocTich_Add(result);
        }
        
        private System.IAsyncResult OnBeginQuocTich_Add(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string TenQuocTich = ((string)(inValues[0]));
            return ((QuanLyKhachSan.QuocTichSVC.QuocTichSVC)(this)).BeginQuocTich_Add(TenQuocTich, callback, asyncState);
        }
        
        private object[] OnEndQuocTich_Add(System.IAsyncResult result) {
            ((QuanLyKhachSan.QuocTichSVC.QuocTichSVC)(this)).EndQuocTich_Add(result);
            return null;
        }
        
        private void OnQuocTich_AddCompleted(object state) {
            if ((this.QuocTich_AddCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.QuocTich_AddCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void QuocTich_AddAsync(string TenQuocTich) {
            this.QuocTich_AddAsync(TenQuocTich, null);
        }
        
        public void QuocTich_AddAsync(string TenQuocTich, object userState) {
            if ((this.onBeginQuocTich_AddDelegate == null)) {
                this.onBeginQuocTich_AddDelegate = new BeginOperationDelegate(this.OnBeginQuocTich_Add);
            }
            if ((this.onEndQuocTich_AddDelegate == null)) {
                this.onEndQuocTich_AddDelegate = new EndOperationDelegate(this.OnEndQuocTich_Add);
            }
            if ((this.onQuocTich_AddCompletedDelegate == null)) {
                this.onQuocTich_AddCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnQuocTich_AddCompleted);
            }
            base.InvokeAsync(this.onBeginQuocTich_AddDelegate, new object[] {
                        TenQuocTich}, this.onEndQuocTich_AddDelegate, this.onQuocTich_AddCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QuanLyKhachSan.QuocTichSVC.QuocTichSVC.BeginQuocTich_Edit(int QuocTichID, string TenQuocTich, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginQuocTich_Edit(QuocTichID, TenQuocTich, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void QuanLyKhachSan.QuocTichSVC.QuocTichSVC.EndQuocTich_Edit(System.IAsyncResult result) {
            base.Channel.EndQuocTich_Edit(result);
        }
        
        private System.IAsyncResult OnBeginQuocTich_Edit(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int QuocTichID = ((int)(inValues[0]));
            string TenQuocTich = ((string)(inValues[1]));
            return ((QuanLyKhachSan.QuocTichSVC.QuocTichSVC)(this)).BeginQuocTich_Edit(QuocTichID, TenQuocTich, callback, asyncState);
        }
        
        private object[] OnEndQuocTich_Edit(System.IAsyncResult result) {
            ((QuanLyKhachSan.QuocTichSVC.QuocTichSVC)(this)).EndQuocTich_Edit(result);
            return null;
        }
        
        private void OnQuocTich_EditCompleted(object state) {
            if ((this.QuocTich_EditCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.QuocTich_EditCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void QuocTich_EditAsync(int QuocTichID, string TenQuocTich) {
            this.QuocTich_EditAsync(QuocTichID, TenQuocTich, null);
        }
        
        public void QuocTich_EditAsync(int QuocTichID, string TenQuocTich, object userState) {
            if ((this.onBeginQuocTich_EditDelegate == null)) {
                this.onBeginQuocTich_EditDelegate = new BeginOperationDelegate(this.OnBeginQuocTich_Edit);
            }
            if ((this.onEndQuocTich_EditDelegate == null)) {
                this.onEndQuocTich_EditDelegate = new EndOperationDelegate(this.OnEndQuocTich_Edit);
            }
            if ((this.onQuocTich_EditCompletedDelegate == null)) {
                this.onQuocTich_EditCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnQuocTich_EditCompleted);
            }
            base.InvokeAsync(this.onBeginQuocTich_EditDelegate, new object[] {
                        QuocTichID,
                        TenQuocTich}, this.onEndQuocTich_EditDelegate, this.onQuocTich_EditCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QuanLyKhachSan.QuocTichSVC.QuocTichSVC.BeginQuocTich_Delete(int QuocTichID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginQuocTich_Delete(QuocTichID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void QuanLyKhachSan.QuocTichSVC.QuocTichSVC.EndQuocTich_Delete(System.IAsyncResult result) {
            base.Channel.EndQuocTich_Delete(result);
        }
        
        private System.IAsyncResult OnBeginQuocTich_Delete(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int QuocTichID = ((int)(inValues[0]));
            return ((QuanLyKhachSan.QuocTichSVC.QuocTichSVC)(this)).BeginQuocTich_Delete(QuocTichID, callback, asyncState);
        }
        
        private object[] OnEndQuocTich_Delete(System.IAsyncResult result) {
            ((QuanLyKhachSan.QuocTichSVC.QuocTichSVC)(this)).EndQuocTich_Delete(result);
            return null;
        }
        
        private void OnQuocTich_DeleteCompleted(object state) {
            if ((this.QuocTich_DeleteCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.QuocTich_DeleteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void QuocTich_DeleteAsync(int QuocTichID) {
            this.QuocTich_DeleteAsync(QuocTichID, null);
        }
        
        public void QuocTich_DeleteAsync(int QuocTichID, object userState) {
            if ((this.onBeginQuocTich_DeleteDelegate == null)) {
                this.onBeginQuocTich_DeleteDelegate = new BeginOperationDelegate(this.OnBeginQuocTich_Delete);
            }
            if ((this.onEndQuocTich_DeleteDelegate == null)) {
                this.onEndQuocTich_DeleteDelegate = new EndOperationDelegate(this.OnEndQuocTich_Delete);
            }
            if ((this.onQuocTich_DeleteCompletedDelegate == null)) {
                this.onQuocTich_DeleteCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnQuocTich_DeleteCompleted);
            }
            base.InvokeAsync(this.onBeginQuocTich_DeleteDelegate, new object[] {
                        QuocTichID}, this.onEndQuocTich_DeleteDelegate, this.onQuocTich_DeleteCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QuanLyKhachSan.QuocTichSVC.QuocTichSVC.BeginQuocTich_GetItem(int QuocTichID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginQuocTich_GetItem(QuocTichID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuanLyKhachSan.QuocTichSVC.QuocTichInfo QuanLyKhachSan.QuocTichSVC.QuocTichSVC.EndQuocTich_GetItem(System.IAsyncResult result) {
            return base.Channel.EndQuocTich_GetItem(result);
        }
        
        private System.IAsyncResult OnBeginQuocTich_GetItem(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int QuocTichID = ((int)(inValues[0]));
            return ((QuanLyKhachSan.QuocTichSVC.QuocTichSVC)(this)).BeginQuocTich_GetItem(QuocTichID, callback, asyncState);
        }
        
        private object[] OnEndQuocTich_GetItem(System.IAsyncResult result) {
            QuanLyKhachSan.QuocTichSVC.QuocTichInfo retVal = ((QuanLyKhachSan.QuocTichSVC.QuocTichSVC)(this)).EndQuocTich_GetItem(result);
            return new object[] {
                    retVal};
        }
        
        private void OnQuocTich_GetItemCompleted(object state) {
            if ((this.QuocTich_GetItemCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.QuocTich_GetItemCompleted(this, new QuocTich_GetItemCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void QuocTich_GetItemAsync(int QuocTichID) {
            this.QuocTich_GetItemAsync(QuocTichID, null);
        }
        
        public void QuocTich_GetItemAsync(int QuocTichID, object userState) {
            if ((this.onBeginQuocTich_GetItemDelegate == null)) {
                this.onBeginQuocTich_GetItemDelegate = new BeginOperationDelegate(this.OnBeginQuocTich_GetItem);
            }
            if ((this.onEndQuocTich_GetItemDelegate == null)) {
                this.onEndQuocTich_GetItemDelegate = new EndOperationDelegate(this.OnEndQuocTich_GetItem);
            }
            if ((this.onQuocTich_GetItemCompletedDelegate == null)) {
                this.onQuocTich_GetItemCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnQuocTich_GetItemCompleted);
            }
            base.InvokeAsync(this.onBeginQuocTich_GetItemDelegate, new object[] {
                        QuocTichID}, this.onEndQuocTich_GetItemDelegate, this.onQuocTich_GetItemCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QuanLyKhachSan.QuocTichSVC.QuocTichSVC.BeginQuocTich_GetItems(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginQuocTich_GetItems(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<QuanLyKhachSan.QuocTichSVC.QuocTichInfo> QuanLyKhachSan.QuocTichSVC.QuocTichSVC.EndQuocTich_GetItems(System.IAsyncResult result) {
            return base.Channel.EndQuocTich_GetItems(result);
        }
        
        private System.IAsyncResult OnBeginQuocTich_GetItems(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((QuanLyKhachSan.QuocTichSVC.QuocTichSVC)(this)).BeginQuocTich_GetItems(callback, asyncState);
        }
        
        private object[] OnEndQuocTich_GetItems(System.IAsyncResult result) {
            System.Collections.Generic.List<QuanLyKhachSan.QuocTichSVC.QuocTichInfo> retVal = ((QuanLyKhachSan.QuocTichSVC.QuocTichSVC)(this)).EndQuocTich_GetItems(result);
            return new object[] {
                    retVal};
        }
        
        private void OnQuocTich_GetItemsCompleted(object state) {
            if ((this.QuocTich_GetItemsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.QuocTich_GetItemsCompleted(this, new QuocTich_GetItemsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void QuocTich_GetItemsAsync() {
            this.QuocTich_GetItemsAsync(null);
        }
        
        public void QuocTich_GetItemsAsync(object userState) {
            if ((this.onBeginQuocTich_GetItemsDelegate == null)) {
                this.onBeginQuocTich_GetItemsDelegate = new BeginOperationDelegate(this.OnBeginQuocTich_GetItems);
            }
            if ((this.onEndQuocTich_GetItemsDelegate == null)) {
                this.onEndQuocTich_GetItemsDelegate = new EndOperationDelegate(this.OnEndQuocTich_GetItems);
            }
            if ((this.onQuocTich_GetItemsCompletedDelegate == null)) {
                this.onQuocTich_GetItemsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnQuocTich_GetItemsCompleted);
            }
            base.InvokeAsync(this.onBeginQuocTich_GetItemsDelegate, null, this.onEndQuocTich_GetItemsDelegate, this.onQuocTich_GetItemsCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override QuanLyKhachSan.QuocTichSVC.QuocTichSVC CreateChannel() {
            return new QuocTichSVCClientChannel(this);
        }
        
        private class QuocTichSVCClientChannel : ChannelBase<QuanLyKhachSan.QuocTichSVC.QuocTichSVC>, QuanLyKhachSan.QuocTichSVC.QuocTichSVC {
            
            public QuocTichSVCClientChannel(System.ServiceModel.ClientBase<QuanLyKhachSan.QuocTichSVC.QuocTichSVC> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginQuocTich_Add(string TenQuocTich, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = TenQuocTich;
                System.IAsyncResult _result = base.BeginInvoke("QuocTich_Add", _args, callback, asyncState);
                return _result;
            }
            
            public void EndQuocTich_Add(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("QuocTich_Add", _args, result);
            }
            
            public System.IAsyncResult BeginQuocTich_Edit(int QuocTichID, string TenQuocTich, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = QuocTichID;
                _args[1] = TenQuocTich;
                System.IAsyncResult _result = base.BeginInvoke("QuocTich_Edit", _args, callback, asyncState);
                return _result;
            }
            
            public void EndQuocTich_Edit(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("QuocTich_Edit", _args, result);
            }
            
            public System.IAsyncResult BeginQuocTich_Delete(int QuocTichID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = QuocTichID;
                System.IAsyncResult _result = base.BeginInvoke("QuocTich_Delete", _args, callback, asyncState);
                return _result;
            }
            
            public void EndQuocTich_Delete(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("QuocTich_Delete", _args, result);
            }
            
            public System.IAsyncResult BeginQuocTich_GetItem(int QuocTichID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = QuocTichID;
                System.IAsyncResult _result = base.BeginInvoke("QuocTich_GetItem", _args, callback, asyncState);
                return _result;
            }
            
            public QuanLyKhachSan.QuocTichSVC.QuocTichInfo EndQuocTich_GetItem(System.IAsyncResult result) {
                object[] _args = new object[0];
                QuanLyKhachSan.QuocTichSVC.QuocTichInfo _result = ((QuanLyKhachSan.QuocTichSVC.QuocTichInfo)(base.EndInvoke("QuocTich_GetItem", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginQuocTich_GetItems(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("QuocTich_GetItems", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<QuanLyKhachSan.QuocTichSVC.QuocTichInfo> EndQuocTich_GetItems(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<QuanLyKhachSan.QuocTichSVC.QuocTichInfo> _result = ((System.Collections.Generic.List<QuanLyKhachSan.QuocTichSVC.QuocTichInfo>)(base.EndInvoke("QuocTich_GetItems", _args, result)));
                return _result;
            }
        }
    }
}
