//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
// 
namespace QuanLyKhachSan.KhachHangSVC {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KhachHangInfo", Namespace="http://schemas.datacontract.org/2004/07/QuanLyKhachSan")]
    public partial class KhachHangInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string CMNDField;
        
        private int CreatedByUserField;
        
        private string CreatedDateField;
        
        private int DeletedByUserField;
        
        private string DeletedDateField;
        
        private string DiaChiField;
        
        private string DienThoaiField;
        
        private int GioiTinhField;
        
        private string HoTenField;
        
        private int IsDeletedField;
        
        private int KhachHangIDField;
        
        private int ModifiedByUserField;
        
        private string ModifiedDateField;
        
        private string NgayNhapCanhField;
        
        private string NgaySinhField;
        
        private string NguoiTiepNhanField;
        
        private string NoiSinhField;
        
        private int QuocTichIDField;
        
        private string SoVisaField;
        
        private string TamTruDenNgayField;
        
        private string TamTruTuNgayField;
        
        private string ThoiHanVisaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CMND {
            get {
                return this.CMNDField;
            }
            set {
                if ((object.ReferenceEquals(this.CMNDField, value) != true)) {
                    this.CMNDField = value;
                    this.RaisePropertyChanged("CMND");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CreatedByUser {
            get {
                return this.CreatedByUserField;
            }
            set {
                if ((this.CreatedByUserField.Equals(value) != true)) {
                    this.CreatedByUserField = value;
                    this.RaisePropertyChanged("CreatedByUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedDateField, value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DeletedByUser {
            get {
                return this.DeletedByUserField;
            }
            set {
                if ((this.DeletedByUserField.Equals(value) != true)) {
                    this.DeletedByUserField = value;
                    this.RaisePropertyChanged("DeletedByUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeletedDate {
            get {
                return this.DeletedDateField;
            }
            set {
                if ((object.ReferenceEquals(this.DeletedDateField, value) != true)) {
                    this.DeletedDateField = value;
                    this.RaisePropertyChanged("DeletedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiaChi {
            get {
                return this.DiaChiField;
            }
            set {
                if ((object.ReferenceEquals(this.DiaChiField, value) != true)) {
                    this.DiaChiField = value;
                    this.RaisePropertyChanged("DiaChi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DienThoai {
            get {
                return this.DienThoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.DienThoaiField, value) != true)) {
                    this.DienThoaiField = value;
                    this.RaisePropertyChanged("DienThoai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GioiTinh {
            get {
                return this.GioiTinhField;
            }
            set {
                if ((this.GioiTinhField.Equals(value) != true)) {
                    this.GioiTinhField = value;
                    this.RaisePropertyChanged("GioiTinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HoTen {
            get {
                return this.HoTenField;
            }
            set {
                if ((object.ReferenceEquals(this.HoTenField, value) != true)) {
                    this.HoTenField = value;
                    this.RaisePropertyChanged("HoTen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IsDeleted {
            get {
                return this.IsDeletedField;
            }
            set {
                if ((this.IsDeletedField.Equals(value) != true)) {
                    this.IsDeletedField = value;
                    this.RaisePropertyChanged("IsDeleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KhachHangID {
            get {
                return this.KhachHangIDField;
            }
            set {
                if ((this.KhachHangIDField.Equals(value) != true)) {
                    this.KhachHangIDField = value;
                    this.RaisePropertyChanged("KhachHangID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ModifiedByUser {
            get {
                return this.ModifiedByUserField;
            }
            set {
                if ((this.ModifiedByUserField.Equals(value) != true)) {
                    this.ModifiedByUserField = value;
                    this.RaisePropertyChanged("ModifiedByUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ModifiedDateField, value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NgayNhapCanh {
            get {
                return this.NgayNhapCanhField;
            }
            set {
                if ((object.ReferenceEquals(this.NgayNhapCanhField, value) != true)) {
                    this.NgayNhapCanhField = value;
                    this.RaisePropertyChanged("NgayNhapCanh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NgaySinh {
            get {
                return this.NgaySinhField;
            }
            set {
                if ((object.ReferenceEquals(this.NgaySinhField, value) != true)) {
                    this.NgaySinhField = value;
                    this.RaisePropertyChanged("NgaySinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NguoiTiepNhan {
            get {
                return this.NguoiTiepNhanField;
            }
            set {
                if ((object.ReferenceEquals(this.NguoiTiepNhanField, value) != true)) {
                    this.NguoiTiepNhanField = value;
                    this.RaisePropertyChanged("NguoiTiepNhan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NoiSinh {
            get {
                return this.NoiSinhField;
            }
            set {
                if ((object.ReferenceEquals(this.NoiSinhField, value) != true)) {
                    this.NoiSinhField = value;
                    this.RaisePropertyChanged("NoiSinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QuocTichID {
            get {
                return this.QuocTichIDField;
            }
            set {
                if ((this.QuocTichIDField.Equals(value) != true)) {
                    this.QuocTichIDField = value;
                    this.RaisePropertyChanged("QuocTichID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SoVisa {
            get {
                return this.SoVisaField;
            }
            set {
                if ((object.ReferenceEquals(this.SoVisaField, value) != true)) {
                    this.SoVisaField = value;
                    this.RaisePropertyChanged("SoVisa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TamTruDenNgay {
            get {
                return this.TamTruDenNgayField;
            }
            set {
                if ((object.ReferenceEquals(this.TamTruDenNgayField, value) != true)) {
                    this.TamTruDenNgayField = value;
                    this.RaisePropertyChanged("TamTruDenNgay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TamTruTuNgay {
            get {
                return this.TamTruTuNgayField;
            }
            set {
                if ((object.ReferenceEquals(this.TamTruTuNgayField, value) != true)) {
                    this.TamTruTuNgayField = value;
                    this.RaisePropertyChanged("TamTruTuNgay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ThoiHanVisa {
            get {
                return this.ThoiHanVisaField;
            }
            set {
                if ((object.ReferenceEquals(this.ThoiHanVisaField, value) != true)) {
                    this.ThoiHanVisaField = value;
                    this.RaisePropertyChanged("ThoiHanVisa");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="KhachHangSVC.KhachHangSVC")]
    public interface KhachHangSVC {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:KhachHangSVC/KhachHang_Add", ReplyAction="urn:KhachHangSVC/KhachHang_AddResponse")]
        System.IAsyncResult BeginKhachHang_Add(
                    string HoTen, 
                    string DiaChi, 
                    string DienThoai, 
                    string CMND, 
                    string NgaySinh, 
                    string NoiSinh, 
                    string SoVisa, 
                    string ThoiHanVisa, 
                    string NguoiTiepNhan, 
                    string NgayNhapCanh, 
                    string TamTruTuNgay, 
                    string TamTruDenNgay, 
                    int QuocTichID, 
                    int GioiTinh, 
                    int CreatedByUser, 
                    string CreatedDate, 
                    System.AsyncCallback callback, 
                    object asyncState);
        
        void EndKhachHang_Add(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:KhachHangSVC/KhachHang_Edit", ReplyAction="urn:KhachHangSVC/KhachHang_EditResponse")]
        System.IAsyncResult BeginKhachHang_Edit(
                    int KhachHangID, 
                    string HoTen, 
                    string DiaChi, 
                    string DienThoai, 
                    string CMND, 
                    string NgaySinh, 
                    string NoiSinh, 
                    string SoVisa, 
                    string ThoiHanVisa, 
                    string NguoiTiepNhan, 
                    string NgayNhapCanh, 
                    string TamTruTuNgay, 
                    string TamTruDenNgay, 
                    int QuocTichID, 
                    int GioiTinh, 
                    int ModifiedByUser, 
                    string ModifiedDate, 
                    System.AsyncCallback callback, 
                    object asyncState);
        
        void EndKhachHang_Edit(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:KhachHangSVC/KhachHang_Delete", ReplyAction="urn:KhachHangSVC/KhachHang_DeleteResponse")]
        System.IAsyncResult BeginKhachHang_Delete(int KhachHangID, int DeletedByUser, string DeletedDate, System.AsyncCallback callback, object asyncState);
        
        void EndKhachHang_Delete(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:KhachHangSVC/KhachHang_GetItem", ReplyAction="urn:KhachHangSVC/KhachHang_GetItemResponse")]
        System.IAsyncResult BeginKhachHang_GetItem(int KhachHangID, System.AsyncCallback callback, object asyncState);
        
        QuanLyKhachSan.KhachHangSVC.KhachHangInfo EndKhachHang_GetItem(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:KhachHangSVC/KhachHang_GetItems", ReplyAction="urn:KhachHangSVC/KhachHang_GetItemsResponse")]
        System.IAsyncResult BeginKhachHang_GetItems(int KhachHangID, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<QuanLyKhachSan.KhachHangSVC.KhachHangInfo> EndKhachHang_GetItems(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:KhachHangSVC/KhachHang_GetItemsInPhong", ReplyAction="urn:KhachHangSVC/KhachHang_GetItemsInPhongResponse")]
        System.IAsyncResult BeginKhachHang_GetItemsInPhong(int KhachHangID, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<QuanLyKhachSan.KhachHangSVC.KhachHangInfo> EndKhachHang_GetItemsInPhong(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface KhachHangSVCChannel : QuanLyKhachSan.KhachHangSVC.KhachHangSVC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KhachHang_GetItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public KhachHang_GetItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public QuanLyKhachSan.KhachHangSVC.KhachHangInfo Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((QuanLyKhachSan.KhachHangSVC.KhachHangInfo)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KhachHang_GetItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public KhachHang_GetItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<QuanLyKhachSan.KhachHangSVC.KhachHangInfo> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<QuanLyKhachSan.KhachHangSVC.KhachHangInfo>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KhachHang_GetItemsInPhongCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public KhachHang_GetItemsInPhongCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<QuanLyKhachSan.KhachHangSVC.KhachHangInfo> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<QuanLyKhachSan.KhachHangSVC.KhachHangInfo>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KhachHangSVCClient : System.ServiceModel.ClientBase<QuanLyKhachSan.KhachHangSVC.KhachHangSVC>, QuanLyKhachSan.KhachHangSVC.KhachHangSVC {
        
        private BeginOperationDelegate onBeginKhachHang_AddDelegate;
        
        private EndOperationDelegate onEndKhachHang_AddDelegate;
        
        private System.Threading.SendOrPostCallback onKhachHang_AddCompletedDelegate;
        
        private BeginOperationDelegate onBeginKhachHang_EditDelegate;
        
        private EndOperationDelegate onEndKhachHang_EditDelegate;
        
        private System.Threading.SendOrPostCallback onKhachHang_EditCompletedDelegate;
        
        private BeginOperationDelegate onBeginKhachHang_DeleteDelegate;
        
        private EndOperationDelegate onEndKhachHang_DeleteDelegate;
        
        private System.Threading.SendOrPostCallback onKhachHang_DeleteCompletedDelegate;
        
        private BeginOperationDelegate onBeginKhachHang_GetItemDelegate;
        
        private EndOperationDelegate onEndKhachHang_GetItemDelegate;
        
        private System.Threading.SendOrPostCallback onKhachHang_GetItemCompletedDelegate;
        
        private BeginOperationDelegate onBeginKhachHang_GetItemsDelegate;
        
        private EndOperationDelegate onEndKhachHang_GetItemsDelegate;
        
        private System.Threading.SendOrPostCallback onKhachHang_GetItemsCompletedDelegate;
        
        private BeginOperationDelegate onBeginKhachHang_GetItemsInPhongDelegate;
        
        private EndOperationDelegate onEndKhachHang_GetItemsInPhongDelegate;
        
        private System.Threading.SendOrPostCallback onKhachHang_GetItemsInPhongCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public KhachHangSVCClient() {
        }
        
        public KhachHangSVCClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KhachHangSVCClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KhachHangSVCClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KhachHangSVCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> KhachHang_AddCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> KhachHang_EditCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> KhachHang_DeleteCompleted;
        
        public event System.EventHandler<KhachHang_GetItemCompletedEventArgs> KhachHang_GetItemCompleted;
        
        public event System.EventHandler<KhachHang_GetItemsCompletedEventArgs> KhachHang_GetItemsCompleted;
        
        public event System.EventHandler<KhachHang_GetItemsInPhongCompletedEventArgs> KhachHang_GetItemsInPhongCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QuanLyKhachSan.KhachHangSVC.KhachHangSVC.BeginKhachHang_Add(
                    string HoTen, 
                    string DiaChi, 
                    string DienThoai, 
                    string CMND, 
                    string NgaySinh, 
                    string NoiSinh, 
                    string SoVisa, 
                    string ThoiHanVisa, 
                    string NguoiTiepNhan, 
                    string NgayNhapCanh, 
                    string TamTruTuNgay, 
                    string TamTruDenNgay, 
                    int QuocTichID, 
                    int GioiTinh, 
                    int CreatedByUser, 
                    string CreatedDate, 
                    System.AsyncCallback callback, 
                    object asyncState) {
            return base.Channel.BeginKhachHang_Add(HoTen, DiaChi, DienThoai, CMND, NgaySinh, NoiSinh, SoVisa, ThoiHanVisa, NguoiTiepNhan, NgayNhapCanh, TamTruTuNgay, TamTruDenNgay, QuocTichID, GioiTinh, CreatedByUser, CreatedDate, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void QuanLyKhachSan.KhachHangSVC.KhachHangSVC.EndKhachHang_Add(System.IAsyncResult result) {
            base.Channel.EndKhachHang_Add(result);
        }
        
        private System.IAsyncResult OnBeginKhachHang_Add(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string HoTen = ((string)(inValues[0]));
            string DiaChi = ((string)(inValues[1]));
            string DienThoai = ((string)(inValues[2]));
            string CMND = ((string)(inValues[3]));
            string NgaySinh = ((string)(inValues[4]));
            string NoiSinh = ((string)(inValues[5]));
            string SoVisa = ((string)(inValues[6]));
            string ThoiHanVisa = ((string)(inValues[7]));
            string NguoiTiepNhan = ((string)(inValues[8]));
            string NgayNhapCanh = ((string)(inValues[9]));
            string TamTruTuNgay = ((string)(inValues[10]));
            string TamTruDenNgay = ((string)(inValues[11]));
            int QuocTichID = ((int)(inValues[12]));
            int GioiTinh = ((int)(inValues[13]));
            int CreatedByUser = ((int)(inValues[14]));
            string CreatedDate = ((string)(inValues[15]));
            return ((QuanLyKhachSan.KhachHangSVC.KhachHangSVC)(this)).BeginKhachHang_Add(HoTen, DiaChi, DienThoai, CMND, NgaySinh, NoiSinh, SoVisa, ThoiHanVisa, NguoiTiepNhan, NgayNhapCanh, TamTruTuNgay, TamTruDenNgay, QuocTichID, GioiTinh, CreatedByUser, CreatedDate, callback, asyncState);
        }
        
        private object[] OnEndKhachHang_Add(System.IAsyncResult result) {
            ((QuanLyKhachSan.KhachHangSVC.KhachHangSVC)(this)).EndKhachHang_Add(result);
            return null;
        }
        
        private void OnKhachHang_AddCompleted(object state) {
            if ((this.KhachHang_AddCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.KhachHang_AddCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void KhachHang_AddAsync(
                    string HoTen, 
                    string DiaChi, 
                    string DienThoai, 
                    string CMND, 
                    string NgaySinh, 
                    string NoiSinh, 
                    string SoVisa, 
                    string ThoiHanVisa, 
                    string NguoiTiepNhan, 
                    string NgayNhapCanh, 
                    string TamTruTuNgay, 
                    string TamTruDenNgay, 
                    int QuocTichID, 
                    int GioiTinh, 
                    int CreatedByUser, 
                    string CreatedDate) {
            this.KhachHang_AddAsync(HoTen, DiaChi, DienThoai, CMND, NgaySinh, NoiSinh, SoVisa, ThoiHanVisa, NguoiTiepNhan, NgayNhapCanh, TamTruTuNgay, TamTruDenNgay, QuocTichID, GioiTinh, CreatedByUser, CreatedDate, null);
        }
        
        public void KhachHang_AddAsync(
                    string HoTen, 
                    string DiaChi, 
                    string DienThoai, 
                    string CMND, 
                    string NgaySinh, 
                    string NoiSinh, 
                    string SoVisa, 
                    string ThoiHanVisa, 
                    string NguoiTiepNhan, 
                    string NgayNhapCanh, 
                    string TamTruTuNgay, 
                    string TamTruDenNgay, 
                    int QuocTichID, 
                    int GioiTinh, 
                    int CreatedByUser, 
                    string CreatedDate, 
                    object userState) {
            if ((this.onBeginKhachHang_AddDelegate == null)) {
                this.onBeginKhachHang_AddDelegate = new BeginOperationDelegate(this.OnBeginKhachHang_Add);
            }
            if ((this.onEndKhachHang_AddDelegate == null)) {
                this.onEndKhachHang_AddDelegate = new EndOperationDelegate(this.OnEndKhachHang_Add);
            }
            if ((this.onKhachHang_AddCompletedDelegate == null)) {
                this.onKhachHang_AddCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnKhachHang_AddCompleted);
            }
            base.InvokeAsync(this.onBeginKhachHang_AddDelegate, new object[] {
                        HoTen,
                        DiaChi,
                        DienThoai,
                        CMND,
                        NgaySinh,
                        NoiSinh,
                        SoVisa,
                        ThoiHanVisa,
                        NguoiTiepNhan,
                        NgayNhapCanh,
                        TamTruTuNgay,
                        TamTruDenNgay,
                        QuocTichID,
                        GioiTinh,
                        CreatedByUser,
                        CreatedDate}, this.onEndKhachHang_AddDelegate, this.onKhachHang_AddCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QuanLyKhachSan.KhachHangSVC.KhachHangSVC.BeginKhachHang_Edit(
                    int KhachHangID, 
                    string HoTen, 
                    string DiaChi, 
                    string DienThoai, 
                    string CMND, 
                    string NgaySinh, 
                    string NoiSinh, 
                    string SoVisa, 
                    string ThoiHanVisa, 
                    string NguoiTiepNhan, 
                    string NgayNhapCanh, 
                    string TamTruTuNgay, 
                    string TamTruDenNgay, 
                    int QuocTichID, 
                    int GioiTinh, 
                    int ModifiedByUser, 
                    string ModifiedDate, 
                    System.AsyncCallback callback, 
                    object asyncState) {
            return base.Channel.BeginKhachHang_Edit(KhachHangID, HoTen, DiaChi, DienThoai, CMND, NgaySinh, NoiSinh, SoVisa, ThoiHanVisa, NguoiTiepNhan, NgayNhapCanh, TamTruTuNgay, TamTruDenNgay, QuocTichID, GioiTinh, ModifiedByUser, ModifiedDate, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void QuanLyKhachSan.KhachHangSVC.KhachHangSVC.EndKhachHang_Edit(System.IAsyncResult result) {
            base.Channel.EndKhachHang_Edit(result);
        }
        
        private System.IAsyncResult OnBeginKhachHang_Edit(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int KhachHangID = ((int)(inValues[0]));
            string HoTen = ((string)(inValues[1]));
            string DiaChi = ((string)(inValues[2]));
            string DienThoai = ((string)(inValues[3]));
            string CMND = ((string)(inValues[4]));
            string NgaySinh = ((string)(inValues[5]));
            string NoiSinh = ((string)(inValues[6]));
            string SoVisa = ((string)(inValues[7]));
            string ThoiHanVisa = ((string)(inValues[8]));
            string NguoiTiepNhan = ((string)(inValues[9]));
            string NgayNhapCanh = ((string)(inValues[10]));
            string TamTruTuNgay = ((string)(inValues[11]));
            string TamTruDenNgay = ((string)(inValues[12]));
            int QuocTichID = ((int)(inValues[13]));
            int GioiTinh = ((int)(inValues[14]));
            int ModifiedByUser = ((int)(inValues[15]));
            string ModifiedDate = ((string)(inValues[16]));
            return ((QuanLyKhachSan.KhachHangSVC.KhachHangSVC)(this)).BeginKhachHang_Edit(KhachHangID, HoTen, DiaChi, DienThoai, CMND, NgaySinh, NoiSinh, SoVisa, ThoiHanVisa, NguoiTiepNhan, NgayNhapCanh, TamTruTuNgay, TamTruDenNgay, QuocTichID, GioiTinh, ModifiedByUser, ModifiedDate, callback, asyncState);
        }
        
        private object[] OnEndKhachHang_Edit(System.IAsyncResult result) {
            ((QuanLyKhachSan.KhachHangSVC.KhachHangSVC)(this)).EndKhachHang_Edit(result);
            return null;
        }
        
        private void OnKhachHang_EditCompleted(object state) {
            if ((this.KhachHang_EditCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.KhachHang_EditCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void KhachHang_EditAsync(
                    int KhachHangID, 
                    string HoTen, 
                    string DiaChi, 
                    string DienThoai, 
                    string CMND, 
                    string NgaySinh, 
                    string NoiSinh, 
                    string SoVisa, 
                    string ThoiHanVisa, 
                    string NguoiTiepNhan, 
                    string NgayNhapCanh, 
                    string TamTruTuNgay, 
                    string TamTruDenNgay, 
                    int QuocTichID, 
                    int GioiTinh, 
                    int ModifiedByUser, 
                    string ModifiedDate) {
            this.KhachHang_EditAsync(KhachHangID, HoTen, DiaChi, DienThoai, CMND, NgaySinh, NoiSinh, SoVisa, ThoiHanVisa, NguoiTiepNhan, NgayNhapCanh, TamTruTuNgay, TamTruDenNgay, QuocTichID, GioiTinh, ModifiedByUser, ModifiedDate, null);
        }
        
        public void KhachHang_EditAsync(
                    int KhachHangID, 
                    string HoTen, 
                    string DiaChi, 
                    string DienThoai, 
                    string CMND, 
                    string NgaySinh, 
                    string NoiSinh, 
                    string SoVisa, 
                    string ThoiHanVisa, 
                    string NguoiTiepNhan, 
                    string NgayNhapCanh, 
                    string TamTruTuNgay, 
                    string TamTruDenNgay, 
                    int QuocTichID, 
                    int GioiTinh, 
                    int ModifiedByUser, 
                    string ModifiedDate, 
                    object userState) {
            if ((this.onBeginKhachHang_EditDelegate == null)) {
                this.onBeginKhachHang_EditDelegate = new BeginOperationDelegate(this.OnBeginKhachHang_Edit);
            }
            if ((this.onEndKhachHang_EditDelegate == null)) {
                this.onEndKhachHang_EditDelegate = new EndOperationDelegate(this.OnEndKhachHang_Edit);
            }
            if ((this.onKhachHang_EditCompletedDelegate == null)) {
                this.onKhachHang_EditCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnKhachHang_EditCompleted);
            }
            base.InvokeAsync(this.onBeginKhachHang_EditDelegate, new object[] {
                        KhachHangID,
                        HoTen,
                        DiaChi,
                        DienThoai,
                        CMND,
                        NgaySinh,
                        NoiSinh,
                        SoVisa,
                        ThoiHanVisa,
                        NguoiTiepNhan,
                        NgayNhapCanh,
                        TamTruTuNgay,
                        TamTruDenNgay,
                        QuocTichID,
                        GioiTinh,
                        ModifiedByUser,
                        ModifiedDate}, this.onEndKhachHang_EditDelegate, this.onKhachHang_EditCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QuanLyKhachSan.KhachHangSVC.KhachHangSVC.BeginKhachHang_Delete(int KhachHangID, int DeletedByUser, string DeletedDate, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginKhachHang_Delete(KhachHangID, DeletedByUser, DeletedDate, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void QuanLyKhachSan.KhachHangSVC.KhachHangSVC.EndKhachHang_Delete(System.IAsyncResult result) {
            base.Channel.EndKhachHang_Delete(result);
        }
        
        private System.IAsyncResult OnBeginKhachHang_Delete(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int KhachHangID = ((int)(inValues[0]));
            int DeletedByUser = ((int)(inValues[1]));
            string DeletedDate = ((string)(inValues[2]));
            return ((QuanLyKhachSan.KhachHangSVC.KhachHangSVC)(this)).BeginKhachHang_Delete(KhachHangID, DeletedByUser, DeletedDate, callback, asyncState);
        }
        
        private object[] OnEndKhachHang_Delete(System.IAsyncResult result) {
            ((QuanLyKhachSan.KhachHangSVC.KhachHangSVC)(this)).EndKhachHang_Delete(result);
            return null;
        }
        
        private void OnKhachHang_DeleteCompleted(object state) {
            if ((this.KhachHang_DeleteCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.KhachHang_DeleteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void KhachHang_DeleteAsync(int KhachHangID, int DeletedByUser, string DeletedDate) {
            this.KhachHang_DeleteAsync(KhachHangID, DeletedByUser, DeletedDate, null);
        }
        
        public void KhachHang_DeleteAsync(int KhachHangID, int DeletedByUser, string DeletedDate, object userState) {
            if ((this.onBeginKhachHang_DeleteDelegate == null)) {
                this.onBeginKhachHang_DeleteDelegate = new BeginOperationDelegate(this.OnBeginKhachHang_Delete);
            }
            if ((this.onEndKhachHang_DeleteDelegate == null)) {
                this.onEndKhachHang_DeleteDelegate = new EndOperationDelegate(this.OnEndKhachHang_Delete);
            }
            if ((this.onKhachHang_DeleteCompletedDelegate == null)) {
                this.onKhachHang_DeleteCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnKhachHang_DeleteCompleted);
            }
            base.InvokeAsync(this.onBeginKhachHang_DeleteDelegate, new object[] {
                        KhachHangID,
                        DeletedByUser,
                        DeletedDate}, this.onEndKhachHang_DeleteDelegate, this.onKhachHang_DeleteCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QuanLyKhachSan.KhachHangSVC.KhachHangSVC.BeginKhachHang_GetItem(int KhachHangID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginKhachHang_GetItem(KhachHangID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuanLyKhachSan.KhachHangSVC.KhachHangInfo QuanLyKhachSan.KhachHangSVC.KhachHangSVC.EndKhachHang_GetItem(System.IAsyncResult result) {
            return base.Channel.EndKhachHang_GetItem(result);
        }
        
        private System.IAsyncResult OnBeginKhachHang_GetItem(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int KhachHangID = ((int)(inValues[0]));
            return ((QuanLyKhachSan.KhachHangSVC.KhachHangSVC)(this)).BeginKhachHang_GetItem(KhachHangID, callback, asyncState);
        }
        
        private object[] OnEndKhachHang_GetItem(System.IAsyncResult result) {
            QuanLyKhachSan.KhachHangSVC.KhachHangInfo retVal = ((QuanLyKhachSan.KhachHangSVC.KhachHangSVC)(this)).EndKhachHang_GetItem(result);
            return new object[] {
                    retVal};
        }
        
        private void OnKhachHang_GetItemCompleted(object state) {
            if ((this.KhachHang_GetItemCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.KhachHang_GetItemCompleted(this, new KhachHang_GetItemCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void KhachHang_GetItemAsync(int KhachHangID) {
            this.KhachHang_GetItemAsync(KhachHangID, null);
        }
        
        public void KhachHang_GetItemAsync(int KhachHangID, object userState) {
            if ((this.onBeginKhachHang_GetItemDelegate == null)) {
                this.onBeginKhachHang_GetItemDelegate = new BeginOperationDelegate(this.OnBeginKhachHang_GetItem);
            }
            if ((this.onEndKhachHang_GetItemDelegate == null)) {
                this.onEndKhachHang_GetItemDelegate = new EndOperationDelegate(this.OnEndKhachHang_GetItem);
            }
            if ((this.onKhachHang_GetItemCompletedDelegate == null)) {
                this.onKhachHang_GetItemCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnKhachHang_GetItemCompleted);
            }
            base.InvokeAsync(this.onBeginKhachHang_GetItemDelegate, new object[] {
                        KhachHangID}, this.onEndKhachHang_GetItemDelegate, this.onKhachHang_GetItemCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QuanLyKhachSan.KhachHangSVC.KhachHangSVC.BeginKhachHang_GetItems(int KhachHangID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginKhachHang_GetItems(KhachHangID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<QuanLyKhachSan.KhachHangSVC.KhachHangInfo> QuanLyKhachSan.KhachHangSVC.KhachHangSVC.EndKhachHang_GetItems(System.IAsyncResult result) {
            return base.Channel.EndKhachHang_GetItems(result);
        }
        
        private System.IAsyncResult OnBeginKhachHang_GetItems(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int KhachHangID = ((int)(inValues[0]));
            return ((QuanLyKhachSan.KhachHangSVC.KhachHangSVC)(this)).BeginKhachHang_GetItems(KhachHangID, callback, asyncState);
        }
        
        private object[] OnEndKhachHang_GetItems(System.IAsyncResult result) {
            System.Collections.Generic.List<QuanLyKhachSan.KhachHangSVC.KhachHangInfo> retVal = ((QuanLyKhachSan.KhachHangSVC.KhachHangSVC)(this)).EndKhachHang_GetItems(result);
            return new object[] {
                    retVal};
        }
        
        private void OnKhachHang_GetItemsCompleted(object state) {
            if ((this.KhachHang_GetItemsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.KhachHang_GetItemsCompleted(this, new KhachHang_GetItemsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void KhachHang_GetItemsAsync(int KhachHangID) {
            this.KhachHang_GetItemsAsync(KhachHangID, null);
        }
        
        public void KhachHang_GetItemsAsync(int KhachHangID, object userState) {
            if ((this.onBeginKhachHang_GetItemsDelegate == null)) {
                this.onBeginKhachHang_GetItemsDelegate = new BeginOperationDelegate(this.OnBeginKhachHang_GetItems);
            }
            if ((this.onEndKhachHang_GetItemsDelegate == null)) {
                this.onEndKhachHang_GetItemsDelegate = new EndOperationDelegate(this.OnEndKhachHang_GetItems);
            }
            if ((this.onKhachHang_GetItemsCompletedDelegate == null)) {
                this.onKhachHang_GetItemsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnKhachHang_GetItemsCompleted);
            }
            base.InvokeAsync(this.onBeginKhachHang_GetItemsDelegate, new object[] {
                        KhachHangID}, this.onEndKhachHang_GetItemsDelegate, this.onKhachHang_GetItemsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QuanLyKhachSan.KhachHangSVC.KhachHangSVC.BeginKhachHang_GetItemsInPhong(int KhachHangID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginKhachHang_GetItemsInPhong(KhachHangID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<QuanLyKhachSan.KhachHangSVC.KhachHangInfo> QuanLyKhachSan.KhachHangSVC.KhachHangSVC.EndKhachHang_GetItemsInPhong(System.IAsyncResult result) {
            return base.Channel.EndKhachHang_GetItemsInPhong(result);
        }
        
        private System.IAsyncResult OnBeginKhachHang_GetItemsInPhong(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int KhachHangID = ((int)(inValues[0]));
            return ((QuanLyKhachSan.KhachHangSVC.KhachHangSVC)(this)).BeginKhachHang_GetItemsInPhong(KhachHangID, callback, asyncState);
        }
        
        private object[] OnEndKhachHang_GetItemsInPhong(System.IAsyncResult result) {
            System.Collections.Generic.List<QuanLyKhachSan.KhachHangSVC.KhachHangInfo> retVal = ((QuanLyKhachSan.KhachHangSVC.KhachHangSVC)(this)).EndKhachHang_GetItemsInPhong(result);
            return new object[] {
                    retVal};
        }
        
        private void OnKhachHang_GetItemsInPhongCompleted(object state) {
            if ((this.KhachHang_GetItemsInPhongCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.KhachHang_GetItemsInPhongCompleted(this, new KhachHang_GetItemsInPhongCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void KhachHang_GetItemsInPhongAsync(int KhachHangID) {
            this.KhachHang_GetItemsInPhongAsync(KhachHangID, null);
        }
        
        public void KhachHang_GetItemsInPhongAsync(int KhachHangID, object userState) {
            if ((this.onBeginKhachHang_GetItemsInPhongDelegate == null)) {
                this.onBeginKhachHang_GetItemsInPhongDelegate = new BeginOperationDelegate(this.OnBeginKhachHang_GetItemsInPhong);
            }
            if ((this.onEndKhachHang_GetItemsInPhongDelegate == null)) {
                this.onEndKhachHang_GetItemsInPhongDelegate = new EndOperationDelegate(this.OnEndKhachHang_GetItemsInPhong);
            }
            if ((this.onKhachHang_GetItemsInPhongCompletedDelegate == null)) {
                this.onKhachHang_GetItemsInPhongCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnKhachHang_GetItemsInPhongCompleted);
            }
            base.InvokeAsync(this.onBeginKhachHang_GetItemsInPhongDelegate, new object[] {
                        KhachHangID}, this.onEndKhachHang_GetItemsInPhongDelegate, this.onKhachHang_GetItemsInPhongCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override QuanLyKhachSan.KhachHangSVC.KhachHangSVC CreateChannel() {
            return new KhachHangSVCClientChannel(this);
        }
        
        private class KhachHangSVCClientChannel : ChannelBase<QuanLyKhachSan.KhachHangSVC.KhachHangSVC>, QuanLyKhachSan.KhachHangSVC.KhachHangSVC {
            
            public KhachHangSVCClientChannel(System.ServiceModel.ClientBase<QuanLyKhachSan.KhachHangSVC.KhachHangSVC> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginKhachHang_Add(
                        string HoTen, 
                        string DiaChi, 
                        string DienThoai, 
                        string CMND, 
                        string NgaySinh, 
                        string NoiSinh, 
                        string SoVisa, 
                        string ThoiHanVisa, 
                        string NguoiTiepNhan, 
                        string NgayNhapCanh, 
                        string TamTruTuNgay, 
                        string TamTruDenNgay, 
                        int QuocTichID, 
                        int GioiTinh, 
                        int CreatedByUser, 
                        string CreatedDate, 
                        System.AsyncCallback callback, 
                        object asyncState) {
                object[] _args = new object[16];
                _args[0] = HoTen;
                _args[1] = DiaChi;
                _args[2] = DienThoai;
                _args[3] = CMND;
                _args[4] = NgaySinh;
                _args[5] = NoiSinh;
                _args[6] = SoVisa;
                _args[7] = ThoiHanVisa;
                _args[8] = NguoiTiepNhan;
                _args[9] = NgayNhapCanh;
                _args[10] = TamTruTuNgay;
                _args[11] = TamTruDenNgay;
                _args[12] = QuocTichID;
                _args[13] = GioiTinh;
                _args[14] = CreatedByUser;
                _args[15] = CreatedDate;
                System.IAsyncResult _result = base.BeginInvoke("KhachHang_Add", _args, callback, asyncState);
                return _result;
            }
            
            public void EndKhachHang_Add(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("KhachHang_Add", _args, result);
            }
            
            public System.IAsyncResult BeginKhachHang_Edit(
                        int KhachHangID, 
                        string HoTen, 
                        string DiaChi, 
                        string DienThoai, 
                        string CMND, 
                        string NgaySinh, 
                        string NoiSinh, 
                        string SoVisa, 
                        string ThoiHanVisa, 
                        string NguoiTiepNhan, 
                        string NgayNhapCanh, 
                        string TamTruTuNgay, 
                        string TamTruDenNgay, 
                        int QuocTichID, 
                        int GioiTinh, 
                        int ModifiedByUser, 
                        string ModifiedDate, 
                        System.AsyncCallback callback, 
                        object asyncState) {
                object[] _args = new object[17];
                _args[0] = KhachHangID;
                _args[1] = HoTen;
                _args[2] = DiaChi;
                _args[3] = DienThoai;
                _args[4] = CMND;
                _args[5] = NgaySinh;
                _args[6] = NoiSinh;
                _args[7] = SoVisa;
                _args[8] = ThoiHanVisa;
                _args[9] = NguoiTiepNhan;
                _args[10] = NgayNhapCanh;
                _args[11] = TamTruTuNgay;
                _args[12] = TamTruDenNgay;
                _args[13] = QuocTichID;
                _args[14] = GioiTinh;
                _args[15] = ModifiedByUser;
                _args[16] = ModifiedDate;
                System.IAsyncResult _result = base.BeginInvoke("KhachHang_Edit", _args, callback, asyncState);
                return _result;
            }
            
            public void EndKhachHang_Edit(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("KhachHang_Edit", _args, result);
            }
            
            public System.IAsyncResult BeginKhachHang_Delete(int KhachHangID, int DeletedByUser, string DeletedDate, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = KhachHangID;
                _args[1] = DeletedByUser;
                _args[2] = DeletedDate;
                System.IAsyncResult _result = base.BeginInvoke("KhachHang_Delete", _args, callback, asyncState);
                return _result;
            }
            
            public void EndKhachHang_Delete(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("KhachHang_Delete", _args, result);
            }
            
            public System.IAsyncResult BeginKhachHang_GetItem(int KhachHangID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = KhachHangID;
                System.IAsyncResult _result = base.BeginInvoke("KhachHang_GetItem", _args, callback, asyncState);
                return _result;
            }
            
            public QuanLyKhachSan.KhachHangSVC.KhachHangInfo EndKhachHang_GetItem(System.IAsyncResult result) {
                object[] _args = new object[0];
                QuanLyKhachSan.KhachHangSVC.KhachHangInfo _result = ((QuanLyKhachSan.KhachHangSVC.KhachHangInfo)(base.EndInvoke("KhachHang_GetItem", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginKhachHang_GetItems(int KhachHangID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = KhachHangID;
                System.IAsyncResult _result = base.BeginInvoke("KhachHang_GetItems", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<QuanLyKhachSan.KhachHangSVC.KhachHangInfo> EndKhachHang_GetItems(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<QuanLyKhachSan.KhachHangSVC.KhachHangInfo> _result = ((System.Collections.Generic.List<QuanLyKhachSan.KhachHangSVC.KhachHangInfo>)(base.EndInvoke("KhachHang_GetItems", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginKhachHang_GetItemsInPhong(int KhachHangID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = KhachHangID;
                System.IAsyncResult _result = base.BeginInvoke("KhachHang_GetItemsInPhong", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<QuanLyKhachSan.KhachHangSVC.KhachHangInfo> EndKhachHang_GetItemsInPhong(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<QuanLyKhachSan.KhachHangSVC.KhachHangInfo> _result = ((System.Collections.Generic.List<QuanLyKhachSan.KhachHangSVC.KhachHangInfo>)(base.EndInvoke("KhachHang_GetItemsInPhong", _args, result)));
                return _result;
            }
        }
    }
}
