//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
// 
namespace QuanLyKhachSan.HoaDon_KhachHangSVC {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Phong_KhachHangInfo", Namespace="http://schemas.datacontract.org/2004/07/QuanLyKhachSan")]
    public partial class Phong_KhachHangInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string CMNDField;
        
        private string HoTenField;
        
        private int HoaDonIDField;
        
        private int KhachHangIDField;
        
        private string NgayBatDauField;
        
        private string NgayKetThucField;
        
        private int PhongIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CMND {
            get {
                return this.CMNDField;
            }
            set {
                if ((object.ReferenceEquals(this.CMNDField, value) != true)) {
                    this.CMNDField = value;
                    this.RaisePropertyChanged("CMND");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HoTen {
            get {
                return this.HoTenField;
            }
            set {
                if ((object.ReferenceEquals(this.HoTenField, value) != true)) {
                    this.HoTenField = value;
                    this.RaisePropertyChanged("HoTen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HoaDonID {
            get {
                return this.HoaDonIDField;
            }
            set {
                if ((this.HoaDonIDField.Equals(value) != true)) {
                    this.HoaDonIDField = value;
                    this.RaisePropertyChanged("HoaDonID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KhachHangID {
            get {
                return this.KhachHangIDField;
            }
            set {
                if ((this.KhachHangIDField.Equals(value) != true)) {
                    this.KhachHangIDField = value;
                    this.RaisePropertyChanged("KhachHangID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NgayBatDau {
            get {
                return this.NgayBatDauField;
            }
            set {
                if ((object.ReferenceEquals(this.NgayBatDauField, value) != true)) {
                    this.NgayBatDauField = value;
                    this.RaisePropertyChanged("NgayBatDau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NgayKetThuc {
            get {
                return this.NgayKetThucField;
            }
            set {
                if ((object.ReferenceEquals(this.NgayKetThucField, value) != true)) {
                    this.NgayKetThucField = value;
                    this.RaisePropertyChanged("NgayKetThuc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PhongID {
            get {
                return this.PhongIDField;
            }
            set {
                if ((this.PhongIDField.Equals(value) != true)) {
                    this.PhongIDField = value;
                    this.RaisePropertyChanged("PhongID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="HoaDon_KhachHangSVC.HoaDon_KhachHangSVC")]
    public interface HoaDon_KhachHangSVC {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:HoaDon_KhachHangSVC/HoaDon_KhachHang_Add", ReplyAction="urn:HoaDon_KhachHangSVC/HoaDon_KhachHang_AddResponse")]
        System.IAsyncResult BeginHoaDon_KhachHang_Add(string LoaiHoaDon, int KhachHangId, int PhongID, string NgayBatDau, int GioBatDau, int PhutBatDau, int NgayBatDau_So, int ThangBatDau, int NamBatDau, string NgayKetThuc, System.AsyncCallback callback, object asyncState);
        
        void EndHoaDon_KhachHang_Add(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:HoaDon_KhachHangSVC/Phong_KhachHang_GetItems", ReplyAction="urn:HoaDon_KhachHangSVC/Phong_KhachHang_GetItemsResponse")]
        System.IAsyncResult BeginPhong_KhachHang_GetItems(int HoaDonID, int PhongID, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<QuanLyKhachSan.HoaDon_KhachHangSVC.Phong_KhachHangInfo> EndPhong_KhachHang_GetItems(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:HoaDon_KhachHangSVC/Phong_KhachHang_Delete", ReplyAction="urn:HoaDon_KhachHangSVC/Phong_KhachHang_DeleteResponse")]
        System.IAsyncResult BeginPhong_KhachHang_Delete(int HoaDonID, int KhachHangID, System.AsyncCallback callback, object asyncState);
        
        void EndPhong_KhachHang_Delete(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:HoaDon_KhachHangSVC/Phong_KhachHang_DatPhong", ReplyAction="urn:HoaDon_KhachHangSVC/Phong_KhachHang_DatPhongResponse")]
        System.IAsyncResult BeginPhong_KhachHang_DatPhong(int PhongID, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<QuanLyKhachSan.HoaDon_KhachHangSVC.Phong_KhachHangInfo> EndPhong_KhachHang_DatPhong(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:HoaDon_KhachHangSVC/HoaDon_KhachHang_EditPhong", ReplyAction="urn:HoaDon_KhachHangSVC/HoaDon_KhachHang_EditPhongResponse")]
        System.IAsyncResult BeginHoaDon_KhachHang_EditPhong(int HoaDonID, int PhongID, System.AsyncCallback callback, object asyncState);
        
        void EndHoaDon_KhachHang_EditPhong(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HoaDon_KhachHangSVCChannel : QuanLyKhachSan.HoaDon_KhachHangSVC.HoaDon_KhachHangSVC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Phong_KhachHang_GetItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public Phong_KhachHang_GetItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<QuanLyKhachSan.HoaDon_KhachHangSVC.Phong_KhachHangInfo> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<QuanLyKhachSan.HoaDon_KhachHangSVC.Phong_KhachHangInfo>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Phong_KhachHang_DatPhongCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public Phong_KhachHang_DatPhongCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<QuanLyKhachSan.HoaDon_KhachHangSVC.Phong_KhachHangInfo> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<QuanLyKhachSan.HoaDon_KhachHangSVC.Phong_KhachHangInfo>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HoaDon_KhachHangSVCClient : System.ServiceModel.ClientBase<QuanLyKhachSan.HoaDon_KhachHangSVC.HoaDon_KhachHangSVC>, QuanLyKhachSan.HoaDon_KhachHangSVC.HoaDon_KhachHangSVC {
        
        private BeginOperationDelegate onBeginHoaDon_KhachHang_AddDelegate;
        
        private EndOperationDelegate onEndHoaDon_KhachHang_AddDelegate;
        
        private System.Threading.SendOrPostCallback onHoaDon_KhachHang_AddCompletedDelegate;
        
        private BeginOperationDelegate onBeginPhong_KhachHang_GetItemsDelegate;
        
        private EndOperationDelegate onEndPhong_KhachHang_GetItemsDelegate;
        
        private System.Threading.SendOrPostCallback onPhong_KhachHang_GetItemsCompletedDelegate;
        
        private BeginOperationDelegate onBeginPhong_KhachHang_DeleteDelegate;
        
        private EndOperationDelegate onEndPhong_KhachHang_DeleteDelegate;
        
        private System.Threading.SendOrPostCallback onPhong_KhachHang_DeleteCompletedDelegate;
        
        private BeginOperationDelegate onBeginPhong_KhachHang_DatPhongDelegate;
        
        private EndOperationDelegate onEndPhong_KhachHang_DatPhongDelegate;
        
        private System.Threading.SendOrPostCallback onPhong_KhachHang_DatPhongCompletedDelegate;
        
        private BeginOperationDelegate onBeginHoaDon_KhachHang_EditPhongDelegate;
        
        private EndOperationDelegate onEndHoaDon_KhachHang_EditPhongDelegate;
        
        private System.Threading.SendOrPostCallback onHoaDon_KhachHang_EditPhongCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public HoaDon_KhachHangSVCClient() {
        }
        
        public HoaDon_KhachHangSVCClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HoaDon_KhachHangSVCClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HoaDon_KhachHangSVCClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HoaDon_KhachHangSVCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> HoaDon_KhachHang_AddCompleted;
        
        public event System.EventHandler<Phong_KhachHang_GetItemsCompletedEventArgs> Phong_KhachHang_GetItemsCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> Phong_KhachHang_DeleteCompleted;
        
        public event System.EventHandler<Phong_KhachHang_DatPhongCompletedEventArgs> Phong_KhachHang_DatPhongCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> HoaDon_KhachHang_EditPhongCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QuanLyKhachSan.HoaDon_KhachHangSVC.HoaDon_KhachHangSVC.BeginHoaDon_KhachHang_Add(string LoaiHoaDon, int KhachHangId, int PhongID, string NgayBatDau, int GioBatDau, int PhutBatDau, int NgayBatDau_So, int ThangBatDau, int NamBatDau, string NgayKetThuc, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginHoaDon_KhachHang_Add(LoaiHoaDon, KhachHangId, PhongID, NgayBatDau, GioBatDau, PhutBatDau, NgayBatDau_So, ThangBatDau, NamBatDau, NgayKetThuc, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void QuanLyKhachSan.HoaDon_KhachHangSVC.HoaDon_KhachHangSVC.EndHoaDon_KhachHang_Add(System.IAsyncResult result) {
            base.Channel.EndHoaDon_KhachHang_Add(result);
        }
        
        private System.IAsyncResult OnBeginHoaDon_KhachHang_Add(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string LoaiHoaDon = ((string)(inValues[0]));
            int KhachHangId = ((int)(inValues[1]));
            int PhongID = ((int)(inValues[2]));
            string NgayBatDau = ((string)(inValues[3]));
            int GioBatDau = ((int)(inValues[4]));
            int PhutBatDau = ((int)(inValues[5]));
            int NgayBatDau_So = ((int)(inValues[6]));
            int ThangBatDau = ((int)(inValues[7]));
            int NamBatDau = ((int)(inValues[8]));
            string NgayKetThuc = ((string)(inValues[9]));
            return ((QuanLyKhachSan.HoaDon_KhachHangSVC.HoaDon_KhachHangSVC)(this)).BeginHoaDon_KhachHang_Add(LoaiHoaDon, KhachHangId, PhongID, NgayBatDau, GioBatDau, PhutBatDau, NgayBatDau_So, ThangBatDau, NamBatDau, NgayKetThuc, callback, asyncState);
        }
        
        private object[] OnEndHoaDon_KhachHang_Add(System.IAsyncResult result) {
            ((QuanLyKhachSan.HoaDon_KhachHangSVC.HoaDon_KhachHangSVC)(this)).EndHoaDon_KhachHang_Add(result);
            return null;
        }
        
        private void OnHoaDon_KhachHang_AddCompleted(object state) {
            if ((this.HoaDon_KhachHang_AddCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.HoaDon_KhachHang_AddCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void HoaDon_KhachHang_AddAsync(string LoaiHoaDon, int KhachHangId, int PhongID, string NgayBatDau, int GioBatDau, int PhutBatDau, int NgayBatDau_So, int ThangBatDau, int NamBatDau, string NgayKetThuc) {
            this.HoaDon_KhachHang_AddAsync(LoaiHoaDon, KhachHangId, PhongID, NgayBatDau, GioBatDau, PhutBatDau, NgayBatDau_So, ThangBatDau, NamBatDau, NgayKetThuc, null);
        }
        
        public void HoaDon_KhachHang_AddAsync(string LoaiHoaDon, int KhachHangId, int PhongID, string NgayBatDau, int GioBatDau, int PhutBatDau, int NgayBatDau_So, int ThangBatDau, int NamBatDau, string NgayKetThuc, object userState) {
            if ((this.onBeginHoaDon_KhachHang_AddDelegate == null)) {
                this.onBeginHoaDon_KhachHang_AddDelegate = new BeginOperationDelegate(this.OnBeginHoaDon_KhachHang_Add);
            }
            if ((this.onEndHoaDon_KhachHang_AddDelegate == null)) {
                this.onEndHoaDon_KhachHang_AddDelegate = new EndOperationDelegate(this.OnEndHoaDon_KhachHang_Add);
            }
            if ((this.onHoaDon_KhachHang_AddCompletedDelegate == null)) {
                this.onHoaDon_KhachHang_AddCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHoaDon_KhachHang_AddCompleted);
            }
            base.InvokeAsync(this.onBeginHoaDon_KhachHang_AddDelegate, new object[] {
                        LoaiHoaDon,
                        KhachHangId,
                        PhongID,
                        NgayBatDau,
                        GioBatDau,
                        PhutBatDau,
                        NgayBatDau_So,
                        ThangBatDau,
                        NamBatDau,
                        NgayKetThuc}, this.onEndHoaDon_KhachHang_AddDelegate, this.onHoaDon_KhachHang_AddCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QuanLyKhachSan.HoaDon_KhachHangSVC.HoaDon_KhachHangSVC.BeginPhong_KhachHang_GetItems(int HoaDonID, int PhongID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginPhong_KhachHang_GetItems(HoaDonID, PhongID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<QuanLyKhachSan.HoaDon_KhachHangSVC.Phong_KhachHangInfo> QuanLyKhachSan.HoaDon_KhachHangSVC.HoaDon_KhachHangSVC.EndPhong_KhachHang_GetItems(System.IAsyncResult result) {
            return base.Channel.EndPhong_KhachHang_GetItems(result);
        }
        
        private System.IAsyncResult OnBeginPhong_KhachHang_GetItems(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int HoaDonID = ((int)(inValues[0]));
            int PhongID = ((int)(inValues[1]));
            return ((QuanLyKhachSan.HoaDon_KhachHangSVC.HoaDon_KhachHangSVC)(this)).BeginPhong_KhachHang_GetItems(HoaDonID, PhongID, callback, asyncState);
        }
        
        private object[] OnEndPhong_KhachHang_GetItems(System.IAsyncResult result) {
            System.Collections.Generic.List<QuanLyKhachSan.HoaDon_KhachHangSVC.Phong_KhachHangInfo> retVal = ((QuanLyKhachSan.HoaDon_KhachHangSVC.HoaDon_KhachHangSVC)(this)).EndPhong_KhachHang_GetItems(result);
            return new object[] {
                    retVal};
        }
        
        private void OnPhong_KhachHang_GetItemsCompleted(object state) {
            if ((this.Phong_KhachHang_GetItemsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.Phong_KhachHang_GetItemsCompleted(this, new Phong_KhachHang_GetItemsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void Phong_KhachHang_GetItemsAsync(int HoaDonID, int PhongID) {
            this.Phong_KhachHang_GetItemsAsync(HoaDonID, PhongID, null);
        }
        
        public void Phong_KhachHang_GetItemsAsync(int HoaDonID, int PhongID, object userState) {
            if ((this.onBeginPhong_KhachHang_GetItemsDelegate == null)) {
                this.onBeginPhong_KhachHang_GetItemsDelegate = new BeginOperationDelegate(this.OnBeginPhong_KhachHang_GetItems);
            }
            if ((this.onEndPhong_KhachHang_GetItemsDelegate == null)) {
                this.onEndPhong_KhachHang_GetItemsDelegate = new EndOperationDelegate(this.OnEndPhong_KhachHang_GetItems);
            }
            if ((this.onPhong_KhachHang_GetItemsCompletedDelegate == null)) {
                this.onPhong_KhachHang_GetItemsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnPhong_KhachHang_GetItemsCompleted);
            }
            base.InvokeAsync(this.onBeginPhong_KhachHang_GetItemsDelegate, new object[] {
                        HoaDonID,
                        PhongID}, this.onEndPhong_KhachHang_GetItemsDelegate, this.onPhong_KhachHang_GetItemsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QuanLyKhachSan.HoaDon_KhachHangSVC.HoaDon_KhachHangSVC.BeginPhong_KhachHang_Delete(int HoaDonID, int KhachHangID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginPhong_KhachHang_Delete(HoaDonID, KhachHangID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void QuanLyKhachSan.HoaDon_KhachHangSVC.HoaDon_KhachHangSVC.EndPhong_KhachHang_Delete(System.IAsyncResult result) {
            base.Channel.EndPhong_KhachHang_Delete(result);
        }
        
        private System.IAsyncResult OnBeginPhong_KhachHang_Delete(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int HoaDonID = ((int)(inValues[0]));
            int KhachHangID = ((int)(inValues[1]));
            return ((QuanLyKhachSan.HoaDon_KhachHangSVC.HoaDon_KhachHangSVC)(this)).BeginPhong_KhachHang_Delete(HoaDonID, KhachHangID, callback, asyncState);
        }
        
        private object[] OnEndPhong_KhachHang_Delete(System.IAsyncResult result) {
            ((QuanLyKhachSan.HoaDon_KhachHangSVC.HoaDon_KhachHangSVC)(this)).EndPhong_KhachHang_Delete(result);
            return null;
        }
        
        private void OnPhong_KhachHang_DeleteCompleted(object state) {
            if ((this.Phong_KhachHang_DeleteCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.Phong_KhachHang_DeleteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void Phong_KhachHang_DeleteAsync(int HoaDonID, int KhachHangID) {
            this.Phong_KhachHang_DeleteAsync(HoaDonID, KhachHangID, null);
        }
        
        public void Phong_KhachHang_DeleteAsync(int HoaDonID, int KhachHangID, object userState) {
            if ((this.onBeginPhong_KhachHang_DeleteDelegate == null)) {
                this.onBeginPhong_KhachHang_DeleteDelegate = new BeginOperationDelegate(this.OnBeginPhong_KhachHang_Delete);
            }
            if ((this.onEndPhong_KhachHang_DeleteDelegate == null)) {
                this.onEndPhong_KhachHang_DeleteDelegate = new EndOperationDelegate(this.OnEndPhong_KhachHang_Delete);
            }
            if ((this.onPhong_KhachHang_DeleteCompletedDelegate == null)) {
                this.onPhong_KhachHang_DeleteCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnPhong_KhachHang_DeleteCompleted);
            }
            base.InvokeAsync(this.onBeginPhong_KhachHang_DeleteDelegate, new object[] {
                        HoaDonID,
                        KhachHangID}, this.onEndPhong_KhachHang_DeleteDelegate, this.onPhong_KhachHang_DeleteCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QuanLyKhachSan.HoaDon_KhachHangSVC.HoaDon_KhachHangSVC.BeginPhong_KhachHang_DatPhong(int PhongID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginPhong_KhachHang_DatPhong(PhongID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<QuanLyKhachSan.HoaDon_KhachHangSVC.Phong_KhachHangInfo> QuanLyKhachSan.HoaDon_KhachHangSVC.HoaDon_KhachHangSVC.EndPhong_KhachHang_DatPhong(System.IAsyncResult result) {
            return base.Channel.EndPhong_KhachHang_DatPhong(result);
        }
        
        private System.IAsyncResult OnBeginPhong_KhachHang_DatPhong(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int PhongID = ((int)(inValues[0]));
            return ((QuanLyKhachSan.HoaDon_KhachHangSVC.HoaDon_KhachHangSVC)(this)).BeginPhong_KhachHang_DatPhong(PhongID, callback, asyncState);
        }
        
        private object[] OnEndPhong_KhachHang_DatPhong(System.IAsyncResult result) {
            System.Collections.Generic.List<QuanLyKhachSan.HoaDon_KhachHangSVC.Phong_KhachHangInfo> retVal = ((QuanLyKhachSan.HoaDon_KhachHangSVC.HoaDon_KhachHangSVC)(this)).EndPhong_KhachHang_DatPhong(result);
            return new object[] {
                    retVal};
        }
        
        private void OnPhong_KhachHang_DatPhongCompleted(object state) {
            if ((this.Phong_KhachHang_DatPhongCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.Phong_KhachHang_DatPhongCompleted(this, new Phong_KhachHang_DatPhongCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void Phong_KhachHang_DatPhongAsync(int PhongID) {
            this.Phong_KhachHang_DatPhongAsync(PhongID, null);
        }
        
        public void Phong_KhachHang_DatPhongAsync(int PhongID, object userState) {
            if ((this.onBeginPhong_KhachHang_DatPhongDelegate == null)) {
                this.onBeginPhong_KhachHang_DatPhongDelegate = new BeginOperationDelegate(this.OnBeginPhong_KhachHang_DatPhong);
            }
            if ((this.onEndPhong_KhachHang_DatPhongDelegate == null)) {
                this.onEndPhong_KhachHang_DatPhongDelegate = new EndOperationDelegate(this.OnEndPhong_KhachHang_DatPhong);
            }
            if ((this.onPhong_KhachHang_DatPhongCompletedDelegate == null)) {
                this.onPhong_KhachHang_DatPhongCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnPhong_KhachHang_DatPhongCompleted);
            }
            base.InvokeAsync(this.onBeginPhong_KhachHang_DatPhongDelegate, new object[] {
                        PhongID}, this.onEndPhong_KhachHang_DatPhongDelegate, this.onPhong_KhachHang_DatPhongCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QuanLyKhachSan.HoaDon_KhachHangSVC.HoaDon_KhachHangSVC.BeginHoaDon_KhachHang_EditPhong(int HoaDonID, int PhongID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginHoaDon_KhachHang_EditPhong(HoaDonID, PhongID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void QuanLyKhachSan.HoaDon_KhachHangSVC.HoaDon_KhachHangSVC.EndHoaDon_KhachHang_EditPhong(System.IAsyncResult result) {
            base.Channel.EndHoaDon_KhachHang_EditPhong(result);
        }
        
        private System.IAsyncResult OnBeginHoaDon_KhachHang_EditPhong(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int HoaDonID = ((int)(inValues[0]));
            int PhongID = ((int)(inValues[1]));
            return ((QuanLyKhachSan.HoaDon_KhachHangSVC.HoaDon_KhachHangSVC)(this)).BeginHoaDon_KhachHang_EditPhong(HoaDonID, PhongID, callback, asyncState);
        }
        
        private object[] OnEndHoaDon_KhachHang_EditPhong(System.IAsyncResult result) {
            ((QuanLyKhachSan.HoaDon_KhachHangSVC.HoaDon_KhachHangSVC)(this)).EndHoaDon_KhachHang_EditPhong(result);
            return null;
        }
        
        private void OnHoaDon_KhachHang_EditPhongCompleted(object state) {
            if ((this.HoaDon_KhachHang_EditPhongCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.HoaDon_KhachHang_EditPhongCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void HoaDon_KhachHang_EditPhongAsync(int HoaDonID, int PhongID) {
            this.HoaDon_KhachHang_EditPhongAsync(HoaDonID, PhongID, null);
        }
        
        public void HoaDon_KhachHang_EditPhongAsync(int HoaDonID, int PhongID, object userState) {
            if ((this.onBeginHoaDon_KhachHang_EditPhongDelegate == null)) {
                this.onBeginHoaDon_KhachHang_EditPhongDelegate = new BeginOperationDelegate(this.OnBeginHoaDon_KhachHang_EditPhong);
            }
            if ((this.onEndHoaDon_KhachHang_EditPhongDelegate == null)) {
                this.onEndHoaDon_KhachHang_EditPhongDelegate = new EndOperationDelegate(this.OnEndHoaDon_KhachHang_EditPhong);
            }
            if ((this.onHoaDon_KhachHang_EditPhongCompletedDelegate == null)) {
                this.onHoaDon_KhachHang_EditPhongCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHoaDon_KhachHang_EditPhongCompleted);
            }
            base.InvokeAsync(this.onBeginHoaDon_KhachHang_EditPhongDelegate, new object[] {
                        HoaDonID,
                        PhongID}, this.onEndHoaDon_KhachHang_EditPhongDelegate, this.onHoaDon_KhachHang_EditPhongCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override QuanLyKhachSan.HoaDon_KhachHangSVC.HoaDon_KhachHangSVC CreateChannel() {
            return new HoaDon_KhachHangSVCClientChannel(this);
        }
        
        private class HoaDon_KhachHangSVCClientChannel : ChannelBase<QuanLyKhachSan.HoaDon_KhachHangSVC.HoaDon_KhachHangSVC>, QuanLyKhachSan.HoaDon_KhachHangSVC.HoaDon_KhachHangSVC {
            
            public HoaDon_KhachHangSVCClientChannel(System.ServiceModel.ClientBase<QuanLyKhachSan.HoaDon_KhachHangSVC.HoaDon_KhachHangSVC> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginHoaDon_KhachHang_Add(string LoaiHoaDon, int KhachHangId, int PhongID, string NgayBatDau, int GioBatDau, int PhutBatDau, int NgayBatDau_So, int ThangBatDau, int NamBatDau, string NgayKetThuc, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[10];
                _args[0] = LoaiHoaDon;
                _args[1] = KhachHangId;
                _args[2] = PhongID;
                _args[3] = NgayBatDau;
                _args[4] = GioBatDau;
                _args[5] = PhutBatDau;
                _args[6] = NgayBatDau_So;
                _args[7] = ThangBatDau;
                _args[8] = NamBatDau;
                _args[9] = NgayKetThuc;
                System.IAsyncResult _result = base.BeginInvoke("HoaDon_KhachHang_Add", _args, callback, asyncState);
                return _result;
            }
            
            public void EndHoaDon_KhachHang_Add(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("HoaDon_KhachHang_Add", _args, result);
            }
            
            public System.IAsyncResult BeginPhong_KhachHang_GetItems(int HoaDonID, int PhongID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = HoaDonID;
                _args[1] = PhongID;
                System.IAsyncResult _result = base.BeginInvoke("Phong_KhachHang_GetItems", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<QuanLyKhachSan.HoaDon_KhachHangSVC.Phong_KhachHangInfo> EndPhong_KhachHang_GetItems(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<QuanLyKhachSan.HoaDon_KhachHangSVC.Phong_KhachHangInfo> _result = ((System.Collections.Generic.List<QuanLyKhachSan.HoaDon_KhachHangSVC.Phong_KhachHangInfo>)(base.EndInvoke("Phong_KhachHang_GetItems", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginPhong_KhachHang_Delete(int HoaDonID, int KhachHangID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = HoaDonID;
                _args[1] = KhachHangID;
                System.IAsyncResult _result = base.BeginInvoke("Phong_KhachHang_Delete", _args, callback, asyncState);
                return _result;
            }
            
            public void EndPhong_KhachHang_Delete(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("Phong_KhachHang_Delete", _args, result);
            }
            
            public System.IAsyncResult BeginPhong_KhachHang_DatPhong(int PhongID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = PhongID;
                System.IAsyncResult _result = base.BeginInvoke("Phong_KhachHang_DatPhong", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<QuanLyKhachSan.HoaDon_KhachHangSVC.Phong_KhachHangInfo> EndPhong_KhachHang_DatPhong(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<QuanLyKhachSan.HoaDon_KhachHangSVC.Phong_KhachHangInfo> _result = ((System.Collections.Generic.List<QuanLyKhachSan.HoaDon_KhachHangSVC.Phong_KhachHangInfo>)(base.EndInvoke("Phong_KhachHang_DatPhong", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginHoaDon_KhachHang_EditPhong(int HoaDonID, int PhongID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = HoaDonID;
                _args[1] = PhongID;
                System.IAsyncResult _result = base.BeginInvoke("HoaDon_KhachHang_EditPhong", _args, callback, asyncState);
                return _result;
            }
            
            public void EndHoaDon_KhachHang_EditPhong(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("HoaDon_KhachHang_EditPhong", _args, result);
            }
        }
    }
}
