//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
// 
namespace QuanLyKhachSan.LoaiPhongSVC {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoaiPhongInfo", Namespace="http://schemas.datacontract.org/2004/07/QuanLyKhachSan")]
    public partial class LoaiPhongInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int LoaiPhongIDField;
        
        private string LoaiPhongNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LoaiPhongID {
            get {
                return this.LoaiPhongIDField;
            }
            set {
                if ((this.LoaiPhongIDField.Equals(value) != true)) {
                    this.LoaiPhongIDField = value;
                    this.RaisePropertyChanged("LoaiPhongID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoaiPhongName {
            get {
                return this.LoaiPhongNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LoaiPhongNameField, value) != true)) {
                    this.LoaiPhongNameField = value;
                    this.RaisePropertyChanged("LoaiPhongName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="LoaiPhongSVC.LoaiPhongSVC")]
    public interface LoaiPhongSVC {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:LoaiPhongSVC/LoaiPhong_Add", ReplyAction="urn:LoaiPhongSVC/LoaiPhong_AddResponse")]
        System.IAsyncResult BeginLoaiPhong_Add(string LoaiPhongName, System.AsyncCallback callback, object asyncState);
        
        void EndLoaiPhong_Add(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:LoaiPhongSVC/LoaiPhong_Edit", ReplyAction="urn:LoaiPhongSVC/LoaiPhong_EditResponse")]
        System.IAsyncResult BeginLoaiPhong_Edit(int LoaiPhongID, string LoaiPhongName, System.AsyncCallback callback, object asyncState);
        
        void EndLoaiPhong_Edit(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:LoaiPhongSVC/LoaiPhong_Delete", ReplyAction="urn:LoaiPhongSVC/LoaiPhong_DeleteResponse")]
        System.IAsyncResult BeginLoaiPhong_Delete(int LoaiPhongID, System.AsyncCallback callback, object asyncState);
        
        void EndLoaiPhong_Delete(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:LoaiPhongSVC/LoaiPhong_GetItem", ReplyAction="urn:LoaiPhongSVC/LoaiPhong_GetItemResponse")]
        System.IAsyncResult BeginLoaiPhong_GetItem(int LoaiPhongID, System.AsyncCallback callback, object asyncState);
        
        QuanLyKhachSan.LoaiPhongSVC.LoaiPhongInfo EndLoaiPhong_GetItem(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:LoaiPhongSVC/LoaiPhong_GetItems", ReplyAction="urn:LoaiPhongSVC/LoaiPhong_GetItemsResponse")]
        System.IAsyncResult BeginLoaiPhong_GetItems(System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<QuanLyKhachSan.LoaiPhongSVC.LoaiPhongInfo> EndLoaiPhong_GetItems(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LoaiPhongSVCChannel : QuanLyKhachSan.LoaiPhongSVC.LoaiPhongSVC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoaiPhong_GetItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public LoaiPhong_GetItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public QuanLyKhachSan.LoaiPhongSVC.LoaiPhongInfo Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((QuanLyKhachSan.LoaiPhongSVC.LoaiPhongInfo)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoaiPhong_GetItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public LoaiPhong_GetItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<QuanLyKhachSan.LoaiPhongSVC.LoaiPhongInfo> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<QuanLyKhachSan.LoaiPhongSVC.LoaiPhongInfo>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoaiPhongSVCClient : System.ServiceModel.ClientBase<QuanLyKhachSan.LoaiPhongSVC.LoaiPhongSVC>, QuanLyKhachSan.LoaiPhongSVC.LoaiPhongSVC {
        
        private BeginOperationDelegate onBeginLoaiPhong_AddDelegate;
        
        private EndOperationDelegate onEndLoaiPhong_AddDelegate;
        
        private System.Threading.SendOrPostCallback onLoaiPhong_AddCompletedDelegate;
        
        private BeginOperationDelegate onBeginLoaiPhong_EditDelegate;
        
        private EndOperationDelegate onEndLoaiPhong_EditDelegate;
        
        private System.Threading.SendOrPostCallback onLoaiPhong_EditCompletedDelegate;
        
        private BeginOperationDelegate onBeginLoaiPhong_DeleteDelegate;
        
        private EndOperationDelegate onEndLoaiPhong_DeleteDelegate;
        
        private System.Threading.SendOrPostCallback onLoaiPhong_DeleteCompletedDelegate;
        
        private BeginOperationDelegate onBeginLoaiPhong_GetItemDelegate;
        
        private EndOperationDelegate onEndLoaiPhong_GetItemDelegate;
        
        private System.Threading.SendOrPostCallback onLoaiPhong_GetItemCompletedDelegate;
        
        private BeginOperationDelegate onBeginLoaiPhong_GetItemsDelegate;
        
        private EndOperationDelegate onEndLoaiPhong_GetItemsDelegate;
        
        private System.Threading.SendOrPostCallback onLoaiPhong_GetItemsCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public LoaiPhongSVCClient() {
        }
        
        public LoaiPhongSVCClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoaiPhongSVCClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoaiPhongSVCClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoaiPhongSVCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> LoaiPhong_AddCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> LoaiPhong_EditCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> LoaiPhong_DeleteCompleted;
        
        public event System.EventHandler<LoaiPhong_GetItemCompletedEventArgs> LoaiPhong_GetItemCompleted;
        
        public event System.EventHandler<LoaiPhong_GetItemsCompletedEventArgs> LoaiPhong_GetItemsCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QuanLyKhachSan.LoaiPhongSVC.LoaiPhongSVC.BeginLoaiPhong_Add(string LoaiPhongName, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLoaiPhong_Add(LoaiPhongName, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void QuanLyKhachSan.LoaiPhongSVC.LoaiPhongSVC.EndLoaiPhong_Add(System.IAsyncResult result) {
            base.Channel.EndLoaiPhong_Add(result);
        }
        
        private System.IAsyncResult OnBeginLoaiPhong_Add(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string LoaiPhongName = ((string)(inValues[0]));
            return ((QuanLyKhachSan.LoaiPhongSVC.LoaiPhongSVC)(this)).BeginLoaiPhong_Add(LoaiPhongName, callback, asyncState);
        }
        
        private object[] OnEndLoaiPhong_Add(System.IAsyncResult result) {
            ((QuanLyKhachSan.LoaiPhongSVC.LoaiPhongSVC)(this)).EndLoaiPhong_Add(result);
            return null;
        }
        
        private void OnLoaiPhong_AddCompleted(object state) {
            if ((this.LoaiPhong_AddCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LoaiPhong_AddCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LoaiPhong_AddAsync(string LoaiPhongName) {
            this.LoaiPhong_AddAsync(LoaiPhongName, null);
        }
        
        public void LoaiPhong_AddAsync(string LoaiPhongName, object userState) {
            if ((this.onBeginLoaiPhong_AddDelegate == null)) {
                this.onBeginLoaiPhong_AddDelegate = new BeginOperationDelegate(this.OnBeginLoaiPhong_Add);
            }
            if ((this.onEndLoaiPhong_AddDelegate == null)) {
                this.onEndLoaiPhong_AddDelegate = new EndOperationDelegate(this.OnEndLoaiPhong_Add);
            }
            if ((this.onLoaiPhong_AddCompletedDelegate == null)) {
                this.onLoaiPhong_AddCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLoaiPhong_AddCompleted);
            }
            base.InvokeAsync(this.onBeginLoaiPhong_AddDelegate, new object[] {
                        LoaiPhongName}, this.onEndLoaiPhong_AddDelegate, this.onLoaiPhong_AddCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QuanLyKhachSan.LoaiPhongSVC.LoaiPhongSVC.BeginLoaiPhong_Edit(int LoaiPhongID, string LoaiPhongName, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLoaiPhong_Edit(LoaiPhongID, LoaiPhongName, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void QuanLyKhachSan.LoaiPhongSVC.LoaiPhongSVC.EndLoaiPhong_Edit(System.IAsyncResult result) {
            base.Channel.EndLoaiPhong_Edit(result);
        }
        
        private System.IAsyncResult OnBeginLoaiPhong_Edit(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int LoaiPhongID = ((int)(inValues[0]));
            string LoaiPhongName = ((string)(inValues[1]));
            return ((QuanLyKhachSan.LoaiPhongSVC.LoaiPhongSVC)(this)).BeginLoaiPhong_Edit(LoaiPhongID, LoaiPhongName, callback, asyncState);
        }
        
        private object[] OnEndLoaiPhong_Edit(System.IAsyncResult result) {
            ((QuanLyKhachSan.LoaiPhongSVC.LoaiPhongSVC)(this)).EndLoaiPhong_Edit(result);
            return null;
        }
        
        private void OnLoaiPhong_EditCompleted(object state) {
            if ((this.LoaiPhong_EditCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LoaiPhong_EditCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LoaiPhong_EditAsync(int LoaiPhongID, string LoaiPhongName) {
            this.LoaiPhong_EditAsync(LoaiPhongID, LoaiPhongName, null);
        }
        
        public void LoaiPhong_EditAsync(int LoaiPhongID, string LoaiPhongName, object userState) {
            if ((this.onBeginLoaiPhong_EditDelegate == null)) {
                this.onBeginLoaiPhong_EditDelegate = new BeginOperationDelegate(this.OnBeginLoaiPhong_Edit);
            }
            if ((this.onEndLoaiPhong_EditDelegate == null)) {
                this.onEndLoaiPhong_EditDelegate = new EndOperationDelegate(this.OnEndLoaiPhong_Edit);
            }
            if ((this.onLoaiPhong_EditCompletedDelegate == null)) {
                this.onLoaiPhong_EditCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLoaiPhong_EditCompleted);
            }
            base.InvokeAsync(this.onBeginLoaiPhong_EditDelegate, new object[] {
                        LoaiPhongID,
                        LoaiPhongName}, this.onEndLoaiPhong_EditDelegate, this.onLoaiPhong_EditCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QuanLyKhachSan.LoaiPhongSVC.LoaiPhongSVC.BeginLoaiPhong_Delete(int LoaiPhongID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLoaiPhong_Delete(LoaiPhongID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void QuanLyKhachSan.LoaiPhongSVC.LoaiPhongSVC.EndLoaiPhong_Delete(System.IAsyncResult result) {
            base.Channel.EndLoaiPhong_Delete(result);
        }
        
        private System.IAsyncResult OnBeginLoaiPhong_Delete(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int LoaiPhongID = ((int)(inValues[0]));
            return ((QuanLyKhachSan.LoaiPhongSVC.LoaiPhongSVC)(this)).BeginLoaiPhong_Delete(LoaiPhongID, callback, asyncState);
        }
        
        private object[] OnEndLoaiPhong_Delete(System.IAsyncResult result) {
            ((QuanLyKhachSan.LoaiPhongSVC.LoaiPhongSVC)(this)).EndLoaiPhong_Delete(result);
            return null;
        }
        
        private void OnLoaiPhong_DeleteCompleted(object state) {
            if ((this.LoaiPhong_DeleteCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LoaiPhong_DeleteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LoaiPhong_DeleteAsync(int LoaiPhongID) {
            this.LoaiPhong_DeleteAsync(LoaiPhongID, null);
        }
        
        public void LoaiPhong_DeleteAsync(int LoaiPhongID, object userState) {
            if ((this.onBeginLoaiPhong_DeleteDelegate == null)) {
                this.onBeginLoaiPhong_DeleteDelegate = new BeginOperationDelegate(this.OnBeginLoaiPhong_Delete);
            }
            if ((this.onEndLoaiPhong_DeleteDelegate == null)) {
                this.onEndLoaiPhong_DeleteDelegate = new EndOperationDelegate(this.OnEndLoaiPhong_Delete);
            }
            if ((this.onLoaiPhong_DeleteCompletedDelegate == null)) {
                this.onLoaiPhong_DeleteCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLoaiPhong_DeleteCompleted);
            }
            base.InvokeAsync(this.onBeginLoaiPhong_DeleteDelegate, new object[] {
                        LoaiPhongID}, this.onEndLoaiPhong_DeleteDelegate, this.onLoaiPhong_DeleteCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QuanLyKhachSan.LoaiPhongSVC.LoaiPhongSVC.BeginLoaiPhong_GetItem(int LoaiPhongID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLoaiPhong_GetItem(LoaiPhongID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuanLyKhachSan.LoaiPhongSVC.LoaiPhongInfo QuanLyKhachSan.LoaiPhongSVC.LoaiPhongSVC.EndLoaiPhong_GetItem(System.IAsyncResult result) {
            return base.Channel.EndLoaiPhong_GetItem(result);
        }
        
        private System.IAsyncResult OnBeginLoaiPhong_GetItem(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int LoaiPhongID = ((int)(inValues[0]));
            return ((QuanLyKhachSan.LoaiPhongSVC.LoaiPhongSVC)(this)).BeginLoaiPhong_GetItem(LoaiPhongID, callback, asyncState);
        }
        
        private object[] OnEndLoaiPhong_GetItem(System.IAsyncResult result) {
            QuanLyKhachSan.LoaiPhongSVC.LoaiPhongInfo retVal = ((QuanLyKhachSan.LoaiPhongSVC.LoaiPhongSVC)(this)).EndLoaiPhong_GetItem(result);
            return new object[] {
                    retVal};
        }
        
        private void OnLoaiPhong_GetItemCompleted(object state) {
            if ((this.LoaiPhong_GetItemCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LoaiPhong_GetItemCompleted(this, new LoaiPhong_GetItemCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LoaiPhong_GetItemAsync(int LoaiPhongID) {
            this.LoaiPhong_GetItemAsync(LoaiPhongID, null);
        }
        
        public void LoaiPhong_GetItemAsync(int LoaiPhongID, object userState) {
            if ((this.onBeginLoaiPhong_GetItemDelegate == null)) {
                this.onBeginLoaiPhong_GetItemDelegate = new BeginOperationDelegate(this.OnBeginLoaiPhong_GetItem);
            }
            if ((this.onEndLoaiPhong_GetItemDelegate == null)) {
                this.onEndLoaiPhong_GetItemDelegate = new EndOperationDelegate(this.OnEndLoaiPhong_GetItem);
            }
            if ((this.onLoaiPhong_GetItemCompletedDelegate == null)) {
                this.onLoaiPhong_GetItemCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLoaiPhong_GetItemCompleted);
            }
            base.InvokeAsync(this.onBeginLoaiPhong_GetItemDelegate, new object[] {
                        LoaiPhongID}, this.onEndLoaiPhong_GetItemDelegate, this.onLoaiPhong_GetItemCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QuanLyKhachSan.LoaiPhongSVC.LoaiPhongSVC.BeginLoaiPhong_GetItems(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLoaiPhong_GetItems(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<QuanLyKhachSan.LoaiPhongSVC.LoaiPhongInfo> QuanLyKhachSan.LoaiPhongSVC.LoaiPhongSVC.EndLoaiPhong_GetItems(System.IAsyncResult result) {
            return base.Channel.EndLoaiPhong_GetItems(result);
        }
        
        private System.IAsyncResult OnBeginLoaiPhong_GetItems(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((QuanLyKhachSan.LoaiPhongSVC.LoaiPhongSVC)(this)).BeginLoaiPhong_GetItems(callback, asyncState);
        }
        
        private object[] OnEndLoaiPhong_GetItems(System.IAsyncResult result) {
            System.Collections.Generic.List<QuanLyKhachSan.LoaiPhongSVC.LoaiPhongInfo> retVal = ((QuanLyKhachSan.LoaiPhongSVC.LoaiPhongSVC)(this)).EndLoaiPhong_GetItems(result);
            return new object[] {
                    retVal};
        }
        
        private void OnLoaiPhong_GetItemsCompleted(object state) {
            if ((this.LoaiPhong_GetItemsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LoaiPhong_GetItemsCompleted(this, new LoaiPhong_GetItemsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LoaiPhong_GetItemsAsync() {
            this.LoaiPhong_GetItemsAsync(null);
        }
        
        public void LoaiPhong_GetItemsAsync(object userState) {
            if ((this.onBeginLoaiPhong_GetItemsDelegate == null)) {
                this.onBeginLoaiPhong_GetItemsDelegate = new BeginOperationDelegate(this.OnBeginLoaiPhong_GetItems);
            }
            if ((this.onEndLoaiPhong_GetItemsDelegate == null)) {
                this.onEndLoaiPhong_GetItemsDelegate = new EndOperationDelegate(this.OnEndLoaiPhong_GetItems);
            }
            if ((this.onLoaiPhong_GetItemsCompletedDelegate == null)) {
                this.onLoaiPhong_GetItemsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLoaiPhong_GetItemsCompleted);
            }
            base.InvokeAsync(this.onBeginLoaiPhong_GetItemsDelegate, null, this.onEndLoaiPhong_GetItemsDelegate, this.onLoaiPhong_GetItemsCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override QuanLyKhachSan.LoaiPhongSVC.LoaiPhongSVC CreateChannel() {
            return new LoaiPhongSVCClientChannel(this);
        }
        
        private class LoaiPhongSVCClientChannel : ChannelBase<QuanLyKhachSan.LoaiPhongSVC.LoaiPhongSVC>, QuanLyKhachSan.LoaiPhongSVC.LoaiPhongSVC {
            
            public LoaiPhongSVCClientChannel(System.ServiceModel.ClientBase<QuanLyKhachSan.LoaiPhongSVC.LoaiPhongSVC> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginLoaiPhong_Add(string LoaiPhongName, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = LoaiPhongName;
                System.IAsyncResult _result = base.BeginInvoke("LoaiPhong_Add", _args, callback, asyncState);
                return _result;
            }
            
            public void EndLoaiPhong_Add(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("LoaiPhong_Add", _args, result);
            }
            
            public System.IAsyncResult BeginLoaiPhong_Edit(int LoaiPhongID, string LoaiPhongName, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = LoaiPhongID;
                _args[1] = LoaiPhongName;
                System.IAsyncResult _result = base.BeginInvoke("LoaiPhong_Edit", _args, callback, asyncState);
                return _result;
            }
            
            public void EndLoaiPhong_Edit(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("LoaiPhong_Edit", _args, result);
            }
            
            public System.IAsyncResult BeginLoaiPhong_Delete(int LoaiPhongID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = LoaiPhongID;
                System.IAsyncResult _result = base.BeginInvoke("LoaiPhong_Delete", _args, callback, asyncState);
                return _result;
            }
            
            public void EndLoaiPhong_Delete(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("LoaiPhong_Delete", _args, result);
            }
            
            public System.IAsyncResult BeginLoaiPhong_GetItem(int LoaiPhongID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = LoaiPhongID;
                System.IAsyncResult _result = base.BeginInvoke("LoaiPhong_GetItem", _args, callback, asyncState);
                return _result;
            }
            
            public QuanLyKhachSan.LoaiPhongSVC.LoaiPhongInfo EndLoaiPhong_GetItem(System.IAsyncResult result) {
                object[] _args = new object[0];
                QuanLyKhachSan.LoaiPhongSVC.LoaiPhongInfo _result = ((QuanLyKhachSan.LoaiPhongSVC.LoaiPhongInfo)(base.EndInvoke("LoaiPhong_GetItem", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginLoaiPhong_GetItems(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("LoaiPhong_GetItems", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<QuanLyKhachSan.LoaiPhongSVC.LoaiPhongInfo> EndLoaiPhong_GetItems(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<QuanLyKhachSan.LoaiPhongSVC.LoaiPhongInfo> _result = ((System.Collections.Generic.List<QuanLyKhachSan.LoaiPhongSVC.LoaiPhongInfo>)(base.EndInvoke("LoaiPhong_GetItems", _args, result)));
                return _result;
            }
        }
    }
}
