//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
// 
namespace QuanLyKhachSan.ChiTietPhieuNhapKhoSVC {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChiTietPhieuNhapKhoInfo", Namespace="http://schemas.datacontract.org/2004/07/QuanLyKhachSan")]
    public partial class ChiTietPhieuNhapKhoInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int ChiTietPhieuNhapIDField;
        
        private int DichVuIDField;
        
        private string DichVuNameField;
        
        private decimal DonGiaField;
        
        private int PhieuNhapKhoIDField;
        
        private int SoLuongField;
        
        private decimal TongTienField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ChiTietPhieuNhapID {
            get {
                return this.ChiTietPhieuNhapIDField;
            }
            set {
                if ((this.ChiTietPhieuNhapIDField.Equals(value) != true)) {
                    this.ChiTietPhieuNhapIDField = value;
                    this.RaisePropertyChanged("ChiTietPhieuNhapID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DichVuID {
            get {
                return this.DichVuIDField;
            }
            set {
                if ((this.DichVuIDField.Equals(value) != true)) {
                    this.DichVuIDField = value;
                    this.RaisePropertyChanged("DichVuID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DichVuName {
            get {
                return this.DichVuNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DichVuNameField, value) != true)) {
                    this.DichVuNameField = value;
                    this.RaisePropertyChanged("DichVuName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DonGia {
            get {
                return this.DonGiaField;
            }
            set {
                if ((this.DonGiaField.Equals(value) != true)) {
                    this.DonGiaField = value;
                    this.RaisePropertyChanged("DonGia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PhieuNhapKhoID {
            get {
                return this.PhieuNhapKhoIDField;
            }
            set {
                if ((this.PhieuNhapKhoIDField.Equals(value) != true)) {
                    this.PhieuNhapKhoIDField = value;
                    this.RaisePropertyChanged("PhieuNhapKhoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SoLuong {
            get {
                return this.SoLuongField;
            }
            set {
                if ((this.SoLuongField.Equals(value) != true)) {
                    this.SoLuongField = value;
                    this.RaisePropertyChanged("SoLuong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TongTien {
            get {
                return this.TongTienField;
            }
            set {
                if ((this.TongTienField.Equals(value) != true)) {
                    this.TongTienField = value;
                    this.RaisePropertyChanged("TongTien");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="ChiTietPhieuNhapKhoSVC.ChiTietPhieuNhapKhoSVC")]
    public interface ChiTietPhieuNhapKhoSVC {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:ChiTietPhieuNhapKhoSVC/ChiTietPhieuNhapKho_Add", ReplyAction="urn:ChiTietPhieuNhapKhoSVC/ChiTietPhieuNhapKho_AddResponse")]
        System.IAsyncResult BeginChiTietPhieuNhapKho_Add(int PhieuNhapKhoID, int SoLuong, decimal DonGia, decimal ThanhTien, int DichVuID, System.AsyncCallback callback, object asyncState);
        
        void EndChiTietPhieuNhapKho_Add(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:ChiTietPhieuNhapKhoSVC/ChiTietPhieuNhapKho_Edit", ReplyAction="urn:ChiTietPhieuNhapKhoSVC/ChiTietPhieuNhapKho_EditResponse")]
        System.IAsyncResult BeginChiTietPhieuNhapKho_Edit(int ChiTietPhieuNhapID, int PhieuNhapKhoID, int SoLuong, decimal DonGia, decimal ThanhTien, int DichVuID, System.AsyncCallback callback, object asyncState);
        
        void EndChiTietPhieuNhapKho_Edit(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:ChiTietPhieuNhapKhoSVC/ChiTietPhieuNhapKho_Delete", ReplyAction="urn:ChiTietPhieuNhapKhoSVC/ChiTietPhieuNhapKho_DeleteResponse")]
        System.IAsyncResult BeginChiTietPhieuNhapKho_Delete(int ChiTietPhieuNhapID, System.AsyncCallback callback, object asyncState);
        
        void EndChiTietPhieuNhapKho_Delete(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:ChiTietPhieuNhapKhoSVC/ChiTietPhieuNhapKho_GetItem", ReplyAction="urn:ChiTietPhieuNhapKhoSVC/ChiTietPhieuNhapKho_GetItemResponse")]
        System.IAsyncResult BeginChiTietPhieuNhapKho_GetItem(int ChiTietPhieuNhapID, System.AsyncCallback callback, object asyncState);
        
        QuanLyKhachSan.ChiTietPhieuNhapKhoSVC.ChiTietPhieuNhapKhoInfo EndChiTietPhieuNhapKho_GetItem(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:ChiTietPhieuNhapKhoSVC/ChiTietPhieuNhapKho_GetItems", ReplyAction="urn:ChiTietPhieuNhapKhoSVC/ChiTietPhieuNhapKho_GetItemsResponse")]
        System.IAsyncResult BeginChiTietPhieuNhapKho_GetItems(int PhieuNhapKhoID, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<QuanLyKhachSan.ChiTietPhieuNhapKhoSVC.ChiTietPhieuNhapKhoInfo> EndChiTietPhieuNhapKho_GetItems(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ChiTietPhieuNhapKhoSVCChannel : QuanLyKhachSan.ChiTietPhieuNhapKhoSVC.ChiTietPhieuNhapKhoSVC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChiTietPhieuNhapKho_GetItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ChiTietPhieuNhapKho_GetItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public QuanLyKhachSan.ChiTietPhieuNhapKhoSVC.ChiTietPhieuNhapKhoInfo Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((QuanLyKhachSan.ChiTietPhieuNhapKhoSVC.ChiTietPhieuNhapKhoInfo)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChiTietPhieuNhapKho_GetItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ChiTietPhieuNhapKho_GetItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<QuanLyKhachSan.ChiTietPhieuNhapKhoSVC.ChiTietPhieuNhapKhoInfo> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<QuanLyKhachSan.ChiTietPhieuNhapKhoSVC.ChiTietPhieuNhapKhoInfo>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChiTietPhieuNhapKhoSVCClient : System.ServiceModel.ClientBase<QuanLyKhachSan.ChiTietPhieuNhapKhoSVC.ChiTietPhieuNhapKhoSVC>, QuanLyKhachSan.ChiTietPhieuNhapKhoSVC.ChiTietPhieuNhapKhoSVC {
        
        private BeginOperationDelegate onBeginChiTietPhieuNhapKho_AddDelegate;
        
        private EndOperationDelegate onEndChiTietPhieuNhapKho_AddDelegate;
        
        private System.Threading.SendOrPostCallback onChiTietPhieuNhapKho_AddCompletedDelegate;
        
        private BeginOperationDelegate onBeginChiTietPhieuNhapKho_EditDelegate;
        
        private EndOperationDelegate onEndChiTietPhieuNhapKho_EditDelegate;
        
        private System.Threading.SendOrPostCallback onChiTietPhieuNhapKho_EditCompletedDelegate;
        
        private BeginOperationDelegate onBeginChiTietPhieuNhapKho_DeleteDelegate;
        
        private EndOperationDelegate onEndChiTietPhieuNhapKho_DeleteDelegate;
        
        private System.Threading.SendOrPostCallback onChiTietPhieuNhapKho_DeleteCompletedDelegate;
        
        private BeginOperationDelegate onBeginChiTietPhieuNhapKho_GetItemDelegate;
        
        private EndOperationDelegate onEndChiTietPhieuNhapKho_GetItemDelegate;
        
        private System.Threading.SendOrPostCallback onChiTietPhieuNhapKho_GetItemCompletedDelegate;
        
        private BeginOperationDelegate onBeginChiTietPhieuNhapKho_GetItemsDelegate;
        
        private EndOperationDelegate onEndChiTietPhieuNhapKho_GetItemsDelegate;
        
        private System.Threading.SendOrPostCallback onChiTietPhieuNhapKho_GetItemsCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ChiTietPhieuNhapKhoSVCClient() {
        }
        
        public ChiTietPhieuNhapKhoSVCClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChiTietPhieuNhapKhoSVCClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChiTietPhieuNhapKhoSVCClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChiTietPhieuNhapKhoSVCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> ChiTietPhieuNhapKho_AddCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> ChiTietPhieuNhapKho_EditCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> ChiTietPhieuNhapKho_DeleteCompleted;
        
        public event System.EventHandler<ChiTietPhieuNhapKho_GetItemCompletedEventArgs> ChiTietPhieuNhapKho_GetItemCompleted;
        
        public event System.EventHandler<ChiTietPhieuNhapKho_GetItemsCompletedEventArgs> ChiTietPhieuNhapKho_GetItemsCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QuanLyKhachSan.ChiTietPhieuNhapKhoSVC.ChiTietPhieuNhapKhoSVC.BeginChiTietPhieuNhapKho_Add(int PhieuNhapKhoID, int SoLuong, decimal DonGia, decimal ThanhTien, int DichVuID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginChiTietPhieuNhapKho_Add(PhieuNhapKhoID, SoLuong, DonGia, ThanhTien, DichVuID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void QuanLyKhachSan.ChiTietPhieuNhapKhoSVC.ChiTietPhieuNhapKhoSVC.EndChiTietPhieuNhapKho_Add(System.IAsyncResult result) {
            base.Channel.EndChiTietPhieuNhapKho_Add(result);
        }
        
        private System.IAsyncResult OnBeginChiTietPhieuNhapKho_Add(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int PhieuNhapKhoID = ((int)(inValues[0]));
            int SoLuong = ((int)(inValues[1]));
            decimal DonGia = ((decimal)(inValues[2]));
            decimal ThanhTien = ((decimal)(inValues[3]));
            int DichVuID = ((int)(inValues[4]));
            return ((QuanLyKhachSan.ChiTietPhieuNhapKhoSVC.ChiTietPhieuNhapKhoSVC)(this)).BeginChiTietPhieuNhapKho_Add(PhieuNhapKhoID, SoLuong, DonGia, ThanhTien, DichVuID, callback, asyncState);
        }
        
        private object[] OnEndChiTietPhieuNhapKho_Add(System.IAsyncResult result) {
            ((QuanLyKhachSan.ChiTietPhieuNhapKhoSVC.ChiTietPhieuNhapKhoSVC)(this)).EndChiTietPhieuNhapKho_Add(result);
            return null;
        }
        
        private void OnChiTietPhieuNhapKho_AddCompleted(object state) {
            if ((this.ChiTietPhieuNhapKho_AddCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ChiTietPhieuNhapKho_AddCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ChiTietPhieuNhapKho_AddAsync(int PhieuNhapKhoID, int SoLuong, decimal DonGia, decimal ThanhTien, int DichVuID) {
            this.ChiTietPhieuNhapKho_AddAsync(PhieuNhapKhoID, SoLuong, DonGia, ThanhTien, DichVuID, null);
        }
        
        public void ChiTietPhieuNhapKho_AddAsync(int PhieuNhapKhoID, int SoLuong, decimal DonGia, decimal ThanhTien, int DichVuID, object userState) {
            if ((this.onBeginChiTietPhieuNhapKho_AddDelegate == null)) {
                this.onBeginChiTietPhieuNhapKho_AddDelegate = new BeginOperationDelegate(this.OnBeginChiTietPhieuNhapKho_Add);
            }
            if ((this.onEndChiTietPhieuNhapKho_AddDelegate == null)) {
                this.onEndChiTietPhieuNhapKho_AddDelegate = new EndOperationDelegate(this.OnEndChiTietPhieuNhapKho_Add);
            }
            if ((this.onChiTietPhieuNhapKho_AddCompletedDelegate == null)) {
                this.onChiTietPhieuNhapKho_AddCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnChiTietPhieuNhapKho_AddCompleted);
            }
            base.InvokeAsync(this.onBeginChiTietPhieuNhapKho_AddDelegate, new object[] {
                        PhieuNhapKhoID,
                        SoLuong,
                        DonGia,
                        ThanhTien,
                        DichVuID}, this.onEndChiTietPhieuNhapKho_AddDelegate, this.onChiTietPhieuNhapKho_AddCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QuanLyKhachSan.ChiTietPhieuNhapKhoSVC.ChiTietPhieuNhapKhoSVC.BeginChiTietPhieuNhapKho_Edit(int ChiTietPhieuNhapID, int PhieuNhapKhoID, int SoLuong, decimal DonGia, decimal ThanhTien, int DichVuID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginChiTietPhieuNhapKho_Edit(ChiTietPhieuNhapID, PhieuNhapKhoID, SoLuong, DonGia, ThanhTien, DichVuID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void QuanLyKhachSan.ChiTietPhieuNhapKhoSVC.ChiTietPhieuNhapKhoSVC.EndChiTietPhieuNhapKho_Edit(System.IAsyncResult result) {
            base.Channel.EndChiTietPhieuNhapKho_Edit(result);
        }
        
        private System.IAsyncResult OnBeginChiTietPhieuNhapKho_Edit(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int ChiTietPhieuNhapID = ((int)(inValues[0]));
            int PhieuNhapKhoID = ((int)(inValues[1]));
            int SoLuong = ((int)(inValues[2]));
            decimal DonGia = ((decimal)(inValues[3]));
            decimal ThanhTien = ((decimal)(inValues[4]));
            int DichVuID = ((int)(inValues[5]));
            return ((QuanLyKhachSan.ChiTietPhieuNhapKhoSVC.ChiTietPhieuNhapKhoSVC)(this)).BeginChiTietPhieuNhapKho_Edit(ChiTietPhieuNhapID, PhieuNhapKhoID, SoLuong, DonGia, ThanhTien, DichVuID, callback, asyncState);
        }
        
        private object[] OnEndChiTietPhieuNhapKho_Edit(System.IAsyncResult result) {
            ((QuanLyKhachSan.ChiTietPhieuNhapKhoSVC.ChiTietPhieuNhapKhoSVC)(this)).EndChiTietPhieuNhapKho_Edit(result);
            return null;
        }
        
        private void OnChiTietPhieuNhapKho_EditCompleted(object state) {
            if ((this.ChiTietPhieuNhapKho_EditCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ChiTietPhieuNhapKho_EditCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ChiTietPhieuNhapKho_EditAsync(int ChiTietPhieuNhapID, int PhieuNhapKhoID, int SoLuong, decimal DonGia, decimal ThanhTien, int DichVuID) {
            this.ChiTietPhieuNhapKho_EditAsync(ChiTietPhieuNhapID, PhieuNhapKhoID, SoLuong, DonGia, ThanhTien, DichVuID, null);
        }
        
        public void ChiTietPhieuNhapKho_EditAsync(int ChiTietPhieuNhapID, int PhieuNhapKhoID, int SoLuong, decimal DonGia, decimal ThanhTien, int DichVuID, object userState) {
            if ((this.onBeginChiTietPhieuNhapKho_EditDelegate == null)) {
                this.onBeginChiTietPhieuNhapKho_EditDelegate = new BeginOperationDelegate(this.OnBeginChiTietPhieuNhapKho_Edit);
            }
            if ((this.onEndChiTietPhieuNhapKho_EditDelegate == null)) {
                this.onEndChiTietPhieuNhapKho_EditDelegate = new EndOperationDelegate(this.OnEndChiTietPhieuNhapKho_Edit);
            }
            if ((this.onChiTietPhieuNhapKho_EditCompletedDelegate == null)) {
                this.onChiTietPhieuNhapKho_EditCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnChiTietPhieuNhapKho_EditCompleted);
            }
            base.InvokeAsync(this.onBeginChiTietPhieuNhapKho_EditDelegate, new object[] {
                        ChiTietPhieuNhapID,
                        PhieuNhapKhoID,
                        SoLuong,
                        DonGia,
                        ThanhTien,
                        DichVuID}, this.onEndChiTietPhieuNhapKho_EditDelegate, this.onChiTietPhieuNhapKho_EditCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QuanLyKhachSan.ChiTietPhieuNhapKhoSVC.ChiTietPhieuNhapKhoSVC.BeginChiTietPhieuNhapKho_Delete(int ChiTietPhieuNhapID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginChiTietPhieuNhapKho_Delete(ChiTietPhieuNhapID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void QuanLyKhachSan.ChiTietPhieuNhapKhoSVC.ChiTietPhieuNhapKhoSVC.EndChiTietPhieuNhapKho_Delete(System.IAsyncResult result) {
            base.Channel.EndChiTietPhieuNhapKho_Delete(result);
        }
        
        private System.IAsyncResult OnBeginChiTietPhieuNhapKho_Delete(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int ChiTietPhieuNhapID = ((int)(inValues[0]));
            return ((QuanLyKhachSan.ChiTietPhieuNhapKhoSVC.ChiTietPhieuNhapKhoSVC)(this)).BeginChiTietPhieuNhapKho_Delete(ChiTietPhieuNhapID, callback, asyncState);
        }
        
        private object[] OnEndChiTietPhieuNhapKho_Delete(System.IAsyncResult result) {
            ((QuanLyKhachSan.ChiTietPhieuNhapKhoSVC.ChiTietPhieuNhapKhoSVC)(this)).EndChiTietPhieuNhapKho_Delete(result);
            return null;
        }
        
        private void OnChiTietPhieuNhapKho_DeleteCompleted(object state) {
            if ((this.ChiTietPhieuNhapKho_DeleteCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ChiTietPhieuNhapKho_DeleteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ChiTietPhieuNhapKho_DeleteAsync(int ChiTietPhieuNhapID) {
            this.ChiTietPhieuNhapKho_DeleteAsync(ChiTietPhieuNhapID, null);
        }
        
        public void ChiTietPhieuNhapKho_DeleteAsync(int ChiTietPhieuNhapID, object userState) {
            if ((this.onBeginChiTietPhieuNhapKho_DeleteDelegate == null)) {
                this.onBeginChiTietPhieuNhapKho_DeleteDelegate = new BeginOperationDelegate(this.OnBeginChiTietPhieuNhapKho_Delete);
            }
            if ((this.onEndChiTietPhieuNhapKho_DeleteDelegate == null)) {
                this.onEndChiTietPhieuNhapKho_DeleteDelegate = new EndOperationDelegate(this.OnEndChiTietPhieuNhapKho_Delete);
            }
            if ((this.onChiTietPhieuNhapKho_DeleteCompletedDelegate == null)) {
                this.onChiTietPhieuNhapKho_DeleteCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnChiTietPhieuNhapKho_DeleteCompleted);
            }
            base.InvokeAsync(this.onBeginChiTietPhieuNhapKho_DeleteDelegate, new object[] {
                        ChiTietPhieuNhapID}, this.onEndChiTietPhieuNhapKho_DeleteDelegate, this.onChiTietPhieuNhapKho_DeleteCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QuanLyKhachSan.ChiTietPhieuNhapKhoSVC.ChiTietPhieuNhapKhoSVC.BeginChiTietPhieuNhapKho_GetItem(int ChiTietPhieuNhapID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginChiTietPhieuNhapKho_GetItem(ChiTietPhieuNhapID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuanLyKhachSan.ChiTietPhieuNhapKhoSVC.ChiTietPhieuNhapKhoInfo QuanLyKhachSan.ChiTietPhieuNhapKhoSVC.ChiTietPhieuNhapKhoSVC.EndChiTietPhieuNhapKho_GetItem(System.IAsyncResult result) {
            return base.Channel.EndChiTietPhieuNhapKho_GetItem(result);
        }
        
        private System.IAsyncResult OnBeginChiTietPhieuNhapKho_GetItem(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int ChiTietPhieuNhapID = ((int)(inValues[0]));
            return ((QuanLyKhachSan.ChiTietPhieuNhapKhoSVC.ChiTietPhieuNhapKhoSVC)(this)).BeginChiTietPhieuNhapKho_GetItem(ChiTietPhieuNhapID, callback, asyncState);
        }
        
        private object[] OnEndChiTietPhieuNhapKho_GetItem(System.IAsyncResult result) {
            QuanLyKhachSan.ChiTietPhieuNhapKhoSVC.ChiTietPhieuNhapKhoInfo retVal = ((QuanLyKhachSan.ChiTietPhieuNhapKhoSVC.ChiTietPhieuNhapKhoSVC)(this)).EndChiTietPhieuNhapKho_GetItem(result);
            return new object[] {
                    retVal};
        }
        
        private void OnChiTietPhieuNhapKho_GetItemCompleted(object state) {
            if ((this.ChiTietPhieuNhapKho_GetItemCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ChiTietPhieuNhapKho_GetItemCompleted(this, new ChiTietPhieuNhapKho_GetItemCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ChiTietPhieuNhapKho_GetItemAsync(int ChiTietPhieuNhapID) {
            this.ChiTietPhieuNhapKho_GetItemAsync(ChiTietPhieuNhapID, null);
        }
        
        public void ChiTietPhieuNhapKho_GetItemAsync(int ChiTietPhieuNhapID, object userState) {
            if ((this.onBeginChiTietPhieuNhapKho_GetItemDelegate == null)) {
                this.onBeginChiTietPhieuNhapKho_GetItemDelegate = new BeginOperationDelegate(this.OnBeginChiTietPhieuNhapKho_GetItem);
            }
            if ((this.onEndChiTietPhieuNhapKho_GetItemDelegate == null)) {
                this.onEndChiTietPhieuNhapKho_GetItemDelegate = new EndOperationDelegate(this.OnEndChiTietPhieuNhapKho_GetItem);
            }
            if ((this.onChiTietPhieuNhapKho_GetItemCompletedDelegate == null)) {
                this.onChiTietPhieuNhapKho_GetItemCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnChiTietPhieuNhapKho_GetItemCompleted);
            }
            base.InvokeAsync(this.onBeginChiTietPhieuNhapKho_GetItemDelegate, new object[] {
                        ChiTietPhieuNhapID}, this.onEndChiTietPhieuNhapKho_GetItemDelegate, this.onChiTietPhieuNhapKho_GetItemCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QuanLyKhachSan.ChiTietPhieuNhapKhoSVC.ChiTietPhieuNhapKhoSVC.BeginChiTietPhieuNhapKho_GetItems(int PhieuNhapKhoID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginChiTietPhieuNhapKho_GetItems(PhieuNhapKhoID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<QuanLyKhachSan.ChiTietPhieuNhapKhoSVC.ChiTietPhieuNhapKhoInfo> QuanLyKhachSan.ChiTietPhieuNhapKhoSVC.ChiTietPhieuNhapKhoSVC.EndChiTietPhieuNhapKho_GetItems(System.IAsyncResult result) {
            return base.Channel.EndChiTietPhieuNhapKho_GetItems(result);
        }
        
        private System.IAsyncResult OnBeginChiTietPhieuNhapKho_GetItems(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int PhieuNhapKhoID = ((int)(inValues[0]));
            return ((QuanLyKhachSan.ChiTietPhieuNhapKhoSVC.ChiTietPhieuNhapKhoSVC)(this)).BeginChiTietPhieuNhapKho_GetItems(PhieuNhapKhoID, callback, asyncState);
        }
        
        private object[] OnEndChiTietPhieuNhapKho_GetItems(System.IAsyncResult result) {
            System.Collections.Generic.List<QuanLyKhachSan.ChiTietPhieuNhapKhoSVC.ChiTietPhieuNhapKhoInfo> retVal = ((QuanLyKhachSan.ChiTietPhieuNhapKhoSVC.ChiTietPhieuNhapKhoSVC)(this)).EndChiTietPhieuNhapKho_GetItems(result);
            return new object[] {
                    retVal};
        }
        
        private void OnChiTietPhieuNhapKho_GetItemsCompleted(object state) {
            if ((this.ChiTietPhieuNhapKho_GetItemsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ChiTietPhieuNhapKho_GetItemsCompleted(this, new ChiTietPhieuNhapKho_GetItemsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ChiTietPhieuNhapKho_GetItemsAsync(int PhieuNhapKhoID) {
            this.ChiTietPhieuNhapKho_GetItemsAsync(PhieuNhapKhoID, null);
        }
        
        public void ChiTietPhieuNhapKho_GetItemsAsync(int PhieuNhapKhoID, object userState) {
            if ((this.onBeginChiTietPhieuNhapKho_GetItemsDelegate == null)) {
                this.onBeginChiTietPhieuNhapKho_GetItemsDelegate = new BeginOperationDelegate(this.OnBeginChiTietPhieuNhapKho_GetItems);
            }
            if ((this.onEndChiTietPhieuNhapKho_GetItemsDelegate == null)) {
                this.onEndChiTietPhieuNhapKho_GetItemsDelegate = new EndOperationDelegate(this.OnEndChiTietPhieuNhapKho_GetItems);
            }
            if ((this.onChiTietPhieuNhapKho_GetItemsCompletedDelegate == null)) {
                this.onChiTietPhieuNhapKho_GetItemsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnChiTietPhieuNhapKho_GetItemsCompleted);
            }
            base.InvokeAsync(this.onBeginChiTietPhieuNhapKho_GetItemsDelegate, new object[] {
                        PhieuNhapKhoID}, this.onEndChiTietPhieuNhapKho_GetItemsDelegate, this.onChiTietPhieuNhapKho_GetItemsCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override QuanLyKhachSan.ChiTietPhieuNhapKhoSVC.ChiTietPhieuNhapKhoSVC CreateChannel() {
            return new ChiTietPhieuNhapKhoSVCClientChannel(this);
        }
        
        private class ChiTietPhieuNhapKhoSVCClientChannel : ChannelBase<QuanLyKhachSan.ChiTietPhieuNhapKhoSVC.ChiTietPhieuNhapKhoSVC>, QuanLyKhachSan.ChiTietPhieuNhapKhoSVC.ChiTietPhieuNhapKhoSVC {
            
            public ChiTietPhieuNhapKhoSVCClientChannel(System.ServiceModel.ClientBase<QuanLyKhachSan.ChiTietPhieuNhapKhoSVC.ChiTietPhieuNhapKhoSVC> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginChiTietPhieuNhapKho_Add(int PhieuNhapKhoID, int SoLuong, decimal DonGia, decimal ThanhTien, int DichVuID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[5];
                _args[0] = PhieuNhapKhoID;
                _args[1] = SoLuong;
                _args[2] = DonGia;
                _args[3] = ThanhTien;
                _args[4] = DichVuID;
                System.IAsyncResult _result = base.BeginInvoke("ChiTietPhieuNhapKho_Add", _args, callback, asyncState);
                return _result;
            }
            
            public void EndChiTietPhieuNhapKho_Add(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("ChiTietPhieuNhapKho_Add", _args, result);
            }
            
            public System.IAsyncResult BeginChiTietPhieuNhapKho_Edit(int ChiTietPhieuNhapID, int PhieuNhapKhoID, int SoLuong, decimal DonGia, decimal ThanhTien, int DichVuID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[6];
                _args[0] = ChiTietPhieuNhapID;
                _args[1] = PhieuNhapKhoID;
                _args[2] = SoLuong;
                _args[3] = DonGia;
                _args[4] = ThanhTien;
                _args[5] = DichVuID;
                System.IAsyncResult _result = base.BeginInvoke("ChiTietPhieuNhapKho_Edit", _args, callback, asyncState);
                return _result;
            }
            
            public void EndChiTietPhieuNhapKho_Edit(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("ChiTietPhieuNhapKho_Edit", _args, result);
            }
            
            public System.IAsyncResult BeginChiTietPhieuNhapKho_Delete(int ChiTietPhieuNhapID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = ChiTietPhieuNhapID;
                System.IAsyncResult _result = base.BeginInvoke("ChiTietPhieuNhapKho_Delete", _args, callback, asyncState);
                return _result;
            }
            
            public void EndChiTietPhieuNhapKho_Delete(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("ChiTietPhieuNhapKho_Delete", _args, result);
            }
            
            public System.IAsyncResult BeginChiTietPhieuNhapKho_GetItem(int ChiTietPhieuNhapID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = ChiTietPhieuNhapID;
                System.IAsyncResult _result = base.BeginInvoke("ChiTietPhieuNhapKho_GetItem", _args, callback, asyncState);
                return _result;
            }
            
            public QuanLyKhachSan.ChiTietPhieuNhapKhoSVC.ChiTietPhieuNhapKhoInfo EndChiTietPhieuNhapKho_GetItem(System.IAsyncResult result) {
                object[] _args = new object[0];
                QuanLyKhachSan.ChiTietPhieuNhapKhoSVC.ChiTietPhieuNhapKhoInfo _result = ((QuanLyKhachSan.ChiTietPhieuNhapKhoSVC.ChiTietPhieuNhapKhoInfo)(base.EndInvoke("ChiTietPhieuNhapKho_GetItem", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginChiTietPhieuNhapKho_GetItems(int PhieuNhapKhoID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = PhieuNhapKhoID;
                System.IAsyncResult _result = base.BeginInvoke("ChiTietPhieuNhapKho_GetItems", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<QuanLyKhachSan.ChiTietPhieuNhapKhoSVC.ChiTietPhieuNhapKhoInfo> EndChiTietPhieuNhapKho_GetItems(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<QuanLyKhachSan.ChiTietPhieuNhapKhoSVC.ChiTietPhieuNhapKhoInfo> _result = ((System.Collections.Generic.List<QuanLyKhachSan.ChiTietPhieuNhapKhoSVC.ChiTietPhieuNhapKhoInfo>)(base.EndInvoke("ChiTietPhieuNhapKho_GetItems", _args, result)));
                return _result;
            }
        }
    }
}
