//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
// 
namespace QuanLyKhachSan.HoaDonDichVuSVC {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HoaDonDichVuInfo", Namespace="http://schemas.datacontract.org/2004/07/QuanLyKhachSan")]
    public partial class HoaDonDichVuInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string CreatedByUserField;
        
        private string CreatedDateField;
        
        private int DichVuIDField;
        
        private string DichVuNameField;
        
        private decimal DonGiaField;
        
        private string HoTenField;
        
        private int HoaDonIDField;
        
        private int HoaDon_DichVuIDField;
        
        private int KhachHangIDField;
        
        private string ModifiedByUserField;
        
        private string ModifiedDateField;
        
        private int NamField;
        
        private int NgaySoField;
        
        private string NgaySuDungField;
        
        private int PhongIDField;
        
        private string PhongNameField;
        
        private int SoLuongField;
        
        private int ThangField;
        
        private decimal TongTienField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedByUser {
            get {
                return this.CreatedByUserField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByUserField, value) != true)) {
                    this.CreatedByUserField = value;
                    this.RaisePropertyChanged("CreatedByUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedDateField, value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DichVuID {
            get {
                return this.DichVuIDField;
            }
            set {
                if ((this.DichVuIDField.Equals(value) != true)) {
                    this.DichVuIDField = value;
                    this.RaisePropertyChanged("DichVuID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DichVuName {
            get {
                return this.DichVuNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DichVuNameField, value) != true)) {
                    this.DichVuNameField = value;
                    this.RaisePropertyChanged("DichVuName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DonGia {
            get {
                return this.DonGiaField;
            }
            set {
                if ((this.DonGiaField.Equals(value) != true)) {
                    this.DonGiaField = value;
                    this.RaisePropertyChanged("DonGia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HoTen {
            get {
                return this.HoTenField;
            }
            set {
                if ((object.ReferenceEquals(this.HoTenField, value) != true)) {
                    this.HoTenField = value;
                    this.RaisePropertyChanged("HoTen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HoaDonID {
            get {
                return this.HoaDonIDField;
            }
            set {
                if ((this.HoaDonIDField.Equals(value) != true)) {
                    this.HoaDonIDField = value;
                    this.RaisePropertyChanged("HoaDonID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HoaDon_DichVuID {
            get {
                return this.HoaDon_DichVuIDField;
            }
            set {
                if ((this.HoaDon_DichVuIDField.Equals(value) != true)) {
                    this.HoaDon_DichVuIDField = value;
                    this.RaisePropertyChanged("HoaDon_DichVuID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KhachHangID {
            get {
                return this.KhachHangIDField;
            }
            set {
                if ((this.KhachHangIDField.Equals(value) != true)) {
                    this.KhachHangIDField = value;
                    this.RaisePropertyChanged("KhachHangID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedByUser {
            get {
                return this.ModifiedByUserField;
            }
            set {
                if ((object.ReferenceEquals(this.ModifiedByUserField, value) != true)) {
                    this.ModifiedByUserField = value;
                    this.RaisePropertyChanged("ModifiedByUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ModifiedDateField, value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Nam {
            get {
                return this.NamField;
            }
            set {
                if ((this.NamField.Equals(value) != true)) {
                    this.NamField = value;
                    this.RaisePropertyChanged("Nam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NgaySo {
            get {
                return this.NgaySoField;
            }
            set {
                if ((this.NgaySoField.Equals(value) != true)) {
                    this.NgaySoField = value;
                    this.RaisePropertyChanged("NgaySo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NgaySuDung {
            get {
                return this.NgaySuDungField;
            }
            set {
                if ((object.ReferenceEquals(this.NgaySuDungField, value) != true)) {
                    this.NgaySuDungField = value;
                    this.RaisePropertyChanged("NgaySuDung");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PhongID {
            get {
                return this.PhongIDField;
            }
            set {
                if ((this.PhongIDField.Equals(value) != true)) {
                    this.PhongIDField = value;
                    this.RaisePropertyChanged("PhongID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhongName {
            get {
                return this.PhongNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PhongNameField, value) != true)) {
                    this.PhongNameField = value;
                    this.RaisePropertyChanged("PhongName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SoLuong {
            get {
                return this.SoLuongField;
            }
            set {
                if ((this.SoLuongField.Equals(value) != true)) {
                    this.SoLuongField = value;
                    this.RaisePropertyChanged("SoLuong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Thang {
            get {
                return this.ThangField;
            }
            set {
                if ((this.ThangField.Equals(value) != true)) {
                    this.ThangField = value;
                    this.RaisePropertyChanged("Thang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TongTien {
            get {
                return this.TongTienField;
            }
            set {
                if ((this.TongTienField.Equals(value) != true)) {
                    this.TongTienField = value;
                    this.RaisePropertyChanged("TongTien");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HoaDonNgayVaoRaInfo", Namespace="http://schemas.datacontract.org/2004/07/QuanLyKhachSan")]
    public partial class HoaDonNgayVaoRaInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int GioRaField;
        
        private int GioVaoField;
        
        private int HoaDonIDField;
        
        private int NamRaField;
        
        private int NamVaoField;
        
        private string NgayRaField;
        
        private int NgayRa_SoField;
        
        private string NgayVaoField;
        
        private int NgayVao_SoField;
        
        private int PhutRaField;
        
        private int PhutVaoField;
        
        private int ThangRaField;
        
        private int ThangVaoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GioRa {
            get {
                return this.GioRaField;
            }
            set {
                if ((this.GioRaField.Equals(value) != true)) {
                    this.GioRaField = value;
                    this.RaisePropertyChanged("GioRa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GioVao {
            get {
                return this.GioVaoField;
            }
            set {
                if ((this.GioVaoField.Equals(value) != true)) {
                    this.GioVaoField = value;
                    this.RaisePropertyChanged("GioVao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HoaDonID {
            get {
                return this.HoaDonIDField;
            }
            set {
                if ((this.HoaDonIDField.Equals(value) != true)) {
                    this.HoaDonIDField = value;
                    this.RaisePropertyChanged("HoaDonID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NamRa {
            get {
                return this.NamRaField;
            }
            set {
                if ((this.NamRaField.Equals(value) != true)) {
                    this.NamRaField = value;
                    this.RaisePropertyChanged("NamRa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NamVao {
            get {
                return this.NamVaoField;
            }
            set {
                if ((this.NamVaoField.Equals(value) != true)) {
                    this.NamVaoField = value;
                    this.RaisePropertyChanged("NamVao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NgayRa {
            get {
                return this.NgayRaField;
            }
            set {
                if ((object.ReferenceEquals(this.NgayRaField, value) != true)) {
                    this.NgayRaField = value;
                    this.RaisePropertyChanged("NgayRa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NgayRa_So {
            get {
                return this.NgayRa_SoField;
            }
            set {
                if ((this.NgayRa_SoField.Equals(value) != true)) {
                    this.NgayRa_SoField = value;
                    this.RaisePropertyChanged("NgayRa_So");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NgayVao {
            get {
                return this.NgayVaoField;
            }
            set {
                if ((object.ReferenceEquals(this.NgayVaoField, value) != true)) {
                    this.NgayVaoField = value;
                    this.RaisePropertyChanged("NgayVao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NgayVao_So {
            get {
                return this.NgayVao_SoField;
            }
            set {
                if ((this.NgayVao_SoField.Equals(value) != true)) {
                    this.NgayVao_SoField = value;
                    this.RaisePropertyChanged("NgayVao_So");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PhutRa {
            get {
                return this.PhutRaField;
            }
            set {
                if ((this.PhutRaField.Equals(value) != true)) {
                    this.PhutRaField = value;
                    this.RaisePropertyChanged("PhutRa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PhutVao {
            get {
                return this.PhutVaoField;
            }
            set {
                if ((this.PhutVaoField.Equals(value) != true)) {
                    this.PhutVaoField = value;
                    this.RaisePropertyChanged("PhutVao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ThangRa {
            get {
                return this.ThangRaField;
            }
            set {
                if ((this.ThangRaField.Equals(value) != true)) {
                    this.ThangRaField = value;
                    this.RaisePropertyChanged("ThangRa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ThangVao {
            get {
                return this.ThangVaoField;
            }
            set {
                if ((this.ThangVaoField.Equals(value) != true)) {
                    this.ThangVaoField = value;
                    this.RaisePropertyChanged("ThangVao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="HoaDonDichVuSVC.HoaDonDichVuSVC")]
    public interface HoaDonDichVuSVC {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:HoaDonDichVuSVC/HoaDonDichVu_Add", ReplyAction="urn:HoaDonDichVuSVC/HoaDonDichVu_AddResponse")]
        System.IAsyncResult BeginHoaDonDichVu_Add(int HoaDonID, int PhongID, int DichVuID, int KhachHangID, string NgaySuDung, int Thang, int Nam, int NgaySo, int SoLuong, decimal DonGia, decimal TongTien, string CreatedByUser, string CreatedDate, System.AsyncCallback callback, object asyncState);
        
        void EndHoaDonDichVu_Add(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:HoaDonDichVuSVC/HoaDonDichVu_Edit", ReplyAction="urn:HoaDonDichVuSVC/HoaDonDichVu_EditResponse")]
        System.IAsyncResult BeginHoaDonDichVu_Edit(
                    int HoaDon_DichVuID, 
                    int HoaDonID, 
                    int PhongID, 
                    int DichVuID, 
                    int KhachHangID, 
                    string NgaySuDung, 
                    int Thang, 
                    int Nam, 
                    int NgaySo, 
                    int SoLuong, 
                    decimal DonGia, 
                    decimal TongTien, 
                    string ModifiedByUser, 
                    string ModifiedDate, 
                    System.AsyncCallback callback, 
                    object asyncState);
        
        void EndHoaDonDichVu_Edit(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:HoaDonDichVuSVC/HoaDonDichVu_Delete", ReplyAction="urn:HoaDonDichVuSVC/HoaDonDichVu_DeleteResponse")]
        System.IAsyncResult BeginHoaDonDichVu_Delete(int HoaDon_DichVuID, System.AsyncCallback callback, object asyncState);
        
        void EndHoaDonDichVu_Delete(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:HoaDonDichVuSVC/HoaDonDichVu_GetItem", ReplyAction="urn:HoaDonDichVuSVC/HoaDonDichVu_GetItemResponse")]
        System.IAsyncResult BeginHoaDonDichVu_GetItem(int HoaDon_DichVuID, System.AsyncCallback callback, object asyncState);
        
        QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuInfo EndHoaDonDichVu_GetItem(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:HoaDonDichVuSVC/HoaDonDichVu_GetItems", ReplyAction="urn:HoaDonDichVuSVC/HoaDonDichVu_GetItemsResponse")]
        System.IAsyncResult BeginHoaDonDichVu_GetItems(int HoaDon_DichVuID, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuInfo> EndHoaDonDichVu_GetItems(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:HoaDonDichVuSVC/HoaDonDichVu_GetItemsByID", ReplyAction="urn:HoaDonDichVuSVC/HoaDonDichVu_GetItemsByIDResponse")]
        System.IAsyncResult BeginHoaDonDichVu_GetItemsByID(int HoaDonID, int PhongID, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuInfo> EndHoaDonDichVu_GetItemsByID(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:HoaDonDichVuSVC/HoaDonDichVu_GetItem_NgayVao", ReplyAction="urn:HoaDonDichVuSVC/HoaDonDichVu_GetItem_NgayVaoResponse")]
        System.IAsyncResult BeginHoaDonDichVu_GetItem_NgayVao(int HoaDonID, System.AsyncCallback callback, object asyncState);
        
        QuanLyKhachSan.HoaDonDichVuSVC.HoaDonNgayVaoRaInfo EndHoaDonDichVu_GetItem_NgayVao(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:HoaDonDichVuSVC/HoaDonNgayRa_Add", ReplyAction="urn:HoaDonDichVuSVC/HoaDonNgayRa_AddResponse")]
        System.IAsyncResult BeginHoaDonNgayRa_Add(int HoaDonID, string NgayRa, int GioRa, int PhutRa, int NgayRa_So, int ThangRa, int NamRa, System.AsyncCallback callback, object asyncState);
        
        void EndHoaDonNgayRa_Add(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:HoaDonDichVuSVC/HoaDonDichVu_ChuyenPhong", ReplyAction="urn:HoaDonDichVuSVC/HoaDonDichVu_ChuyenPhongResponse")]
        System.IAsyncResult BeginHoaDonDichVu_ChuyenPhong(int HoaDonID, int PhongID, System.AsyncCallback callback, object asyncState);
        
        void EndHoaDonDichVu_ChuyenPhong(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HoaDonDichVuSVCChannel : QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuSVC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HoaDonDichVu_GetItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public HoaDonDichVu_GetItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuInfo Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuInfo)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HoaDonDichVu_GetItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public HoaDonDichVu_GetItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuInfo> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuInfo>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HoaDonDichVu_GetItemsByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public HoaDonDichVu_GetItemsByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuInfo> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuInfo>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HoaDonDichVu_GetItem_NgayVaoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public HoaDonDichVu_GetItem_NgayVaoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public QuanLyKhachSan.HoaDonDichVuSVC.HoaDonNgayVaoRaInfo Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((QuanLyKhachSan.HoaDonDichVuSVC.HoaDonNgayVaoRaInfo)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HoaDonDichVuSVCClient : System.ServiceModel.ClientBase<QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuSVC>, QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuSVC {
        
        private BeginOperationDelegate onBeginHoaDonDichVu_AddDelegate;
        
        private EndOperationDelegate onEndHoaDonDichVu_AddDelegate;
        
        private System.Threading.SendOrPostCallback onHoaDonDichVu_AddCompletedDelegate;
        
        private BeginOperationDelegate onBeginHoaDonDichVu_EditDelegate;
        
        private EndOperationDelegate onEndHoaDonDichVu_EditDelegate;
        
        private System.Threading.SendOrPostCallback onHoaDonDichVu_EditCompletedDelegate;
        
        private BeginOperationDelegate onBeginHoaDonDichVu_DeleteDelegate;
        
        private EndOperationDelegate onEndHoaDonDichVu_DeleteDelegate;
        
        private System.Threading.SendOrPostCallback onHoaDonDichVu_DeleteCompletedDelegate;
        
        private BeginOperationDelegate onBeginHoaDonDichVu_GetItemDelegate;
        
        private EndOperationDelegate onEndHoaDonDichVu_GetItemDelegate;
        
        private System.Threading.SendOrPostCallback onHoaDonDichVu_GetItemCompletedDelegate;
        
        private BeginOperationDelegate onBeginHoaDonDichVu_GetItemsDelegate;
        
        private EndOperationDelegate onEndHoaDonDichVu_GetItemsDelegate;
        
        private System.Threading.SendOrPostCallback onHoaDonDichVu_GetItemsCompletedDelegate;
        
        private BeginOperationDelegate onBeginHoaDonDichVu_GetItemsByIDDelegate;
        
        private EndOperationDelegate onEndHoaDonDichVu_GetItemsByIDDelegate;
        
        private System.Threading.SendOrPostCallback onHoaDonDichVu_GetItemsByIDCompletedDelegate;
        
        private BeginOperationDelegate onBeginHoaDonDichVu_GetItem_NgayVaoDelegate;
        
        private EndOperationDelegate onEndHoaDonDichVu_GetItem_NgayVaoDelegate;
        
        private System.Threading.SendOrPostCallback onHoaDonDichVu_GetItem_NgayVaoCompletedDelegate;
        
        private BeginOperationDelegate onBeginHoaDonNgayRa_AddDelegate;
        
        private EndOperationDelegate onEndHoaDonNgayRa_AddDelegate;
        
        private System.Threading.SendOrPostCallback onHoaDonNgayRa_AddCompletedDelegate;
        
        private BeginOperationDelegate onBeginHoaDonDichVu_ChuyenPhongDelegate;
        
        private EndOperationDelegate onEndHoaDonDichVu_ChuyenPhongDelegate;
        
        private System.Threading.SendOrPostCallback onHoaDonDichVu_ChuyenPhongCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public HoaDonDichVuSVCClient() {
        }
        
        public HoaDonDichVuSVCClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HoaDonDichVuSVCClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HoaDonDichVuSVCClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HoaDonDichVuSVCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> HoaDonDichVu_AddCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> HoaDonDichVu_EditCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> HoaDonDichVu_DeleteCompleted;
        
        public event System.EventHandler<HoaDonDichVu_GetItemCompletedEventArgs> HoaDonDichVu_GetItemCompleted;
        
        public event System.EventHandler<HoaDonDichVu_GetItemsCompletedEventArgs> HoaDonDichVu_GetItemsCompleted;
        
        public event System.EventHandler<HoaDonDichVu_GetItemsByIDCompletedEventArgs> HoaDonDichVu_GetItemsByIDCompleted;
        
        public event System.EventHandler<HoaDonDichVu_GetItem_NgayVaoCompletedEventArgs> HoaDonDichVu_GetItem_NgayVaoCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> HoaDonNgayRa_AddCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> HoaDonDichVu_ChuyenPhongCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuSVC.BeginHoaDonDichVu_Add(int HoaDonID, int PhongID, int DichVuID, int KhachHangID, string NgaySuDung, int Thang, int Nam, int NgaySo, int SoLuong, decimal DonGia, decimal TongTien, string CreatedByUser, string CreatedDate, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginHoaDonDichVu_Add(HoaDonID, PhongID, DichVuID, KhachHangID, NgaySuDung, Thang, Nam, NgaySo, SoLuong, DonGia, TongTien, CreatedByUser, CreatedDate, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuSVC.EndHoaDonDichVu_Add(System.IAsyncResult result) {
            base.Channel.EndHoaDonDichVu_Add(result);
        }
        
        private System.IAsyncResult OnBeginHoaDonDichVu_Add(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int HoaDonID = ((int)(inValues[0]));
            int PhongID = ((int)(inValues[1]));
            int DichVuID = ((int)(inValues[2]));
            int KhachHangID = ((int)(inValues[3]));
            string NgaySuDung = ((string)(inValues[4]));
            int Thang = ((int)(inValues[5]));
            int Nam = ((int)(inValues[6]));
            int NgaySo = ((int)(inValues[7]));
            int SoLuong = ((int)(inValues[8]));
            decimal DonGia = ((decimal)(inValues[9]));
            decimal TongTien = ((decimal)(inValues[10]));
            string CreatedByUser = ((string)(inValues[11]));
            string CreatedDate = ((string)(inValues[12]));
            return ((QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuSVC)(this)).BeginHoaDonDichVu_Add(HoaDonID, PhongID, DichVuID, KhachHangID, NgaySuDung, Thang, Nam, NgaySo, SoLuong, DonGia, TongTien, CreatedByUser, CreatedDate, callback, asyncState);
        }
        
        private object[] OnEndHoaDonDichVu_Add(System.IAsyncResult result) {
            ((QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuSVC)(this)).EndHoaDonDichVu_Add(result);
            return null;
        }
        
        private void OnHoaDonDichVu_AddCompleted(object state) {
            if ((this.HoaDonDichVu_AddCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.HoaDonDichVu_AddCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void HoaDonDichVu_AddAsync(int HoaDonID, int PhongID, int DichVuID, int KhachHangID, string NgaySuDung, int Thang, int Nam, int NgaySo, int SoLuong, decimal DonGia, decimal TongTien, string CreatedByUser, string CreatedDate) {
            this.HoaDonDichVu_AddAsync(HoaDonID, PhongID, DichVuID, KhachHangID, NgaySuDung, Thang, Nam, NgaySo, SoLuong, DonGia, TongTien, CreatedByUser, CreatedDate, null);
        }
        
        public void HoaDonDichVu_AddAsync(int HoaDonID, int PhongID, int DichVuID, int KhachHangID, string NgaySuDung, int Thang, int Nam, int NgaySo, int SoLuong, decimal DonGia, decimal TongTien, string CreatedByUser, string CreatedDate, object userState) {
            if ((this.onBeginHoaDonDichVu_AddDelegate == null)) {
                this.onBeginHoaDonDichVu_AddDelegate = new BeginOperationDelegate(this.OnBeginHoaDonDichVu_Add);
            }
            if ((this.onEndHoaDonDichVu_AddDelegate == null)) {
                this.onEndHoaDonDichVu_AddDelegate = new EndOperationDelegate(this.OnEndHoaDonDichVu_Add);
            }
            if ((this.onHoaDonDichVu_AddCompletedDelegate == null)) {
                this.onHoaDonDichVu_AddCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHoaDonDichVu_AddCompleted);
            }
            base.InvokeAsync(this.onBeginHoaDonDichVu_AddDelegate, new object[] {
                        HoaDonID,
                        PhongID,
                        DichVuID,
                        KhachHangID,
                        NgaySuDung,
                        Thang,
                        Nam,
                        NgaySo,
                        SoLuong,
                        DonGia,
                        TongTien,
                        CreatedByUser,
                        CreatedDate}, this.onEndHoaDonDichVu_AddDelegate, this.onHoaDonDichVu_AddCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuSVC.BeginHoaDonDichVu_Edit(
                    int HoaDon_DichVuID, 
                    int HoaDonID, 
                    int PhongID, 
                    int DichVuID, 
                    int KhachHangID, 
                    string NgaySuDung, 
                    int Thang, 
                    int Nam, 
                    int NgaySo, 
                    int SoLuong, 
                    decimal DonGia, 
                    decimal TongTien, 
                    string ModifiedByUser, 
                    string ModifiedDate, 
                    System.AsyncCallback callback, 
                    object asyncState) {
            return base.Channel.BeginHoaDonDichVu_Edit(HoaDon_DichVuID, HoaDonID, PhongID, DichVuID, KhachHangID, NgaySuDung, Thang, Nam, NgaySo, SoLuong, DonGia, TongTien, ModifiedByUser, ModifiedDate, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuSVC.EndHoaDonDichVu_Edit(System.IAsyncResult result) {
            base.Channel.EndHoaDonDichVu_Edit(result);
        }
        
        private System.IAsyncResult OnBeginHoaDonDichVu_Edit(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int HoaDon_DichVuID = ((int)(inValues[0]));
            int HoaDonID = ((int)(inValues[1]));
            int PhongID = ((int)(inValues[2]));
            int DichVuID = ((int)(inValues[3]));
            int KhachHangID = ((int)(inValues[4]));
            string NgaySuDung = ((string)(inValues[5]));
            int Thang = ((int)(inValues[6]));
            int Nam = ((int)(inValues[7]));
            int NgaySo = ((int)(inValues[8]));
            int SoLuong = ((int)(inValues[9]));
            decimal DonGia = ((decimal)(inValues[10]));
            decimal TongTien = ((decimal)(inValues[11]));
            string ModifiedByUser = ((string)(inValues[12]));
            string ModifiedDate = ((string)(inValues[13]));
            return ((QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuSVC)(this)).BeginHoaDonDichVu_Edit(HoaDon_DichVuID, HoaDonID, PhongID, DichVuID, KhachHangID, NgaySuDung, Thang, Nam, NgaySo, SoLuong, DonGia, TongTien, ModifiedByUser, ModifiedDate, callback, asyncState);
        }
        
        private object[] OnEndHoaDonDichVu_Edit(System.IAsyncResult result) {
            ((QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuSVC)(this)).EndHoaDonDichVu_Edit(result);
            return null;
        }
        
        private void OnHoaDonDichVu_EditCompleted(object state) {
            if ((this.HoaDonDichVu_EditCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.HoaDonDichVu_EditCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void HoaDonDichVu_EditAsync(int HoaDon_DichVuID, int HoaDonID, int PhongID, int DichVuID, int KhachHangID, string NgaySuDung, int Thang, int Nam, int NgaySo, int SoLuong, decimal DonGia, decimal TongTien, string ModifiedByUser, string ModifiedDate) {
            this.HoaDonDichVu_EditAsync(HoaDon_DichVuID, HoaDonID, PhongID, DichVuID, KhachHangID, NgaySuDung, Thang, Nam, NgaySo, SoLuong, DonGia, TongTien, ModifiedByUser, ModifiedDate, null);
        }
        
        public void HoaDonDichVu_EditAsync(int HoaDon_DichVuID, int HoaDonID, int PhongID, int DichVuID, int KhachHangID, string NgaySuDung, int Thang, int Nam, int NgaySo, int SoLuong, decimal DonGia, decimal TongTien, string ModifiedByUser, string ModifiedDate, object userState) {
            if ((this.onBeginHoaDonDichVu_EditDelegate == null)) {
                this.onBeginHoaDonDichVu_EditDelegate = new BeginOperationDelegate(this.OnBeginHoaDonDichVu_Edit);
            }
            if ((this.onEndHoaDonDichVu_EditDelegate == null)) {
                this.onEndHoaDonDichVu_EditDelegate = new EndOperationDelegate(this.OnEndHoaDonDichVu_Edit);
            }
            if ((this.onHoaDonDichVu_EditCompletedDelegate == null)) {
                this.onHoaDonDichVu_EditCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHoaDonDichVu_EditCompleted);
            }
            base.InvokeAsync(this.onBeginHoaDonDichVu_EditDelegate, new object[] {
                        HoaDon_DichVuID,
                        HoaDonID,
                        PhongID,
                        DichVuID,
                        KhachHangID,
                        NgaySuDung,
                        Thang,
                        Nam,
                        NgaySo,
                        SoLuong,
                        DonGia,
                        TongTien,
                        ModifiedByUser,
                        ModifiedDate}, this.onEndHoaDonDichVu_EditDelegate, this.onHoaDonDichVu_EditCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuSVC.BeginHoaDonDichVu_Delete(int HoaDon_DichVuID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginHoaDonDichVu_Delete(HoaDon_DichVuID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuSVC.EndHoaDonDichVu_Delete(System.IAsyncResult result) {
            base.Channel.EndHoaDonDichVu_Delete(result);
        }
        
        private System.IAsyncResult OnBeginHoaDonDichVu_Delete(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int HoaDon_DichVuID = ((int)(inValues[0]));
            return ((QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuSVC)(this)).BeginHoaDonDichVu_Delete(HoaDon_DichVuID, callback, asyncState);
        }
        
        private object[] OnEndHoaDonDichVu_Delete(System.IAsyncResult result) {
            ((QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuSVC)(this)).EndHoaDonDichVu_Delete(result);
            return null;
        }
        
        private void OnHoaDonDichVu_DeleteCompleted(object state) {
            if ((this.HoaDonDichVu_DeleteCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.HoaDonDichVu_DeleteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void HoaDonDichVu_DeleteAsync(int HoaDon_DichVuID) {
            this.HoaDonDichVu_DeleteAsync(HoaDon_DichVuID, null);
        }
        
        public void HoaDonDichVu_DeleteAsync(int HoaDon_DichVuID, object userState) {
            if ((this.onBeginHoaDonDichVu_DeleteDelegate == null)) {
                this.onBeginHoaDonDichVu_DeleteDelegate = new BeginOperationDelegate(this.OnBeginHoaDonDichVu_Delete);
            }
            if ((this.onEndHoaDonDichVu_DeleteDelegate == null)) {
                this.onEndHoaDonDichVu_DeleteDelegate = new EndOperationDelegate(this.OnEndHoaDonDichVu_Delete);
            }
            if ((this.onHoaDonDichVu_DeleteCompletedDelegate == null)) {
                this.onHoaDonDichVu_DeleteCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHoaDonDichVu_DeleteCompleted);
            }
            base.InvokeAsync(this.onBeginHoaDonDichVu_DeleteDelegate, new object[] {
                        HoaDon_DichVuID}, this.onEndHoaDonDichVu_DeleteDelegate, this.onHoaDonDichVu_DeleteCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuSVC.BeginHoaDonDichVu_GetItem(int HoaDon_DichVuID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginHoaDonDichVu_GetItem(HoaDon_DichVuID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuInfo QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuSVC.EndHoaDonDichVu_GetItem(System.IAsyncResult result) {
            return base.Channel.EndHoaDonDichVu_GetItem(result);
        }
        
        private System.IAsyncResult OnBeginHoaDonDichVu_GetItem(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int HoaDon_DichVuID = ((int)(inValues[0]));
            return ((QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuSVC)(this)).BeginHoaDonDichVu_GetItem(HoaDon_DichVuID, callback, asyncState);
        }
        
        private object[] OnEndHoaDonDichVu_GetItem(System.IAsyncResult result) {
            QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuInfo retVal = ((QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuSVC)(this)).EndHoaDonDichVu_GetItem(result);
            return new object[] {
                    retVal};
        }
        
        private void OnHoaDonDichVu_GetItemCompleted(object state) {
            if ((this.HoaDonDichVu_GetItemCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.HoaDonDichVu_GetItemCompleted(this, new HoaDonDichVu_GetItemCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void HoaDonDichVu_GetItemAsync(int HoaDon_DichVuID) {
            this.HoaDonDichVu_GetItemAsync(HoaDon_DichVuID, null);
        }
        
        public void HoaDonDichVu_GetItemAsync(int HoaDon_DichVuID, object userState) {
            if ((this.onBeginHoaDonDichVu_GetItemDelegate == null)) {
                this.onBeginHoaDonDichVu_GetItemDelegate = new BeginOperationDelegate(this.OnBeginHoaDonDichVu_GetItem);
            }
            if ((this.onEndHoaDonDichVu_GetItemDelegate == null)) {
                this.onEndHoaDonDichVu_GetItemDelegate = new EndOperationDelegate(this.OnEndHoaDonDichVu_GetItem);
            }
            if ((this.onHoaDonDichVu_GetItemCompletedDelegate == null)) {
                this.onHoaDonDichVu_GetItemCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHoaDonDichVu_GetItemCompleted);
            }
            base.InvokeAsync(this.onBeginHoaDonDichVu_GetItemDelegate, new object[] {
                        HoaDon_DichVuID}, this.onEndHoaDonDichVu_GetItemDelegate, this.onHoaDonDichVu_GetItemCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuSVC.BeginHoaDonDichVu_GetItems(int HoaDon_DichVuID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginHoaDonDichVu_GetItems(HoaDon_DichVuID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuInfo> QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuSVC.EndHoaDonDichVu_GetItems(System.IAsyncResult result) {
            return base.Channel.EndHoaDonDichVu_GetItems(result);
        }
        
        private System.IAsyncResult OnBeginHoaDonDichVu_GetItems(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int HoaDon_DichVuID = ((int)(inValues[0]));
            return ((QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuSVC)(this)).BeginHoaDonDichVu_GetItems(HoaDon_DichVuID, callback, asyncState);
        }
        
        private object[] OnEndHoaDonDichVu_GetItems(System.IAsyncResult result) {
            System.Collections.Generic.List<QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuInfo> retVal = ((QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuSVC)(this)).EndHoaDonDichVu_GetItems(result);
            return new object[] {
                    retVal};
        }
        
        private void OnHoaDonDichVu_GetItemsCompleted(object state) {
            if ((this.HoaDonDichVu_GetItemsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.HoaDonDichVu_GetItemsCompleted(this, new HoaDonDichVu_GetItemsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void HoaDonDichVu_GetItemsAsync(int HoaDon_DichVuID) {
            this.HoaDonDichVu_GetItemsAsync(HoaDon_DichVuID, null);
        }
        
        public void HoaDonDichVu_GetItemsAsync(int HoaDon_DichVuID, object userState) {
            if ((this.onBeginHoaDonDichVu_GetItemsDelegate == null)) {
                this.onBeginHoaDonDichVu_GetItemsDelegate = new BeginOperationDelegate(this.OnBeginHoaDonDichVu_GetItems);
            }
            if ((this.onEndHoaDonDichVu_GetItemsDelegate == null)) {
                this.onEndHoaDonDichVu_GetItemsDelegate = new EndOperationDelegate(this.OnEndHoaDonDichVu_GetItems);
            }
            if ((this.onHoaDonDichVu_GetItemsCompletedDelegate == null)) {
                this.onHoaDonDichVu_GetItemsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHoaDonDichVu_GetItemsCompleted);
            }
            base.InvokeAsync(this.onBeginHoaDonDichVu_GetItemsDelegate, new object[] {
                        HoaDon_DichVuID}, this.onEndHoaDonDichVu_GetItemsDelegate, this.onHoaDonDichVu_GetItemsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuSVC.BeginHoaDonDichVu_GetItemsByID(int HoaDonID, int PhongID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginHoaDonDichVu_GetItemsByID(HoaDonID, PhongID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuInfo> QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuSVC.EndHoaDonDichVu_GetItemsByID(System.IAsyncResult result) {
            return base.Channel.EndHoaDonDichVu_GetItemsByID(result);
        }
        
        private System.IAsyncResult OnBeginHoaDonDichVu_GetItemsByID(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int HoaDonID = ((int)(inValues[0]));
            int PhongID = ((int)(inValues[1]));
            return ((QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuSVC)(this)).BeginHoaDonDichVu_GetItemsByID(HoaDonID, PhongID, callback, asyncState);
        }
        
        private object[] OnEndHoaDonDichVu_GetItemsByID(System.IAsyncResult result) {
            System.Collections.Generic.List<QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuInfo> retVal = ((QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuSVC)(this)).EndHoaDonDichVu_GetItemsByID(result);
            return new object[] {
                    retVal};
        }
        
        private void OnHoaDonDichVu_GetItemsByIDCompleted(object state) {
            if ((this.HoaDonDichVu_GetItemsByIDCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.HoaDonDichVu_GetItemsByIDCompleted(this, new HoaDonDichVu_GetItemsByIDCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void HoaDonDichVu_GetItemsByIDAsync(int HoaDonID, int PhongID) {
            this.HoaDonDichVu_GetItemsByIDAsync(HoaDonID, PhongID, null);
        }
        
        public void HoaDonDichVu_GetItemsByIDAsync(int HoaDonID, int PhongID, object userState) {
            if ((this.onBeginHoaDonDichVu_GetItemsByIDDelegate == null)) {
                this.onBeginHoaDonDichVu_GetItemsByIDDelegate = new BeginOperationDelegate(this.OnBeginHoaDonDichVu_GetItemsByID);
            }
            if ((this.onEndHoaDonDichVu_GetItemsByIDDelegate == null)) {
                this.onEndHoaDonDichVu_GetItemsByIDDelegate = new EndOperationDelegate(this.OnEndHoaDonDichVu_GetItemsByID);
            }
            if ((this.onHoaDonDichVu_GetItemsByIDCompletedDelegate == null)) {
                this.onHoaDonDichVu_GetItemsByIDCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHoaDonDichVu_GetItemsByIDCompleted);
            }
            base.InvokeAsync(this.onBeginHoaDonDichVu_GetItemsByIDDelegate, new object[] {
                        HoaDonID,
                        PhongID}, this.onEndHoaDonDichVu_GetItemsByIDDelegate, this.onHoaDonDichVu_GetItemsByIDCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuSVC.BeginHoaDonDichVu_GetItem_NgayVao(int HoaDonID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginHoaDonDichVu_GetItem_NgayVao(HoaDonID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuanLyKhachSan.HoaDonDichVuSVC.HoaDonNgayVaoRaInfo QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuSVC.EndHoaDonDichVu_GetItem_NgayVao(System.IAsyncResult result) {
            return base.Channel.EndHoaDonDichVu_GetItem_NgayVao(result);
        }
        
        private System.IAsyncResult OnBeginHoaDonDichVu_GetItem_NgayVao(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int HoaDonID = ((int)(inValues[0]));
            return ((QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuSVC)(this)).BeginHoaDonDichVu_GetItem_NgayVao(HoaDonID, callback, asyncState);
        }
        
        private object[] OnEndHoaDonDichVu_GetItem_NgayVao(System.IAsyncResult result) {
            QuanLyKhachSan.HoaDonDichVuSVC.HoaDonNgayVaoRaInfo retVal = ((QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuSVC)(this)).EndHoaDonDichVu_GetItem_NgayVao(result);
            return new object[] {
                    retVal};
        }
        
        private void OnHoaDonDichVu_GetItem_NgayVaoCompleted(object state) {
            if ((this.HoaDonDichVu_GetItem_NgayVaoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.HoaDonDichVu_GetItem_NgayVaoCompleted(this, new HoaDonDichVu_GetItem_NgayVaoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void HoaDonDichVu_GetItem_NgayVaoAsync(int HoaDonID) {
            this.HoaDonDichVu_GetItem_NgayVaoAsync(HoaDonID, null);
        }
        
        public void HoaDonDichVu_GetItem_NgayVaoAsync(int HoaDonID, object userState) {
            if ((this.onBeginHoaDonDichVu_GetItem_NgayVaoDelegate == null)) {
                this.onBeginHoaDonDichVu_GetItem_NgayVaoDelegate = new BeginOperationDelegate(this.OnBeginHoaDonDichVu_GetItem_NgayVao);
            }
            if ((this.onEndHoaDonDichVu_GetItem_NgayVaoDelegate == null)) {
                this.onEndHoaDonDichVu_GetItem_NgayVaoDelegate = new EndOperationDelegate(this.OnEndHoaDonDichVu_GetItem_NgayVao);
            }
            if ((this.onHoaDonDichVu_GetItem_NgayVaoCompletedDelegate == null)) {
                this.onHoaDonDichVu_GetItem_NgayVaoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHoaDonDichVu_GetItem_NgayVaoCompleted);
            }
            base.InvokeAsync(this.onBeginHoaDonDichVu_GetItem_NgayVaoDelegate, new object[] {
                        HoaDonID}, this.onEndHoaDonDichVu_GetItem_NgayVaoDelegate, this.onHoaDonDichVu_GetItem_NgayVaoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuSVC.BeginHoaDonNgayRa_Add(int HoaDonID, string NgayRa, int GioRa, int PhutRa, int NgayRa_So, int ThangRa, int NamRa, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginHoaDonNgayRa_Add(HoaDonID, NgayRa, GioRa, PhutRa, NgayRa_So, ThangRa, NamRa, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuSVC.EndHoaDonNgayRa_Add(System.IAsyncResult result) {
            base.Channel.EndHoaDonNgayRa_Add(result);
        }
        
        private System.IAsyncResult OnBeginHoaDonNgayRa_Add(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int HoaDonID = ((int)(inValues[0]));
            string NgayRa = ((string)(inValues[1]));
            int GioRa = ((int)(inValues[2]));
            int PhutRa = ((int)(inValues[3]));
            int NgayRa_So = ((int)(inValues[4]));
            int ThangRa = ((int)(inValues[5]));
            int NamRa = ((int)(inValues[6]));
            return ((QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuSVC)(this)).BeginHoaDonNgayRa_Add(HoaDonID, NgayRa, GioRa, PhutRa, NgayRa_So, ThangRa, NamRa, callback, asyncState);
        }
        
        private object[] OnEndHoaDonNgayRa_Add(System.IAsyncResult result) {
            ((QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuSVC)(this)).EndHoaDonNgayRa_Add(result);
            return null;
        }
        
        private void OnHoaDonNgayRa_AddCompleted(object state) {
            if ((this.HoaDonNgayRa_AddCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.HoaDonNgayRa_AddCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void HoaDonNgayRa_AddAsync(int HoaDonID, string NgayRa, int GioRa, int PhutRa, int NgayRa_So, int ThangRa, int NamRa) {
            this.HoaDonNgayRa_AddAsync(HoaDonID, NgayRa, GioRa, PhutRa, NgayRa_So, ThangRa, NamRa, null);
        }
        
        public void HoaDonNgayRa_AddAsync(int HoaDonID, string NgayRa, int GioRa, int PhutRa, int NgayRa_So, int ThangRa, int NamRa, object userState) {
            if ((this.onBeginHoaDonNgayRa_AddDelegate == null)) {
                this.onBeginHoaDonNgayRa_AddDelegate = new BeginOperationDelegate(this.OnBeginHoaDonNgayRa_Add);
            }
            if ((this.onEndHoaDonNgayRa_AddDelegate == null)) {
                this.onEndHoaDonNgayRa_AddDelegate = new EndOperationDelegate(this.OnEndHoaDonNgayRa_Add);
            }
            if ((this.onHoaDonNgayRa_AddCompletedDelegate == null)) {
                this.onHoaDonNgayRa_AddCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHoaDonNgayRa_AddCompleted);
            }
            base.InvokeAsync(this.onBeginHoaDonNgayRa_AddDelegate, new object[] {
                        HoaDonID,
                        NgayRa,
                        GioRa,
                        PhutRa,
                        NgayRa_So,
                        ThangRa,
                        NamRa}, this.onEndHoaDonNgayRa_AddDelegate, this.onHoaDonNgayRa_AddCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuSVC.BeginHoaDonDichVu_ChuyenPhong(int HoaDonID, int PhongID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginHoaDonDichVu_ChuyenPhong(HoaDonID, PhongID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuSVC.EndHoaDonDichVu_ChuyenPhong(System.IAsyncResult result) {
            base.Channel.EndHoaDonDichVu_ChuyenPhong(result);
        }
        
        private System.IAsyncResult OnBeginHoaDonDichVu_ChuyenPhong(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int HoaDonID = ((int)(inValues[0]));
            int PhongID = ((int)(inValues[1]));
            return ((QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuSVC)(this)).BeginHoaDonDichVu_ChuyenPhong(HoaDonID, PhongID, callback, asyncState);
        }
        
        private object[] OnEndHoaDonDichVu_ChuyenPhong(System.IAsyncResult result) {
            ((QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuSVC)(this)).EndHoaDonDichVu_ChuyenPhong(result);
            return null;
        }
        
        private void OnHoaDonDichVu_ChuyenPhongCompleted(object state) {
            if ((this.HoaDonDichVu_ChuyenPhongCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.HoaDonDichVu_ChuyenPhongCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void HoaDonDichVu_ChuyenPhongAsync(int HoaDonID, int PhongID) {
            this.HoaDonDichVu_ChuyenPhongAsync(HoaDonID, PhongID, null);
        }
        
        public void HoaDonDichVu_ChuyenPhongAsync(int HoaDonID, int PhongID, object userState) {
            if ((this.onBeginHoaDonDichVu_ChuyenPhongDelegate == null)) {
                this.onBeginHoaDonDichVu_ChuyenPhongDelegate = new BeginOperationDelegate(this.OnBeginHoaDonDichVu_ChuyenPhong);
            }
            if ((this.onEndHoaDonDichVu_ChuyenPhongDelegate == null)) {
                this.onEndHoaDonDichVu_ChuyenPhongDelegate = new EndOperationDelegate(this.OnEndHoaDonDichVu_ChuyenPhong);
            }
            if ((this.onHoaDonDichVu_ChuyenPhongCompletedDelegate == null)) {
                this.onHoaDonDichVu_ChuyenPhongCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHoaDonDichVu_ChuyenPhongCompleted);
            }
            base.InvokeAsync(this.onBeginHoaDonDichVu_ChuyenPhongDelegate, new object[] {
                        HoaDonID,
                        PhongID}, this.onEndHoaDonDichVu_ChuyenPhongDelegate, this.onHoaDonDichVu_ChuyenPhongCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuSVC CreateChannel() {
            return new HoaDonDichVuSVCClientChannel(this);
        }
        
        private class HoaDonDichVuSVCClientChannel : ChannelBase<QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuSVC>, QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuSVC {
            
            public HoaDonDichVuSVCClientChannel(System.ServiceModel.ClientBase<QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuSVC> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginHoaDonDichVu_Add(int HoaDonID, int PhongID, int DichVuID, int KhachHangID, string NgaySuDung, int Thang, int Nam, int NgaySo, int SoLuong, decimal DonGia, decimal TongTien, string CreatedByUser, string CreatedDate, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[13];
                _args[0] = HoaDonID;
                _args[1] = PhongID;
                _args[2] = DichVuID;
                _args[3] = KhachHangID;
                _args[4] = NgaySuDung;
                _args[5] = Thang;
                _args[6] = Nam;
                _args[7] = NgaySo;
                _args[8] = SoLuong;
                _args[9] = DonGia;
                _args[10] = TongTien;
                _args[11] = CreatedByUser;
                _args[12] = CreatedDate;
                System.IAsyncResult _result = base.BeginInvoke("HoaDonDichVu_Add", _args, callback, asyncState);
                return _result;
            }
            
            public void EndHoaDonDichVu_Add(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("HoaDonDichVu_Add", _args, result);
            }
            
            public System.IAsyncResult BeginHoaDonDichVu_Edit(
                        int HoaDon_DichVuID, 
                        int HoaDonID, 
                        int PhongID, 
                        int DichVuID, 
                        int KhachHangID, 
                        string NgaySuDung, 
                        int Thang, 
                        int Nam, 
                        int NgaySo, 
                        int SoLuong, 
                        decimal DonGia, 
                        decimal TongTien, 
                        string ModifiedByUser, 
                        string ModifiedDate, 
                        System.AsyncCallback callback, 
                        object asyncState) {
                object[] _args = new object[14];
                _args[0] = HoaDon_DichVuID;
                _args[1] = HoaDonID;
                _args[2] = PhongID;
                _args[3] = DichVuID;
                _args[4] = KhachHangID;
                _args[5] = NgaySuDung;
                _args[6] = Thang;
                _args[7] = Nam;
                _args[8] = NgaySo;
                _args[9] = SoLuong;
                _args[10] = DonGia;
                _args[11] = TongTien;
                _args[12] = ModifiedByUser;
                _args[13] = ModifiedDate;
                System.IAsyncResult _result = base.BeginInvoke("HoaDonDichVu_Edit", _args, callback, asyncState);
                return _result;
            }
            
            public void EndHoaDonDichVu_Edit(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("HoaDonDichVu_Edit", _args, result);
            }
            
            public System.IAsyncResult BeginHoaDonDichVu_Delete(int HoaDon_DichVuID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = HoaDon_DichVuID;
                System.IAsyncResult _result = base.BeginInvoke("HoaDonDichVu_Delete", _args, callback, asyncState);
                return _result;
            }
            
            public void EndHoaDonDichVu_Delete(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("HoaDonDichVu_Delete", _args, result);
            }
            
            public System.IAsyncResult BeginHoaDonDichVu_GetItem(int HoaDon_DichVuID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = HoaDon_DichVuID;
                System.IAsyncResult _result = base.BeginInvoke("HoaDonDichVu_GetItem", _args, callback, asyncState);
                return _result;
            }
            
            public QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuInfo EndHoaDonDichVu_GetItem(System.IAsyncResult result) {
                object[] _args = new object[0];
                QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuInfo _result = ((QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuInfo)(base.EndInvoke("HoaDonDichVu_GetItem", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginHoaDonDichVu_GetItems(int HoaDon_DichVuID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = HoaDon_DichVuID;
                System.IAsyncResult _result = base.BeginInvoke("HoaDonDichVu_GetItems", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuInfo> EndHoaDonDichVu_GetItems(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuInfo> _result = ((System.Collections.Generic.List<QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuInfo>)(base.EndInvoke("HoaDonDichVu_GetItems", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginHoaDonDichVu_GetItemsByID(int HoaDonID, int PhongID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = HoaDonID;
                _args[1] = PhongID;
                System.IAsyncResult _result = base.BeginInvoke("HoaDonDichVu_GetItemsByID", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuInfo> EndHoaDonDichVu_GetItemsByID(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuInfo> _result = ((System.Collections.Generic.List<QuanLyKhachSan.HoaDonDichVuSVC.HoaDonDichVuInfo>)(base.EndInvoke("HoaDonDichVu_GetItemsByID", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginHoaDonDichVu_GetItem_NgayVao(int HoaDonID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = HoaDonID;
                System.IAsyncResult _result = base.BeginInvoke("HoaDonDichVu_GetItem_NgayVao", _args, callback, asyncState);
                return _result;
            }
            
            public QuanLyKhachSan.HoaDonDichVuSVC.HoaDonNgayVaoRaInfo EndHoaDonDichVu_GetItem_NgayVao(System.IAsyncResult result) {
                object[] _args = new object[0];
                QuanLyKhachSan.HoaDonDichVuSVC.HoaDonNgayVaoRaInfo _result = ((QuanLyKhachSan.HoaDonDichVuSVC.HoaDonNgayVaoRaInfo)(base.EndInvoke("HoaDonDichVu_GetItem_NgayVao", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginHoaDonNgayRa_Add(int HoaDonID, string NgayRa, int GioRa, int PhutRa, int NgayRa_So, int ThangRa, int NamRa, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[7];
                _args[0] = HoaDonID;
                _args[1] = NgayRa;
                _args[2] = GioRa;
                _args[3] = PhutRa;
                _args[4] = NgayRa_So;
                _args[5] = ThangRa;
                _args[6] = NamRa;
                System.IAsyncResult _result = base.BeginInvoke("HoaDonNgayRa_Add", _args, callback, asyncState);
                return _result;
            }
            
            public void EndHoaDonNgayRa_Add(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("HoaDonNgayRa_Add", _args, result);
            }
            
            public System.IAsyncResult BeginHoaDonDichVu_ChuyenPhong(int HoaDonID, int PhongID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = HoaDonID;
                _args[1] = PhongID;
                System.IAsyncResult _result = base.BeginInvoke("HoaDonDichVu_ChuyenPhong", _args, callback, asyncState);
                return _result;
            }
            
            public void EndHoaDonDichVu_ChuyenPhong(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("HoaDonDichVu_ChuyenPhong", _args, result);
            }
        }
    }
}
