//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
// 
namespace QuanLyKhachSan.UserSVC {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserInfo", Namespace="http://schemas.datacontract.org/2004/07/QuanLyKhachSan")]
    public partial class UserInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int CreatedByUserField;
        
        private string CreatedDateField;
        
        private string DisplayNameField;
        
        private string FullNameField;
        
        private int IsActivedField;
        
        private int ModifiedByUserField;
        
        private string ModifiedDateField;
        
        private string PassWordField;
        
        private int UserIDField;
        
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CreatedByUser {
            get {
                return this.CreatedByUserField;
            }
            set {
                if ((this.CreatedByUserField.Equals(value) != true)) {
                    this.CreatedByUserField = value;
                    this.RaisePropertyChanged("CreatedByUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedDateField, value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayName {
            get {
                return this.DisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayNameField, value) != true)) {
                    this.DisplayNameField = value;
                    this.RaisePropertyChanged("DisplayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IsActived {
            get {
                return this.IsActivedField;
            }
            set {
                if ((this.IsActivedField.Equals(value) != true)) {
                    this.IsActivedField = value;
                    this.RaisePropertyChanged("IsActived");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ModifiedByUser {
            get {
                return this.ModifiedByUserField;
            }
            set {
                if ((this.ModifiedByUserField.Equals(value) != true)) {
                    this.ModifiedByUserField = value;
                    this.RaisePropertyChanged("ModifiedByUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ModifiedDateField, value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PassWord {
            get {
                return this.PassWordField;
            }
            set {
                if ((object.ReferenceEquals(this.PassWordField, value) != true)) {
                    this.PassWordField = value;
                    this.RaisePropertyChanged("PassWord");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="UserSVC.UserSVC")]
    public interface UserSVC {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:UserSVC/User_Add", ReplyAction="urn:UserSVC/User_AddResponse")]
        System.IAsyncResult BeginUser_Add(string UserName, string PassWord, string FullName, string DisplayName, int IsActived, int CreatedByUser, string CreatedDate, System.AsyncCallback callback, object asyncState);
        
        void EndUser_Add(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:UserSVC/User_Edit", ReplyAction="urn:UserSVC/User_EditResponse")]
        System.IAsyncResult BeginUser_Edit(int UserID, string UserName, string PassWord, string FullName, string DisplayName, int IsActived, int ModifiedByUser, string ModifiedDate, System.AsyncCallback callback, object asyncState);
        
        void EndUser_Edit(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:UserSVC/User_Delete", ReplyAction="urn:UserSVC/User_DeleteResponse")]
        System.IAsyncResult BeginUser_Delete(int UserID, System.AsyncCallback callback, object asyncState);
        
        void EndUser_Delete(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:UserSVC/User_GetItem", ReplyAction="urn:UserSVC/User_GetItemResponse")]
        System.IAsyncResult BeginUser_GetItem(int UserID, System.AsyncCallback callback, object asyncState);
        
        QuanLyKhachSan.UserSVC.UserInfo EndUser_GetItem(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:UserSVC/User_GetItems", ReplyAction="urn:UserSVC/User_GetItemsResponse")]
        System.IAsyncResult BeginUser_GetItems(int UserID, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<QuanLyKhachSan.UserSVC.UserInfo> EndUser_GetItems(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:UserSVC/User_GetActivedItems", ReplyAction="urn:UserSVC/User_GetActivedItemsResponse")]
        System.IAsyncResult BeginUser_GetActivedItems(System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<QuanLyKhachSan.UserSVC.UserInfo> EndUser_GetActivedItems(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:UserSVC/Users_Login", ReplyAction="urn:UserSVC/Users_LoginResponse")]
        System.IAsyncResult BeginUsers_Login(string UserName, string PassWord, System.AsyncCallback callback, object asyncState);
        
        int EndUsers_Login(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserSVCChannel : QuanLyKhachSan.UserSVC.UserSVC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class User_GetItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public User_GetItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public QuanLyKhachSan.UserSVC.UserInfo Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((QuanLyKhachSan.UserSVC.UserInfo)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class User_GetItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public User_GetItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<QuanLyKhachSan.UserSVC.UserInfo> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<QuanLyKhachSan.UserSVC.UserInfo>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class User_GetActivedItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public User_GetActivedItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<QuanLyKhachSan.UserSVC.UserInfo> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<QuanLyKhachSan.UserSVC.UserInfo>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Users_LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public Users_LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserSVCClient : System.ServiceModel.ClientBase<QuanLyKhachSan.UserSVC.UserSVC>, QuanLyKhachSan.UserSVC.UserSVC {
        
        private BeginOperationDelegate onBeginUser_AddDelegate;
        
        private EndOperationDelegate onEndUser_AddDelegate;
        
        private System.Threading.SendOrPostCallback onUser_AddCompletedDelegate;
        
        private BeginOperationDelegate onBeginUser_EditDelegate;
        
        private EndOperationDelegate onEndUser_EditDelegate;
        
        private System.Threading.SendOrPostCallback onUser_EditCompletedDelegate;
        
        private BeginOperationDelegate onBeginUser_DeleteDelegate;
        
        private EndOperationDelegate onEndUser_DeleteDelegate;
        
        private System.Threading.SendOrPostCallback onUser_DeleteCompletedDelegate;
        
        private BeginOperationDelegate onBeginUser_GetItemDelegate;
        
        private EndOperationDelegate onEndUser_GetItemDelegate;
        
        private System.Threading.SendOrPostCallback onUser_GetItemCompletedDelegate;
        
        private BeginOperationDelegate onBeginUser_GetItemsDelegate;
        
        private EndOperationDelegate onEndUser_GetItemsDelegate;
        
        private System.Threading.SendOrPostCallback onUser_GetItemsCompletedDelegate;
        
        private BeginOperationDelegate onBeginUser_GetActivedItemsDelegate;
        
        private EndOperationDelegate onEndUser_GetActivedItemsDelegate;
        
        private System.Threading.SendOrPostCallback onUser_GetActivedItemsCompletedDelegate;
        
        private BeginOperationDelegate onBeginUsers_LoginDelegate;
        
        private EndOperationDelegate onEndUsers_LoginDelegate;
        
        private System.Threading.SendOrPostCallback onUsers_LoginCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public UserSVCClient() {
        }
        
        public UserSVCClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserSVCClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserSVCClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserSVCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> User_AddCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> User_EditCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> User_DeleteCompleted;
        
        public event System.EventHandler<User_GetItemCompletedEventArgs> User_GetItemCompleted;
        
        public event System.EventHandler<User_GetItemsCompletedEventArgs> User_GetItemsCompleted;
        
        public event System.EventHandler<User_GetActivedItemsCompletedEventArgs> User_GetActivedItemsCompleted;
        
        public event System.EventHandler<Users_LoginCompletedEventArgs> Users_LoginCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QuanLyKhachSan.UserSVC.UserSVC.BeginUser_Add(string UserName, string PassWord, string FullName, string DisplayName, int IsActived, int CreatedByUser, string CreatedDate, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUser_Add(UserName, PassWord, FullName, DisplayName, IsActived, CreatedByUser, CreatedDate, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void QuanLyKhachSan.UserSVC.UserSVC.EndUser_Add(System.IAsyncResult result) {
            base.Channel.EndUser_Add(result);
        }
        
        private System.IAsyncResult OnBeginUser_Add(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string UserName = ((string)(inValues[0]));
            string PassWord = ((string)(inValues[1]));
            string FullName = ((string)(inValues[2]));
            string DisplayName = ((string)(inValues[3]));
            int IsActived = ((int)(inValues[4]));
            int CreatedByUser = ((int)(inValues[5]));
            string CreatedDate = ((string)(inValues[6]));
            return ((QuanLyKhachSan.UserSVC.UserSVC)(this)).BeginUser_Add(UserName, PassWord, FullName, DisplayName, IsActived, CreatedByUser, CreatedDate, callback, asyncState);
        }
        
        private object[] OnEndUser_Add(System.IAsyncResult result) {
            ((QuanLyKhachSan.UserSVC.UserSVC)(this)).EndUser_Add(result);
            return null;
        }
        
        private void OnUser_AddCompleted(object state) {
            if ((this.User_AddCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.User_AddCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void User_AddAsync(string UserName, string PassWord, string FullName, string DisplayName, int IsActived, int CreatedByUser, string CreatedDate) {
            this.User_AddAsync(UserName, PassWord, FullName, DisplayName, IsActived, CreatedByUser, CreatedDate, null);
        }
        
        public void User_AddAsync(string UserName, string PassWord, string FullName, string DisplayName, int IsActived, int CreatedByUser, string CreatedDate, object userState) {
            if ((this.onBeginUser_AddDelegate == null)) {
                this.onBeginUser_AddDelegate = new BeginOperationDelegate(this.OnBeginUser_Add);
            }
            if ((this.onEndUser_AddDelegate == null)) {
                this.onEndUser_AddDelegate = new EndOperationDelegate(this.OnEndUser_Add);
            }
            if ((this.onUser_AddCompletedDelegate == null)) {
                this.onUser_AddCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUser_AddCompleted);
            }
            base.InvokeAsync(this.onBeginUser_AddDelegate, new object[] {
                        UserName,
                        PassWord,
                        FullName,
                        DisplayName,
                        IsActived,
                        CreatedByUser,
                        CreatedDate}, this.onEndUser_AddDelegate, this.onUser_AddCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QuanLyKhachSan.UserSVC.UserSVC.BeginUser_Edit(int UserID, string UserName, string PassWord, string FullName, string DisplayName, int IsActived, int ModifiedByUser, string ModifiedDate, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUser_Edit(UserID, UserName, PassWord, FullName, DisplayName, IsActived, ModifiedByUser, ModifiedDate, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void QuanLyKhachSan.UserSVC.UserSVC.EndUser_Edit(System.IAsyncResult result) {
            base.Channel.EndUser_Edit(result);
        }
        
        private System.IAsyncResult OnBeginUser_Edit(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int UserID = ((int)(inValues[0]));
            string UserName = ((string)(inValues[1]));
            string PassWord = ((string)(inValues[2]));
            string FullName = ((string)(inValues[3]));
            string DisplayName = ((string)(inValues[4]));
            int IsActived = ((int)(inValues[5]));
            int ModifiedByUser = ((int)(inValues[6]));
            string ModifiedDate = ((string)(inValues[7]));
            return ((QuanLyKhachSan.UserSVC.UserSVC)(this)).BeginUser_Edit(UserID, UserName, PassWord, FullName, DisplayName, IsActived, ModifiedByUser, ModifiedDate, callback, asyncState);
        }
        
        private object[] OnEndUser_Edit(System.IAsyncResult result) {
            ((QuanLyKhachSan.UserSVC.UserSVC)(this)).EndUser_Edit(result);
            return null;
        }
        
        private void OnUser_EditCompleted(object state) {
            if ((this.User_EditCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.User_EditCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void User_EditAsync(int UserID, string UserName, string PassWord, string FullName, string DisplayName, int IsActived, int ModifiedByUser, string ModifiedDate) {
            this.User_EditAsync(UserID, UserName, PassWord, FullName, DisplayName, IsActived, ModifiedByUser, ModifiedDate, null);
        }
        
        public void User_EditAsync(int UserID, string UserName, string PassWord, string FullName, string DisplayName, int IsActived, int ModifiedByUser, string ModifiedDate, object userState) {
            if ((this.onBeginUser_EditDelegate == null)) {
                this.onBeginUser_EditDelegate = new BeginOperationDelegate(this.OnBeginUser_Edit);
            }
            if ((this.onEndUser_EditDelegate == null)) {
                this.onEndUser_EditDelegate = new EndOperationDelegate(this.OnEndUser_Edit);
            }
            if ((this.onUser_EditCompletedDelegate == null)) {
                this.onUser_EditCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUser_EditCompleted);
            }
            base.InvokeAsync(this.onBeginUser_EditDelegate, new object[] {
                        UserID,
                        UserName,
                        PassWord,
                        FullName,
                        DisplayName,
                        IsActived,
                        ModifiedByUser,
                        ModifiedDate}, this.onEndUser_EditDelegate, this.onUser_EditCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QuanLyKhachSan.UserSVC.UserSVC.BeginUser_Delete(int UserID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUser_Delete(UserID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void QuanLyKhachSan.UserSVC.UserSVC.EndUser_Delete(System.IAsyncResult result) {
            base.Channel.EndUser_Delete(result);
        }
        
        private System.IAsyncResult OnBeginUser_Delete(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int UserID = ((int)(inValues[0]));
            return ((QuanLyKhachSan.UserSVC.UserSVC)(this)).BeginUser_Delete(UserID, callback, asyncState);
        }
        
        private object[] OnEndUser_Delete(System.IAsyncResult result) {
            ((QuanLyKhachSan.UserSVC.UserSVC)(this)).EndUser_Delete(result);
            return null;
        }
        
        private void OnUser_DeleteCompleted(object state) {
            if ((this.User_DeleteCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.User_DeleteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void User_DeleteAsync(int UserID) {
            this.User_DeleteAsync(UserID, null);
        }
        
        public void User_DeleteAsync(int UserID, object userState) {
            if ((this.onBeginUser_DeleteDelegate == null)) {
                this.onBeginUser_DeleteDelegate = new BeginOperationDelegate(this.OnBeginUser_Delete);
            }
            if ((this.onEndUser_DeleteDelegate == null)) {
                this.onEndUser_DeleteDelegate = new EndOperationDelegate(this.OnEndUser_Delete);
            }
            if ((this.onUser_DeleteCompletedDelegate == null)) {
                this.onUser_DeleteCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUser_DeleteCompleted);
            }
            base.InvokeAsync(this.onBeginUser_DeleteDelegate, new object[] {
                        UserID}, this.onEndUser_DeleteDelegate, this.onUser_DeleteCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QuanLyKhachSan.UserSVC.UserSVC.BeginUser_GetItem(int UserID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUser_GetItem(UserID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuanLyKhachSan.UserSVC.UserInfo QuanLyKhachSan.UserSVC.UserSVC.EndUser_GetItem(System.IAsyncResult result) {
            return base.Channel.EndUser_GetItem(result);
        }
        
        private System.IAsyncResult OnBeginUser_GetItem(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int UserID = ((int)(inValues[0]));
            return ((QuanLyKhachSan.UserSVC.UserSVC)(this)).BeginUser_GetItem(UserID, callback, asyncState);
        }
        
        private object[] OnEndUser_GetItem(System.IAsyncResult result) {
            QuanLyKhachSan.UserSVC.UserInfo retVal = ((QuanLyKhachSan.UserSVC.UserSVC)(this)).EndUser_GetItem(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUser_GetItemCompleted(object state) {
            if ((this.User_GetItemCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.User_GetItemCompleted(this, new User_GetItemCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void User_GetItemAsync(int UserID) {
            this.User_GetItemAsync(UserID, null);
        }
        
        public void User_GetItemAsync(int UserID, object userState) {
            if ((this.onBeginUser_GetItemDelegate == null)) {
                this.onBeginUser_GetItemDelegate = new BeginOperationDelegate(this.OnBeginUser_GetItem);
            }
            if ((this.onEndUser_GetItemDelegate == null)) {
                this.onEndUser_GetItemDelegate = new EndOperationDelegate(this.OnEndUser_GetItem);
            }
            if ((this.onUser_GetItemCompletedDelegate == null)) {
                this.onUser_GetItemCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUser_GetItemCompleted);
            }
            base.InvokeAsync(this.onBeginUser_GetItemDelegate, new object[] {
                        UserID}, this.onEndUser_GetItemDelegate, this.onUser_GetItemCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QuanLyKhachSan.UserSVC.UserSVC.BeginUser_GetItems(int UserID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUser_GetItems(UserID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<QuanLyKhachSan.UserSVC.UserInfo> QuanLyKhachSan.UserSVC.UserSVC.EndUser_GetItems(System.IAsyncResult result) {
            return base.Channel.EndUser_GetItems(result);
        }
        
        private System.IAsyncResult OnBeginUser_GetItems(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int UserID = ((int)(inValues[0]));
            return ((QuanLyKhachSan.UserSVC.UserSVC)(this)).BeginUser_GetItems(UserID, callback, asyncState);
        }
        
        private object[] OnEndUser_GetItems(System.IAsyncResult result) {
            System.Collections.Generic.List<QuanLyKhachSan.UserSVC.UserInfo> retVal = ((QuanLyKhachSan.UserSVC.UserSVC)(this)).EndUser_GetItems(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUser_GetItemsCompleted(object state) {
            if ((this.User_GetItemsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.User_GetItemsCompleted(this, new User_GetItemsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void User_GetItemsAsync(int UserID) {
            this.User_GetItemsAsync(UserID, null);
        }
        
        public void User_GetItemsAsync(int UserID, object userState) {
            if ((this.onBeginUser_GetItemsDelegate == null)) {
                this.onBeginUser_GetItemsDelegate = new BeginOperationDelegate(this.OnBeginUser_GetItems);
            }
            if ((this.onEndUser_GetItemsDelegate == null)) {
                this.onEndUser_GetItemsDelegate = new EndOperationDelegate(this.OnEndUser_GetItems);
            }
            if ((this.onUser_GetItemsCompletedDelegate == null)) {
                this.onUser_GetItemsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUser_GetItemsCompleted);
            }
            base.InvokeAsync(this.onBeginUser_GetItemsDelegate, new object[] {
                        UserID}, this.onEndUser_GetItemsDelegate, this.onUser_GetItemsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QuanLyKhachSan.UserSVC.UserSVC.BeginUser_GetActivedItems(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUser_GetActivedItems(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<QuanLyKhachSan.UserSVC.UserInfo> QuanLyKhachSan.UserSVC.UserSVC.EndUser_GetActivedItems(System.IAsyncResult result) {
            return base.Channel.EndUser_GetActivedItems(result);
        }
        
        private System.IAsyncResult OnBeginUser_GetActivedItems(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((QuanLyKhachSan.UserSVC.UserSVC)(this)).BeginUser_GetActivedItems(callback, asyncState);
        }
        
        private object[] OnEndUser_GetActivedItems(System.IAsyncResult result) {
            System.Collections.Generic.List<QuanLyKhachSan.UserSVC.UserInfo> retVal = ((QuanLyKhachSan.UserSVC.UserSVC)(this)).EndUser_GetActivedItems(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUser_GetActivedItemsCompleted(object state) {
            if ((this.User_GetActivedItemsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.User_GetActivedItemsCompleted(this, new User_GetActivedItemsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void User_GetActivedItemsAsync() {
            this.User_GetActivedItemsAsync(null);
        }
        
        public void User_GetActivedItemsAsync(object userState) {
            if ((this.onBeginUser_GetActivedItemsDelegate == null)) {
                this.onBeginUser_GetActivedItemsDelegate = new BeginOperationDelegate(this.OnBeginUser_GetActivedItems);
            }
            if ((this.onEndUser_GetActivedItemsDelegate == null)) {
                this.onEndUser_GetActivedItemsDelegate = new EndOperationDelegate(this.OnEndUser_GetActivedItems);
            }
            if ((this.onUser_GetActivedItemsCompletedDelegate == null)) {
                this.onUser_GetActivedItemsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUser_GetActivedItemsCompleted);
            }
            base.InvokeAsync(this.onBeginUser_GetActivedItemsDelegate, null, this.onEndUser_GetActivedItemsDelegate, this.onUser_GetActivedItemsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QuanLyKhachSan.UserSVC.UserSVC.BeginUsers_Login(string UserName, string PassWord, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUsers_Login(UserName, PassWord, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int QuanLyKhachSan.UserSVC.UserSVC.EndUsers_Login(System.IAsyncResult result) {
            return base.Channel.EndUsers_Login(result);
        }
        
        private System.IAsyncResult OnBeginUsers_Login(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string UserName = ((string)(inValues[0]));
            string PassWord = ((string)(inValues[1]));
            return ((QuanLyKhachSan.UserSVC.UserSVC)(this)).BeginUsers_Login(UserName, PassWord, callback, asyncState);
        }
        
        private object[] OnEndUsers_Login(System.IAsyncResult result) {
            int retVal = ((QuanLyKhachSan.UserSVC.UserSVC)(this)).EndUsers_Login(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUsers_LoginCompleted(object state) {
            if ((this.Users_LoginCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.Users_LoginCompleted(this, new Users_LoginCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void Users_LoginAsync(string UserName, string PassWord) {
            this.Users_LoginAsync(UserName, PassWord, null);
        }
        
        public void Users_LoginAsync(string UserName, string PassWord, object userState) {
            if ((this.onBeginUsers_LoginDelegate == null)) {
                this.onBeginUsers_LoginDelegate = new BeginOperationDelegate(this.OnBeginUsers_Login);
            }
            if ((this.onEndUsers_LoginDelegate == null)) {
                this.onEndUsers_LoginDelegate = new EndOperationDelegate(this.OnEndUsers_Login);
            }
            if ((this.onUsers_LoginCompletedDelegate == null)) {
                this.onUsers_LoginCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUsers_LoginCompleted);
            }
            base.InvokeAsync(this.onBeginUsers_LoginDelegate, new object[] {
                        UserName,
                        PassWord}, this.onEndUsers_LoginDelegate, this.onUsers_LoginCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override QuanLyKhachSan.UserSVC.UserSVC CreateChannel() {
            return new UserSVCClientChannel(this);
        }
        
        private class UserSVCClientChannel : ChannelBase<QuanLyKhachSan.UserSVC.UserSVC>, QuanLyKhachSan.UserSVC.UserSVC {
            
            public UserSVCClientChannel(System.ServiceModel.ClientBase<QuanLyKhachSan.UserSVC.UserSVC> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginUser_Add(string UserName, string PassWord, string FullName, string DisplayName, int IsActived, int CreatedByUser, string CreatedDate, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[7];
                _args[0] = UserName;
                _args[1] = PassWord;
                _args[2] = FullName;
                _args[3] = DisplayName;
                _args[4] = IsActived;
                _args[5] = CreatedByUser;
                _args[6] = CreatedDate;
                System.IAsyncResult _result = base.BeginInvoke("User_Add", _args, callback, asyncState);
                return _result;
            }
            
            public void EndUser_Add(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("User_Add", _args, result);
            }
            
            public System.IAsyncResult BeginUser_Edit(int UserID, string UserName, string PassWord, string FullName, string DisplayName, int IsActived, int ModifiedByUser, string ModifiedDate, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[8];
                _args[0] = UserID;
                _args[1] = UserName;
                _args[2] = PassWord;
                _args[3] = FullName;
                _args[4] = DisplayName;
                _args[5] = IsActived;
                _args[6] = ModifiedByUser;
                _args[7] = ModifiedDate;
                System.IAsyncResult _result = base.BeginInvoke("User_Edit", _args, callback, asyncState);
                return _result;
            }
            
            public void EndUser_Edit(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("User_Edit", _args, result);
            }
            
            public System.IAsyncResult BeginUser_Delete(int UserID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = UserID;
                System.IAsyncResult _result = base.BeginInvoke("User_Delete", _args, callback, asyncState);
                return _result;
            }
            
            public void EndUser_Delete(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("User_Delete", _args, result);
            }
            
            public System.IAsyncResult BeginUser_GetItem(int UserID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = UserID;
                System.IAsyncResult _result = base.BeginInvoke("User_GetItem", _args, callback, asyncState);
                return _result;
            }
            
            public QuanLyKhachSan.UserSVC.UserInfo EndUser_GetItem(System.IAsyncResult result) {
                object[] _args = new object[0];
                QuanLyKhachSan.UserSVC.UserInfo _result = ((QuanLyKhachSan.UserSVC.UserInfo)(base.EndInvoke("User_GetItem", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginUser_GetItems(int UserID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = UserID;
                System.IAsyncResult _result = base.BeginInvoke("User_GetItems", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<QuanLyKhachSan.UserSVC.UserInfo> EndUser_GetItems(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<QuanLyKhachSan.UserSVC.UserInfo> _result = ((System.Collections.Generic.List<QuanLyKhachSan.UserSVC.UserInfo>)(base.EndInvoke("User_GetItems", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginUser_GetActivedItems(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("User_GetActivedItems", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<QuanLyKhachSan.UserSVC.UserInfo> EndUser_GetActivedItems(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<QuanLyKhachSan.UserSVC.UserInfo> _result = ((System.Collections.Generic.List<QuanLyKhachSan.UserSVC.UserInfo>)(base.EndInvoke("User_GetActivedItems", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginUsers_Login(string UserName, string PassWord, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = UserName;
                _args[1] = PassWord;
                System.IAsyncResult _result = base.BeginInvoke("Users_Login", _args, callback, asyncState);
                return _result;
            }
            
            public int EndUsers_Login(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("Users_Login", _args, result)));
                return _result;
            }
        }
    }
}
