//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
// 
namespace QuanLyKhachSan.TKDoanhThuDichVuSVC {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TKDoanhThuDichVuInfo", Namespace="http://schemas.datacontract.org/2004/07/QuanLyKhachSan")]
    public partial class TKDoanhThuDichVuInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int CreatedByUserField;
        
        private string CreatedDateField;
        
        private int DichVuIDField;
        
        private string DichVuNameField;
        
        private decimal DonGiaField;
        
        private string HoTenField;
        
        private int HoaDonIDField;
        
        private int HoaDon_DichVuIDField;
        
        private int KhachHangIDField;
        
        private int ModifiedByUserField;
        
        private string ModifiedDateField;
        
        private int NamField;
        
        private int NgaySoField;
        
        private string NgaySuDungField;
        
        private int PhongIDField;
        
        private string PhongNameField;
        
        private int SoLuongField;
        
        private int ThangField;
        
        private decimal TongTienField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CreatedByUser {
            get {
                return this.CreatedByUserField;
            }
            set {
                if ((this.CreatedByUserField.Equals(value) != true)) {
                    this.CreatedByUserField = value;
                    this.RaisePropertyChanged("CreatedByUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedDateField, value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DichVuID {
            get {
                return this.DichVuIDField;
            }
            set {
                if ((this.DichVuIDField.Equals(value) != true)) {
                    this.DichVuIDField = value;
                    this.RaisePropertyChanged("DichVuID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DichVuName {
            get {
                return this.DichVuNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DichVuNameField, value) != true)) {
                    this.DichVuNameField = value;
                    this.RaisePropertyChanged("DichVuName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DonGia {
            get {
                return this.DonGiaField;
            }
            set {
                if ((this.DonGiaField.Equals(value) != true)) {
                    this.DonGiaField = value;
                    this.RaisePropertyChanged("DonGia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HoTen {
            get {
                return this.HoTenField;
            }
            set {
                if ((object.ReferenceEquals(this.HoTenField, value) != true)) {
                    this.HoTenField = value;
                    this.RaisePropertyChanged("HoTen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HoaDonID {
            get {
                return this.HoaDonIDField;
            }
            set {
                if ((this.HoaDonIDField.Equals(value) != true)) {
                    this.HoaDonIDField = value;
                    this.RaisePropertyChanged("HoaDonID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HoaDon_DichVuID {
            get {
                return this.HoaDon_DichVuIDField;
            }
            set {
                if ((this.HoaDon_DichVuIDField.Equals(value) != true)) {
                    this.HoaDon_DichVuIDField = value;
                    this.RaisePropertyChanged("HoaDon_DichVuID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KhachHangID {
            get {
                return this.KhachHangIDField;
            }
            set {
                if ((this.KhachHangIDField.Equals(value) != true)) {
                    this.KhachHangIDField = value;
                    this.RaisePropertyChanged("KhachHangID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ModifiedByUser {
            get {
                return this.ModifiedByUserField;
            }
            set {
                if ((this.ModifiedByUserField.Equals(value) != true)) {
                    this.ModifiedByUserField = value;
                    this.RaisePropertyChanged("ModifiedByUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ModifiedDateField, value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Nam {
            get {
                return this.NamField;
            }
            set {
                if ((this.NamField.Equals(value) != true)) {
                    this.NamField = value;
                    this.RaisePropertyChanged("Nam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NgaySo {
            get {
                return this.NgaySoField;
            }
            set {
                if ((this.NgaySoField.Equals(value) != true)) {
                    this.NgaySoField = value;
                    this.RaisePropertyChanged("NgaySo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NgaySuDung {
            get {
                return this.NgaySuDungField;
            }
            set {
                if ((object.ReferenceEquals(this.NgaySuDungField, value) != true)) {
                    this.NgaySuDungField = value;
                    this.RaisePropertyChanged("NgaySuDung");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PhongID {
            get {
                return this.PhongIDField;
            }
            set {
                if ((this.PhongIDField.Equals(value) != true)) {
                    this.PhongIDField = value;
                    this.RaisePropertyChanged("PhongID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhongName {
            get {
                return this.PhongNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PhongNameField, value) != true)) {
                    this.PhongNameField = value;
                    this.RaisePropertyChanged("PhongName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SoLuong {
            get {
                return this.SoLuongField;
            }
            set {
                if ((this.SoLuongField.Equals(value) != true)) {
                    this.SoLuongField = value;
                    this.RaisePropertyChanged("SoLuong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Thang {
            get {
                return this.ThangField;
            }
            set {
                if ((this.ThangField.Equals(value) != true)) {
                    this.ThangField = value;
                    this.RaisePropertyChanged("Thang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TongTien {
            get {
                return this.TongTienField;
            }
            set {
                if ((this.TongTienField.Equals(value) != true)) {
                    this.TongTienField = value;
                    this.RaisePropertyChanged("TongTien");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="TKDoanhThuDichVuSVC.TKDoanhThuDichVuSVC")]
    public interface TKDoanhThuDichVuSVC {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:TKDoanhThuDichVuSVC/HoaDonDichVu_GetItems_TheoNgay", ReplyAction="urn:TKDoanhThuDichVuSVC/HoaDonDichVu_GetItems_TheoNgayResponse")]
        System.IAsyncResult BeginHoaDonDichVu_GetItems_TheoNgay(int NgaySo, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<QuanLyKhachSan.TKDoanhThuDichVuSVC.TKDoanhThuDichVuInfo> EndHoaDonDichVu_GetItems_TheoNgay(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:TKDoanhThuDichVuSVC/HoaDonDichVu_GetItems_TheoThang", ReplyAction="urn:TKDoanhThuDichVuSVC/HoaDonDichVu_GetItems_TheoThangResponse")]
        System.IAsyncResult BeginHoaDonDichVu_GetItems_TheoThang(int Thang, int Nam, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<QuanLyKhachSan.TKDoanhThuDichVuSVC.TKDoanhThuDichVuInfo> EndHoaDonDichVu_GetItems_TheoThang(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:TKDoanhThuDichVuSVC/HoaDonDichVu_GetItems_TheoNam", ReplyAction="urn:TKDoanhThuDichVuSVC/HoaDonDichVu_GetItems_TheoNamResponse")]
        System.IAsyncResult BeginHoaDonDichVu_GetItems_TheoNam(int Nam, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<QuanLyKhachSan.TKDoanhThuDichVuSVC.TKDoanhThuDichVuInfo> EndHoaDonDichVu_GetItems_TheoNam(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:TKDoanhThuDichVuSVC/HoaDonDichVu_GetItems_TuNgayDenNgay", ReplyAction="urn:TKDoanhThuDichVuSVC/HoaDonDichVu_GetItems_TuNgayDenNgayResponse")]
        System.IAsyncResult BeginHoaDonDichVu_GetItems_TuNgayDenNgay(int TuNgaySo, int DenNgaySo, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<QuanLyKhachSan.TKDoanhThuDichVuSVC.TKDoanhThuDichVuInfo> EndHoaDonDichVu_GetItems_TuNgayDenNgay(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TKDoanhThuDichVuSVCChannel : QuanLyKhachSan.TKDoanhThuDichVuSVC.TKDoanhThuDichVuSVC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HoaDonDichVu_GetItems_TheoNgayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public HoaDonDichVu_GetItems_TheoNgayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<QuanLyKhachSan.TKDoanhThuDichVuSVC.TKDoanhThuDichVuInfo> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<QuanLyKhachSan.TKDoanhThuDichVuSVC.TKDoanhThuDichVuInfo>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HoaDonDichVu_GetItems_TheoThangCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public HoaDonDichVu_GetItems_TheoThangCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<QuanLyKhachSan.TKDoanhThuDichVuSVC.TKDoanhThuDichVuInfo> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<QuanLyKhachSan.TKDoanhThuDichVuSVC.TKDoanhThuDichVuInfo>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HoaDonDichVu_GetItems_TheoNamCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public HoaDonDichVu_GetItems_TheoNamCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<QuanLyKhachSan.TKDoanhThuDichVuSVC.TKDoanhThuDichVuInfo> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<QuanLyKhachSan.TKDoanhThuDichVuSVC.TKDoanhThuDichVuInfo>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HoaDonDichVu_GetItems_TuNgayDenNgayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public HoaDonDichVu_GetItems_TuNgayDenNgayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<QuanLyKhachSan.TKDoanhThuDichVuSVC.TKDoanhThuDichVuInfo> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<QuanLyKhachSan.TKDoanhThuDichVuSVC.TKDoanhThuDichVuInfo>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TKDoanhThuDichVuSVCClient : System.ServiceModel.ClientBase<QuanLyKhachSan.TKDoanhThuDichVuSVC.TKDoanhThuDichVuSVC>, QuanLyKhachSan.TKDoanhThuDichVuSVC.TKDoanhThuDichVuSVC {
        
        private BeginOperationDelegate onBeginHoaDonDichVu_GetItems_TheoNgayDelegate;
        
        private EndOperationDelegate onEndHoaDonDichVu_GetItems_TheoNgayDelegate;
        
        private System.Threading.SendOrPostCallback onHoaDonDichVu_GetItems_TheoNgayCompletedDelegate;
        
        private BeginOperationDelegate onBeginHoaDonDichVu_GetItems_TheoThangDelegate;
        
        private EndOperationDelegate onEndHoaDonDichVu_GetItems_TheoThangDelegate;
        
        private System.Threading.SendOrPostCallback onHoaDonDichVu_GetItems_TheoThangCompletedDelegate;
        
        private BeginOperationDelegate onBeginHoaDonDichVu_GetItems_TheoNamDelegate;
        
        private EndOperationDelegate onEndHoaDonDichVu_GetItems_TheoNamDelegate;
        
        private System.Threading.SendOrPostCallback onHoaDonDichVu_GetItems_TheoNamCompletedDelegate;
        
        private BeginOperationDelegate onBeginHoaDonDichVu_GetItems_TuNgayDenNgayDelegate;
        
        private EndOperationDelegate onEndHoaDonDichVu_GetItems_TuNgayDenNgayDelegate;
        
        private System.Threading.SendOrPostCallback onHoaDonDichVu_GetItems_TuNgayDenNgayCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public TKDoanhThuDichVuSVCClient() {
        }
        
        public TKDoanhThuDichVuSVCClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TKDoanhThuDichVuSVCClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TKDoanhThuDichVuSVCClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TKDoanhThuDichVuSVCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<HoaDonDichVu_GetItems_TheoNgayCompletedEventArgs> HoaDonDichVu_GetItems_TheoNgayCompleted;
        
        public event System.EventHandler<HoaDonDichVu_GetItems_TheoThangCompletedEventArgs> HoaDonDichVu_GetItems_TheoThangCompleted;
        
        public event System.EventHandler<HoaDonDichVu_GetItems_TheoNamCompletedEventArgs> HoaDonDichVu_GetItems_TheoNamCompleted;
        
        public event System.EventHandler<HoaDonDichVu_GetItems_TuNgayDenNgayCompletedEventArgs> HoaDonDichVu_GetItems_TuNgayDenNgayCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QuanLyKhachSan.TKDoanhThuDichVuSVC.TKDoanhThuDichVuSVC.BeginHoaDonDichVu_GetItems_TheoNgay(int NgaySo, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginHoaDonDichVu_GetItems_TheoNgay(NgaySo, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<QuanLyKhachSan.TKDoanhThuDichVuSVC.TKDoanhThuDichVuInfo> QuanLyKhachSan.TKDoanhThuDichVuSVC.TKDoanhThuDichVuSVC.EndHoaDonDichVu_GetItems_TheoNgay(System.IAsyncResult result) {
            return base.Channel.EndHoaDonDichVu_GetItems_TheoNgay(result);
        }
        
        private System.IAsyncResult OnBeginHoaDonDichVu_GetItems_TheoNgay(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int NgaySo = ((int)(inValues[0]));
            return ((QuanLyKhachSan.TKDoanhThuDichVuSVC.TKDoanhThuDichVuSVC)(this)).BeginHoaDonDichVu_GetItems_TheoNgay(NgaySo, callback, asyncState);
        }
        
        private object[] OnEndHoaDonDichVu_GetItems_TheoNgay(System.IAsyncResult result) {
            System.Collections.Generic.List<QuanLyKhachSan.TKDoanhThuDichVuSVC.TKDoanhThuDichVuInfo> retVal = ((QuanLyKhachSan.TKDoanhThuDichVuSVC.TKDoanhThuDichVuSVC)(this)).EndHoaDonDichVu_GetItems_TheoNgay(result);
            return new object[] {
                    retVal};
        }
        
        private void OnHoaDonDichVu_GetItems_TheoNgayCompleted(object state) {
            if ((this.HoaDonDichVu_GetItems_TheoNgayCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.HoaDonDichVu_GetItems_TheoNgayCompleted(this, new HoaDonDichVu_GetItems_TheoNgayCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void HoaDonDichVu_GetItems_TheoNgayAsync(int NgaySo) {
            this.HoaDonDichVu_GetItems_TheoNgayAsync(NgaySo, null);
        }
        
        public void HoaDonDichVu_GetItems_TheoNgayAsync(int NgaySo, object userState) {
            if ((this.onBeginHoaDonDichVu_GetItems_TheoNgayDelegate == null)) {
                this.onBeginHoaDonDichVu_GetItems_TheoNgayDelegate = new BeginOperationDelegate(this.OnBeginHoaDonDichVu_GetItems_TheoNgay);
            }
            if ((this.onEndHoaDonDichVu_GetItems_TheoNgayDelegate == null)) {
                this.onEndHoaDonDichVu_GetItems_TheoNgayDelegate = new EndOperationDelegate(this.OnEndHoaDonDichVu_GetItems_TheoNgay);
            }
            if ((this.onHoaDonDichVu_GetItems_TheoNgayCompletedDelegate == null)) {
                this.onHoaDonDichVu_GetItems_TheoNgayCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHoaDonDichVu_GetItems_TheoNgayCompleted);
            }
            base.InvokeAsync(this.onBeginHoaDonDichVu_GetItems_TheoNgayDelegate, new object[] {
                        NgaySo}, this.onEndHoaDonDichVu_GetItems_TheoNgayDelegate, this.onHoaDonDichVu_GetItems_TheoNgayCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QuanLyKhachSan.TKDoanhThuDichVuSVC.TKDoanhThuDichVuSVC.BeginHoaDonDichVu_GetItems_TheoThang(int Thang, int Nam, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginHoaDonDichVu_GetItems_TheoThang(Thang, Nam, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<QuanLyKhachSan.TKDoanhThuDichVuSVC.TKDoanhThuDichVuInfo> QuanLyKhachSan.TKDoanhThuDichVuSVC.TKDoanhThuDichVuSVC.EndHoaDonDichVu_GetItems_TheoThang(System.IAsyncResult result) {
            return base.Channel.EndHoaDonDichVu_GetItems_TheoThang(result);
        }
        
        private System.IAsyncResult OnBeginHoaDonDichVu_GetItems_TheoThang(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int Thang = ((int)(inValues[0]));
            int Nam = ((int)(inValues[1]));
            return ((QuanLyKhachSan.TKDoanhThuDichVuSVC.TKDoanhThuDichVuSVC)(this)).BeginHoaDonDichVu_GetItems_TheoThang(Thang, Nam, callback, asyncState);
        }
        
        private object[] OnEndHoaDonDichVu_GetItems_TheoThang(System.IAsyncResult result) {
            System.Collections.Generic.List<QuanLyKhachSan.TKDoanhThuDichVuSVC.TKDoanhThuDichVuInfo> retVal = ((QuanLyKhachSan.TKDoanhThuDichVuSVC.TKDoanhThuDichVuSVC)(this)).EndHoaDonDichVu_GetItems_TheoThang(result);
            return new object[] {
                    retVal};
        }
        
        private void OnHoaDonDichVu_GetItems_TheoThangCompleted(object state) {
            if ((this.HoaDonDichVu_GetItems_TheoThangCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.HoaDonDichVu_GetItems_TheoThangCompleted(this, new HoaDonDichVu_GetItems_TheoThangCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void HoaDonDichVu_GetItems_TheoThangAsync(int Thang, int Nam) {
            this.HoaDonDichVu_GetItems_TheoThangAsync(Thang, Nam, null);
        }
        
        public void HoaDonDichVu_GetItems_TheoThangAsync(int Thang, int Nam, object userState) {
            if ((this.onBeginHoaDonDichVu_GetItems_TheoThangDelegate == null)) {
                this.onBeginHoaDonDichVu_GetItems_TheoThangDelegate = new BeginOperationDelegate(this.OnBeginHoaDonDichVu_GetItems_TheoThang);
            }
            if ((this.onEndHoaDonDichVu_GetItems_TheoThangDelegate == null)) {
                this.onEndHoaDonDichVu_GetItems_TheoThangDelegate = new EndOperationDelegate(this.OnEndHoaDonDichVu_GetItems_TheoThang);
            }
            if ((this.onHoaDonDichVu_GetItems_TheoThangCompletedDelegate == null)) {
                this.onHoaDonDichVu_GetItems_TheoThangCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHoaDonDichVu_GetItems_TheoThangCompleted);
            }
            base.InvokeAsync(this.onBeginHoaDonDichVu_GetItems_TheoThangDelegate, new object[] {
                        Thang,
                        Nam}, this.onEndHoaDonDichVu_GetItems_TheoThangDelegate, this.onHoaDonDichVu_GetItems_TheoThangCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QuanLyKhachSan.TKDoanhThuDichVuSVC.TKDoanhThuDichVuSVC.BeginHoaDonDichVu_GetItems_TheoNam(int Nam, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginHoaDonDichVu_GetItems_TheoNam(Nam, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<QuanLyKhachSan.TKDoanhThuDichVuSVC.TKDoanhThuDichVuInfo> QuanLyKhachSan.TKDoanhThuDichVuSVC.TKDoanhThuDichVuSVC.EndHoaDonDichVu_GetItems_TheoNam(System.IAsyncResult result) {
            return base.Channel.EndHoaDonDichVu_GetItems_TheoNam(result);
        }
        
        private System.IAsyncResult OnBeginHoaDonDichVu_GetItems_TheoNam(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int Nam = ((int)(inValues[0]));
            return ((QuanLyKhachSan.TKDoanhThuDichVuSVC.TKDoanhThuDichVuSVC)(this)).BeginHoaDonDichVu_GetItems_TheoNam(Nam, callback, asyncState);
        }
        
        private object[] OnEndHoaDonDichVu_GetItems_TheoNam(System.IAsyncResult result) {
            System.Collections.Generic.List<QuanLyKhachSan.TKDoanhThuDichVuSVC.TKDoanhThuDichVuInfo> retVal = ((QuanLyKhachSan.TKDoanhThuDichVuSVC.TKDoanhThuDichVuSVC)(this)).EndHoaDonDichVu_GetItems_TheoNam(result);
            return new object[] {
                    retVal};
        }
        
        private void OnHoaDonDichVu_GetItems_TheoNamCompleted(object state) {
            if ((this.HoaDonDichVu_GetItems_TheoNamCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.HoaDonDichVu_GetItems_TheoNamCompleted(this, new HoaDonDichVu_GetItems_TheoNamCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void HoaDonDichVu_GetItems_TheoNamAsync(int Nam) {
            this.HoaDonDichVu_GetItems_TheoNamAsync(Nam, null);
        }
        
        public void HoaDonDichVu_GetItems_TheoNamAsync(int Nam, object userState) {
            if ((this.onBeginHoaDonDichVu_GetItems_TheoNamDelegate == null)) {
                this.onBeginHoaDonDichVu_GetItems_TheoNamDelegate = new BeginOperationDelegate(this.OnBeginHoaDonDichVu_GetItems_TheoNam);
            }
            if ((this.onEndHoaDonDichVu_GetItems_TheoNamDelegate == null)) {
                this.onEndHoaDonDichVu_GetItems_TheoNamDelegate = new EndOperationDelegate(this.OnEndHoaDonDichVu_GetItems_TheoNam);
            }
            if ((this.onHoaDonDichVu_GetItems_TheoNamCompletedDelegate == null)) {
                this.onHoaDonDichVu_GetItems_TheoNamCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHoaDonDichVu_GetItems_TheoNamCompleted);
            }
            base.InvokeAsync(this.onBeginHoaDonDichVu_GetItems_TheoNamDelegate, new object[] {
                        Nam}, this.onEndHoaDonDichVu_GetItems_TheoNamDelegate, this.onHoaDonDichVu_GetItems_TheoNamCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QuanLyKhachSan.TKDoanhThuDichVuSVC.TKDoanhThuDichVuSVC.BeginHoaDonDichVu_GetItems_TuNgayDenNgay(int TuNgaySo, int DenNgaySo, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginHoaDonDichVu_GetItems_TuNgayDenNgay(TuNgaySo, DenNgaySo, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<QuanLyKhachSan.TKDoanhThuDichVuSVC.TKDoanhThuDichVuInfo> QuanLyKhachSan.TKDoanhThuDichVuSVC.TKDoanhThuDichVuSVC.EndHoaDonDichVu_GetItems_TuNgayDenNgay(System.IAsyncResult result) {
            return base.Channel.EndHoaDonDichVu_GetItems_TuNgayDenNgay(result);
        }
        
        private System.IAsyncResult OnBeginHoaDonDichVu_GetItems_TuNgayDenNgay(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int TuNgaySo = ((int)(inValues[0]));
            int DenNgaySo = ((int)(inValues[1]));
            return ((QuanLyKhachSan.TKDoanhThuDichVuSVC.TKDoanhThuDichVuSVC)(this)).BeginHoaDonDichVu_GetItems_TuNgayDenNgay(TuNgaySo, DenNgaySo, callback, asyncState);
        }
        
        private object[] OnEndHoaDonDichVu_GetItems_TuNgayDenNgay(System.IAsyncResult result) {
            System.Collections.Generic.List<QuanLyKhachSan.TKDoanhThuDichVuSVC.TKDoanhThuDichVuInfo> retVal = ((QuanLyKhachSan.TKDoanhThuDichVuSVC.TKDoanhThuDichVuSVC)(this)).EndHoaDonDichVu_GetItems_TuNgayDenNgay(result);
            return new object[] {
                    retVal};
        }
        
        private void OnHoaDonDichVu_GetItems_TuNgayDenNgayCompleted(object state) {
            if ((this.HoaDonDichVu_GetItems_TuNgayDenNgayCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.HoaDonDichVu_GetItems_TuNgayDenNgayCompleted(this, new HoaDonDichVu_GetItems_TuNgayDenNgayCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void HoaDonDichVu_GetItems_TuNgayDenNgayAsync(int TuNgaySo, int DenNgaySo) {
            this.HoaDonDichVu_GetItems_TuNgayDenNgayAsync(TuNgaySo, DenNgaySo, null);
        }
        
        public void HoaDonDichVu_GetItems_TuNgayDenNgayAsync(int TuNgaySo, int DenNgaySo, object userState) {
            if ((this.onBeginHoaDonDichVu_GetItems_TuNgayDenNgayDelegate == null)) {
                this.onBeginHoaDonDichVu_GetItems_TuNgayDenNgayDelegate = new BeginOperationDelegate(this.OnBeginHoaDonDichVu_GetItems_TuNgayDenNgay);
            }
            if ((this.onEndHoaDonDichVu_GetItems_TuNgayDenNgayDelegate == null)) {
                this.onEndHoaDonDichVu_GetItems_TuNgayDenNgayDelegate = new EndOperationDelegate(this.OnEndHoaDonDichVu_GetItems_TuNgayDenNgay);
            }
            if ((this.onHoaDonDichVu_GetItems_TuNgayDenNgayCompletedDelegate == null)) {
                this.onHoaDonDichVu_GetItems_TuNgayDenNgayCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHoaDonDichVu_GetItems_TuNgayDenNgayCompleted);
            }
            base.InvokeAsync(this.onBeginHoaDonDichVu_GetItems_TuNgayDenNgayDelegate, new object[] {
                        TuNgaySo,
                        DenNgaySo}, this.onEndHoaDonDichVu_GetItems_TuNgayDenNgayDelegate, this.onHoaDonDichVu_GetItems_TuNgayDenNgayCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override QuanLyKhachSan.TKDoanhThuDichVuSVC.TKDoanhThuDichVuSVC CreateChannel() {
            return new TKDoanhThuDichVuSVCClientChannel(this);
        }
        
        private class TKDoanhThuDichVuSVCClientChannel : ChannelBase<QuanLyKhachSan.TKDoanhThuDichVuSVC.TKDoanhThuDichVuSVC>, QuanLyKhachSan.TKDoanhThuDichVuSVC.TKDoanhThuDichVuSVC {
            
            public TKDoanhThuDichVuSVCClientChannel(System.ServiceModel.ClientBase<QuanLyKhachSan.TKDoanhThuDichVuSVC.TKDoanhThuDichVuSVC> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginHoaDonDichVu_GetItems_TheoNgay(int NgaySo, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = NgaySo;
                System.IAsyncResult _result = base.BeginInvoke("HoaDonDichVu_GetItems_TheoNgay", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<QuanLyKhachSan.TKDoanhThuDichVuSVC.TKDoanhThuDichVuInfo> EndHoaDonDichVu_GetItems_TheoNgay(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<QuanLyKhachSan.TKDoanhThuDichVuSVC.TKDoanhThuDichVuInfo> _result = ((System.Collections.Generic.List<QuanLyKhachSan.TKDoanhThuDichVuSVC.TKDoanhThuDichVuInfo>)(base.EndInvoke("HoaDonDichVu_GetItems_TheoNgay", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginHoaDonDichVu_GetItems_TheoThang(int Thang, int Nam, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = Thang;
                _args[1] = Nam;
                System.IAsyncResult _result = base.BeginInvoke("HoaDonDichVu_GetItems_TheoThang", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<QuanLyKhachSan.TKDoanhThuDichVuSVC.TKDoanhThuDichVuInfo> EndHoaDonDichVu_GetItems_TheoThang(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<QuanLyKhachSan.TKDoanhThuDichVuSVC.TKDoanhThuDichVuInfo> _result = ((System.Collections.Generic.List<QuanLyKhachSan.TKDoanhThuDichVuSVC.TKDoanhThuDichVuInfo>)(base.EndInvoke("HoaDonDichVu_GetItems_TheoThang", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginHoaDonDichVu_GetItems_TheoNam(int Nam, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = Nam;
                System.IAsyncResult _result = base.BeginInvoke("HoaDonDichVu_GetItems_TheoNam", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<QuanLyKhachSan.TKDoanhThuDichVuSVC.TKDoanhThuDichVuInfo> EndHoaDonDichVu_GetItems_TheoNam(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<QuanLyKhachSan.TKDoanhThuDichVuSVC.TKDoanhThuDichVuInfo> _result = ((System.Collections.Generic.List<QuanLyKhachSan.TKDoanhThuDichVuSVC.TKDoanhThuDichVuInfo>)(base.EndInvoke("HoaDonDichVu_GetItems_TheoNam", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginHoaDonDichVu_GetItems_TuNgayDenNgay(int TuNgaySo, int DenNgaySo, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = TuNgaySo;
                _args[1] = DenNgaySo;
                System.IAsyncResult _result = base.BeginInvoke("HoaDonDichVu_GetItems_TuNgayDenNgay", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<QuanLyKhachSan.TKDoanhThuDichVuSVC.TKDoanhThuDichVuInfo> EndHoaDonDichVu_GetItems_TuNgayDenNgay(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<QuanLyKhachSan.TKDoanhThuDichVuSVC.TKDoanhThuDichVuInfo> _result = ((System.Collections.Generic.List<QuanLyKhachSan.TKDoanhThuDichVuSVC.TKDoanhThuDichVuInfo>)(base.EndInvoke("HoaDonDichVu_GetItems_TuNgayDenNgay", _args, result)));
                return _result;
            }
        }
    }
}
