//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
// 
namespace QuanLyKhachSan.GroupSVC {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GroupInfo", Namespace="http://schemas.datacontract.org/2004/07/QuanLyKhachSan")]
    public partial class GroupInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int CreatedByUserField;
        
        private string CreatedDateField;
        
        private string DescriptionsField;
        
        private int GroupIDField;
        
        private string GroupNameField;
        
        private int IsActivedField;
        
        private int ModifiedByUserField;
        
        private string ModifiedDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CreatedByUser {
            get {
                return this.CreatedByUserField;
            }
            set {
                if ((this.CreatedByUserField.Equals(value) != true)) {
                    this.CreatedByUserField = value;
                    this.RaisePropertyChanged("CreatedByUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedDateField, value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descriptions {
            get {
                return this.DescriptionsField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionsField, value) != true)) {
                    this.DescriptionsField = value;
                    this.RaisePropertyChanged("Descriptions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GroupID {
            get {
                return this.GroupIDField;
            }
            set {
                if ((this.GroupIDField.Equals(value) != true)) {
                    this.GroupIDField = value;
                    this.RaisePropertyChanged("GroupID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupName {
            get {
                return this.GroupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupNameField, value) != true)) {
                    this.GroupNameField = value;
                    this.RaisePropertyChanged("GroupName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IsActived {
            get {
                return this.IsActivedField;
            }
            set {
                if ((this.IsActivedField.Equals(value) != true)) {
                    this.IsActivedField = value;
                    this.RaisePropertyChanged("IsActived");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ModifiedByUser {
            get {
                return this.ModifiedByUserField;
            }
            set {
                if ((this.ModifiedByUserField.Equals(value) != true)) {
                    this.ModifiedByUserField = value;
                    this.RaisePropertyChanged("ModifiedByUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ModifiedDateField, value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="GroupSVC.GroupSVC")]
    public interface GroupSVC {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:GroupSVC/Group_Add", ReplyAction="urn:GroupSVC/Group_AddResponse")]
        System.IAsyncResult BeginGroup_Add(string GroupName, string Descriptions, int IsActived, int CreatedByUser, string CreatedDate, System.AsyncCallback callback, object asyncState);
        
        void EndGroup_Add(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:GroupSVC/Group_Edit", ReplyAction="urn:GroupSVC/Group_EditResponse")]
        System.IAsyncResult BeginGroup_Edit(int GroupID, string GroupName, string Descriptions, int IsActived, int ModifiedByUser, string ModifiedDate, System.AsyncCallback callback, object asyncState);
        
        void EndGroup_Edit(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:GroupSVC/Group_Delete", ReplyAction="urn:GroupSVC/Group_DeleteResponse")]
        System.IAsyncResult BeginGroup_Delete(int GroupID, System.AsyncCallback callback, object asyncState);
        
        void EndGroup_Delete(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:GroupSVC/Group_GetItem", ReplyAction="urn:GroupSVC/Group_GetItemResponse")]
        System.IAsyncResult BeginGroup_GetItem(int GroupID, System.AsyncCallback callback, object asyncState);
        
        QuanLyKhachSan.GroupSVC.GroupInfo EndGroup_GetItem(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:GroupSVC/Group_GetItems", ReplyAction="urn:GroupSVC/Group_GetItemsResponse")]
        System.IAsyncResult BeginGroup_GetItems(System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<QuanLyKhachSan.GroupSVC.GroupInfo> EndGroup_GetItems(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:GroupSVC/Group_GetActivedItems", ReplyAction="urn:GroupSVC/Group_GetActivedItemsResponse")]
        System.IAsyncResult BeginGroup_GetActivedItems(System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<QuanLyKhachSan.GroupSVC.GroupInfo> EndGroup_GetActivedItems(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GroupSVCChannel : QuanLyKhachSan.GroupSVC.GroupSVC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Group_GetItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public Group_GetItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public QuanLyKhachSan.GroupSVC.GroupInfo Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((QuanLyKhachSan.GroupSVC.GroupInfo)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Group_GetItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public Group_GetItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<QuanLyKhachSan.GroupSVC.GroupInfo> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<QuanLyKhachSan.GroupSVC.GroupInfo>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Group_GetActivedItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public Group_GetActivedItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<QuanLyKhachSan.GroupSVC.GroupInfo> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<QuanLyKhachSan.GroupSVC.GroupInfo>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GroupSVCClient : System.ServiceModel.ClientBase<QuanLyKhachSan.GroupSVC.GroupSVC>, QuanLyKhachSan.GroupSVC.GroupSVC {
        
        private BeginOperationDelegate onBeginGroup_AddDelegate;
        
        private EndOperationDelegate onEndGroup_AddDelegate;
        
        private System.Threading.SendOrPostCallback onGroup_AddCompletedDelegate;
        
        private BeginOperationDelegate onBeginGroup_EditDelegate;
        
        private EndOperationDelegate onEndGroup_EditDelegate;
        
        private System.Threading.SendOrPostCallback onGroup_EditCompletedDelegate;
        
        private BeginOperationDelegate onBeginGroup_DeleteDelegate;
        
        private EndOperationDelegate onEndGroup_DeleteDelegate;
        
        private System.Threading.SendOrPostCallback onGroup_DeleteCompletedDelegate;
        
        private BeginOperationDelegate onBeginGroup_GetItemDelegate;
        
        private EndOperationDelegate onEndGroup_GetItemDelegate;
        
        private System.Threading.SendOrPostCallback onGroup_GetItemCompletedDelegate;
        
        private BeginOperationDelegate onBeginGroup_GetItemsDelegate;
        
        private EndOperationDelegate onEndGroup_GetItemsDelegate;
        
        private System.Threading.SendOrPostCallback onGroup_GetItemsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGroup_GetActivedItemsDelegate;
        
        private EndOperationDelegate onEndGroup_GetActivedItemsDelegate;
        
        private System.Threading.SendOrPostCallback onGroup_GetActivedItemsCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public GroupSVCClient() {
        }
        
        public GroupSVCClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GroupSVCClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GroupSVCClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GroupSVCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> Group_AddCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> Group_EditCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> Group_DeleteCompleted;
        
        public event System.EventHandler<Group_GetItemCompletedEventArgs> Group_GetItemCompleted;
        
        public event System.EventHandler<Group_GetItemsCompletedEventArgs> Group_GetItemsCompleted;
        
        public event System.EventHandler<Group_GetActivedItemsCompletedEventArgs> Group_GetActivedItemsCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QuanLyKhachSan.GroupSVC.GroupSVC.BeginGroup_Add(string GroupName, string Descriptions, int IsActived, int CreatedByUser, string CreatedDate, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGroup_Add(GroupName, Descriptions, IsActived, CreatedByUser, CreatedDate, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void QuanLyKhachSan.GroupSVC.GroupSVC.EndGroup_Add(System.IAsyncResult result) {
            base.Channel.EndGroup_Add(result);
        }
        
        private System.IAsyncResult OnBeginGroup_Add(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string GroupName = ((string)(inValues[0]));
            string Descriptions = ((string)(inValues[1]));
            int IsActived = ((int)(inValues[2]));
            int CreatedByUser = ((int)(inValues[3]));
            string CreatedDate = ((string)(inValues[4]));
            return ((QuanLyKhachSan.GroupSVC.GroupSVC)(this)).BeginGroup_Add(GroupName, Descriptions, IsActived, CreatedByUser, CreatedDate, callback, asyncState);
        }
        
        private object[] OnEndGroup_Add(System.IAsyncResult result) {
            ((QuanLyKhachSan.GroupSVC.GroupSVC)(this)).EndGroup_Add(result);
            return null;
        }
        
        private void OnGroup_AddCompleted(object state) {
            if ((this.Group_AddCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.Group_AddCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void Group_AddAsync(string GroupName, string Descriptions, int IsActived, int CreatedByUser, string CreatedDate) {
            this.Group_AddAsync(GroupName, Descriptions, IsActived, CreatedByUser, CreatedDate, null);
        }
        
        public void Group_AddAsync(string GroupName, string Descriptions, int IsActived, int CreatedByUser, string CreatedDate, object userState) {
            if ((this.onBeginGroup_AddDelegate == null)) {
                this.onBeginGroup_AddDelegate = new BeginOperationDelegate(this.OnBeginGroup_Add);
            }
            if ((this.onEndGroup_AddDelegate == null)) {
                this.onEndGroup_AddDelegate = new EndOperationDelegate(this.OnEndGroup_Add);
            }
            if ((this.onGroup_AddCompletedDelegate == null)) {
                this.onGroup_AddCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGroup_AddCompleted);
            }
            base.InvokeAsync(this.onBeginGroup_AddDelegate, new object[] {
                        GroupName,
                        Descriptions,
                        IsActived,
                        CreatedByUser,
                        CreatedDate}, this.onEndGroup_AddDelegate, this.onGroup_AddCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QuanLyKhachSan.GroupSVC.GroupSVC.BeginGroup_Edit(int GroupID, string GroupName, string Descriptions, int IsActived, int ModifiedByUser, string ModifiedDate, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGroup_Edit(GroupID, GroupName, Descriptions, IsActived, ModifiedByUser, ModifiedDate, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void QuanLyKhachSan.GroupSVC.GroupSVC.EndGroup_Edit(System.IAsyncResult result) {
            base.Channel.EndGroup_Edit(result);
        }
        
        private System.IAsyncResult OnBeginGroup_Edit(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int GroupID = ((int)(inValues[0]));
            string GroupName = ((string)(inValues[1]));
            string Descriptions = ((string)(inValues[2]));
            int IsActived = ((int)(inValues[3]));
            int ModifiedByUser = ((int)(inValues[4]));
            string ModifiedDate = ((string)(inValues[5]));
            return ((QuanLyKhachSan.GroupSVC.GroupSVC)(this)).BeginGroup_Edit(GroupID, GroupName, Descriptions, IsActived, ModifiedByUser, ModifiedDate, callback, asyncState);
        }
        
        private object[] OnEndGroup_Edit(System.IAsyncResult result) {
            ((QuanLyKhachSan.GroupSVC.GroupSVC)(this)).EndGroup_Edit(result);
            return null;
        }
        
        private void OnGroup_EditCompleted(object state) {
            if ((this.Group_EditCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.Group_EditCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void Group_EditAsync(int GroupID, string GroupName, string Descriptions, int IsActived, int ModifiedByUser, string ModifiedDate) {
            this.Group_EditAsync(GroupID, GroupName, Descriptions, IsActived, ModifiedByUser, ModifiedDate, null);
        }
        
        public void Group_EditAsync(int GroupID, string GroupName, string Descriptions, int IsActived, int ModifiedByUser, string ModifiedDate, object userState) {
            if ((this.onBeginGroup_EditDelegate == null)) {
                this.onBeginGroup_EditDelegate = new BeginOperationDelegate(this.OnBeginGroup_Edit);
            }
            if ((this.onEndGroup_EditDelegate == null)) {
                this.onEndGroup_EditDelegate = new EndOperationDelegate(this.OnEndGroup_Edit);
            }
            if ((this.onGroup_EditCompletedDelegate == null)) {
                this.onGroup_EditCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGroup_EditCompleted);
            }
            base.InvokeAsync(this.onBeginGroup_EditDelegate, new object[] {
                        GroupID,
                        GroupName,
                        Descriptions,
                        IsActived,
                        ModifiedByUser,
                        ModifiedDate}, this.onEndGroup_EditDelegate, this.onGroup_EditCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QuanLyKhachSan.GroupSVC.GroupSVC.BeginGroup_Delete(int GroupID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGroup_Delete(GroupID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void QuanLyKhachSan.GroupSVC.GroupSVC.EndGroup_Delete(System.IAsyncResult result) {
            base.Channel.EndGroup_Delete(result);
        }
        
        private System.IAsyncResult OnBeginGroup_Delete(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int GroupID = ((int)(inValues[0]));
            return ((QuanLyKhachSan.GroupSVC.GroupSVC)(this)).BeginGroup_Delete(GroupID, callback, asyncState);
        }
        
        private object[] OnEndGroup_Delete(System.IAsyncResult result) {
            ((QuanLyKhachSan.GroupSVC.GroupSVC)(this)).EndGroup_Delete(result);
            return null;
        }
        
        private void OnGroup_DeleteCompleted(object state) {
            if ((this.Group_DeleteCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.Group_DeleteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void Group_DeleteAsync(int GroupID) {
            this.Group_DeleteAsync(GroupID, null);
        }
        
        public void Group_DeleteAsync(int GroupID, object userState) {
            if ((this.onBeginGroup_DeleteDelegate == null)) {
                this.onBeginGroup_DeleteDelegate = new BeginOperationDelegate(this.OnBeginGroup_Delete);
            }
            if ((this.onEndGroup_DeleteDelegate == null)) {
                this.onEndGroup_DeleteDelegate = new EndOperationDelegate(this.OnEndGroup_Delete);
            }
            if ((this.onGroup_DeleteCompletedDelegate == null)) {
                this.onGroup_DeleteCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGroup_DeleteCompleted);
            }
            base.InvokeAsync(this.onBeginGroup_DeleteDelegate, new object[] {
                        GroupID}, this.onEndGroup_DeleteDelegate, this.onGroup_DeleteCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QuanLyKhachSan.GroupSVC.GroupSVC.BeginGroup_GetItem(int GroupID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGroup_GetItem(GroupID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuanLyKhachSan.GroupSVC.GroupInfo QuanLyKhachSan.GroupSVC.GroupSVC.EndGroup_GetItem(System.IAsyncResult result) {
            return base.Channel.EndGroup_GetItem(result);
        }
        
        private System.IAsyncResult OnBeginGroup_GetItem(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int GroupID = ((int)(inValues[0]));
            return ((QuanLyKhachSan.GroupSVC.GroupSVC)(this)).BeginGroup_GetItem(GroupID, callback, asyncState);
        }
        
        private object[] OnEndGroup_GetItem(System.IAsyncResult result) {
            QuanLyKhachSan.GroupSVC.GroupInfo retVal = ((QuanLyKhachSan.GroupSVC.GroupSVC)(this)).EndGroup_GetItem(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGroup_GetItemCompleted(object state) {
            if ((this.Group_GetItemCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.Group_GetItemCompleted(this, new Group_GetItemCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void Group_GetItemAsync(int GroupID) {
            this.Group_GetItemAsync(GroupID, null);
        }
        
        public void Group_GetItemAsync(int GroupID, object userState) {
            if ((this.onBeginGroup_GetItemDelegate == null)) {
                this.onBeginGroup_GetItemDelegate = new BeginOperationDelegate(this.OnBeginGroup_GetItem);
            }
            if ((this.onEndGroup_GetItemDelegate == null)) {
                this.onEndGroup_GetItemDelegate = new EndOperationDelegate(this.OnEndGroup_GetItem);
            }
            if ((this.onGroup_GetItemCompletedDelegate == null)) {
                this.onGroup_GetItemCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGroup_GetItemCompleted);
            }
            base.InvokeAsync(this.onBeginGroup_GetItemDelegate, new object[] {
                        GroupID}, this.onEndGroup_GetItemDelegate, this.onGroup_GetItemCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QuanLyKhachSan.GroupSVC.GroupSVC.BeginGroup_GetItems(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGroup_GetItems(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<QuanLyKhachSan.GroupSVC.GroupInfo> QuanLyKhachSan.GroupSVC.GroupSVC.EndGroup_GetItems(System.IAsyncResult result) {
            return base.Channel.EndGroup_GetItems(result);
        }
        
        private System.IAsyncResult OnBeginGroup_GetItems(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((QuanLyKhachSan.GroupSVC.GroupSVC)(this)).BeginGroup_GetItems(callback, asyncState);
        }
        
        private object[] OnEndGroup_GetItems(System.IAsyncResult result) {
            System.Collections.Generic.List<QuanLyKhachSan.GroupSVC.GroupInfo> retVal = ((QuanLyKhachSan.GroupSVC.GroupSVC)(this)).EndGroup_GetItems(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGroup_GetItemsCompleted(object state) {
            if ((this.Group_GetItemsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.Group_GetItemsCompleted(this, new Group_GetItemsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void Group_GetItemsAsync() {
            this.Group_GetItemsAsync(null);
        }
        
        public void Group_GetItemsAsync(object userState) {
            if ((this.onBeginGroup_GetItemsDelegate == null)) {
                this.onBeginGroup_GetItemsDelegate = new BeginOperationDelegate(this.OnBeginGroup_GetItems);
            }
            if ((this.onEndGroup_GetItemsDelegate == null)) {
                this.onEndGroup_GetItemsDelegate = new EndOperationDelegate(this.OnEndGroup_GetItems);
            }
            if ((this.onGroup_GetItemsCompletedDelegate == null)) {
                this.onGroup_GetItemsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGroup_GetItemsCompleted);
            }
            base.InvokeAsync(this.onBeginGroup_GetItemsDelegate, null, this.onEndGroup_GetItemsDelegate, this.onGroup_GetItemsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QuanLyKhachSan.GroupSVC.GroupSVC.BeginGroup_GetActivedItems(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGroup_GetActivedItems(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<QuanLyKhachSan.GroupSVC.GroupInfo> QuanLyKhachSan.GroupSVC.GroupSVC.EndGroup_GetActivedItems(System.IAsyncResult result) {
            return base.Channel.EndGroup_GetActivedItems(result);
        }
        
        private System.IAsyncResult OnBeginGroup_GetActivedItems(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((QuanLyKhachSan.GroupSVC.GroupSVC)(this)).BeginGroup_GetActivedItems(callback, asyncState);
        }
        
        private object[] OnEndGroup_GetActivedItems(System.IAsyncResult result) {
            System.Collections.Generic.List<QuanLyKhachSan.GroupSVC.GroupInfo> retVal = ((QuanLyKhachSan.GroupSVC.GroupSVC)(this)).EndGroup_GetActivedItems(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGroup_GetActivedItemsCompleted(object state) {
            if ((this.Group_GetActivedItemsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.Group_GetActivedItemsCompleted(this, new Group_GetActivedItemsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void Group_GetActivedItemsAsync() {
            this.Group_GetActivedItemsAsync(null);
        }
        
        public void Group_GetActivedItemsAsync(object userState) {
            if ((this.onBeginGroup_GetActivedItemsDelegate == null)) {
                this.onBeginGroup_GetActivedItemsDelegate = new BeginOperationDelegate(this.OnBeginGroup_GetActivedItems);
            }
            if ((this.onEndGroup_GetActivedItemsDelegate == null)) {
                this.onEndGroup_GetActivedItemsDelegate = new EndOperationDelegate(this.OnEndGroup_GetActivedItems);
            }
            if ((this.onGroup_GetActivedItemsCompletedDelegate == null)) {
                this.onGroup_GetActivedItemsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGroup_GetActivedItemsCompleted);
            }
            base.InvokeAsync(this.onBeginGroup_GetActivedItemsDelegate, null, this.onEndGroup_GetActivedItemsDelegate, this.onGroup_GetActivedItemsCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override QuanLyKhachSan.GroupSVC.GroupSVC CreateChannel() {
            return new GroupSVCClientChannel(this);
        }
        
        private class GroupSVCClientChannel : ChannelBase<QuanLyKhachSan.GroupSVC.GroupSVC>, QuanLyKhachSan.GroupSVC.GroupSVC {
            
            public GroupSVCClientChannel(System.ServiceModel.ClientBase<QuanLyKhachSan.GroupSVC.GroupSVC> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGroup_Add(string GroupName, string Descriptions, int IsActived, int CreatedByUser, string CreatedDate, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[5];
                _args[0] = GroupName;
                _args[1] = Descriptions;
                _args[2] = IsActived;
                _args[3] = CreatedByUser;
                _args[4] = CreatedDate;
                System.IAsyncResult _result = base.BeginInvoke("Group_Add", _args, callback, asyncState);
                return _result;
            }
            
            public void EndGroup_Add(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("Group_Add", _args, result);
            }
            
            public System.IAsyncResult BeginGroup_Edit(int GroupID, string GroupName, string Descriptions, int IsActived, int ModifiedByUser, string ModifiedDate, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[6];
                _args[0] = GroupID;
                _args[1] = GroupName;
                _args[2] = Descriptions;
                _args[3] = IsActived;
                _args[4] = ModifiedByUser;
                _args[5] = ModifiedDate;
                System.IAsyncResult _result = base.BeginInvoke("Group_Edit", _args, callback, asyncState);
                return _result;
            }
            
            public void EndGroup_Edit(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("Group_Edit", _args, result);
            }
            
            public System.IAsyncResult BeginGroup_Delete(int GroupID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = GroupID;
                System.IAsyncResult _result = base.BeginInvoke("Group_Delete", _args, callback, asyncState);
                return _result;
            }
            
            public void EndGroup_Delete(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("Group_Delete", _args, result);
            }
            
            public System.IAsyncResult BeginGroup_GetItem(int GroupID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = GroupID;
                System.IAsyncResult _result = base.BeginInvoke("Group_GetItem", _args, callback, asyncState);
                return _result;
            }
            
            public QuanLyKhachSan.GroupSVC.GroupInfo EndGroup_GetItem(System.IAsyncResult result) {
                object[] _args = new object[0];
                QuanLyKhachSan.GroupSVC.GroupInfo _result = ((QuanLyKhachSan.GroupSVC.GroupInfo)(base.EndInvoke("Group_GetItem", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGroup_GetItems(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("Group_GetItems", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<QuanLyKhachSan.GroupSVC.GroupInfo> EndGroup_GetItems(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<QuanLyKhachSan.GroupSVC.GroupInfo> _result = ((System.Collections.Generic.List<QuanLyKhachSan.GroupSVC.GroupInfo>)(base.EndInvoke("Group_GetItems", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGroup_GetActivedItems(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("Group_GetActivedItems", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<QuanLyKhachSan.GroupSVC.GroupInfo> EndGroup_GetActivedItems(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<QuanLyKhachSan.GroupSVC.GroupInfo> _result = ((System.Collections.Generic.List<QuanLyKhachSan.GroupSVC.GroupInfo>)(base.EndInvoke("Group_GetActivedItems", _args, result)));
                return _result;
            }
        }
    }
}
